# Module 2: Career Growth Intelligence

## Objective

Analyze the key factors that influence career progression, promotion speed, and long-term professional growth within the AI workforce.

### Business Questions

- Does experience improve career growth?
- Which AI specializations have the highest career growth?
- Which countries provide the best career opportunities?
- Which job roles offer faster promotions?
- Does salary influence career growth?
- Which factors contribute most to promotion speed?

In [48]:
import warnings
import platform
import numpy as np
import pandas as pd

# Configure execution environment and suppress warnings
warnings.filterwarnings("ignore")

# Optimize pandas display configurations for comprehensive data inspection.
pd.set_option("display.max_columns", None)
pd.set_option("display.max_rows", 100)
pd.set_option("display.width", None)

# Log framework metadata and verification metrics.

print("Environment Information")
print("-" * 22)
print(f"Python Version : {platform.python_version()}")
print(f"Pandas Version : {pd.__version__}")
print(f"NumPy Version  : {np.__version__}")

Environment Information
----------------------
Python Version : 3.14.6
Pandas Version : 3.0.3
NumPy Version  : 2.4.6

In [49]:
# Load target dataset

DATA_PATH = "../../../data/processed/cleaned_ai_jobs.csv"
df = pd.read_csv(DATA_PATH)
print("\nDataset Loaded Successfully")

# Execute descriptive matrix shape verification.

print("\nDataset Shape")
print("-" * 16)

total_rows, total_columns = df.shape

print(f"Rows    : {total_rows:,}")
print(f"Columns : {total_columns}")
print("-" * 16)

# Display a quick preview of the dataset schema.

display(df.head())

Dataset Loaded Successfully

Dataset Shape
----------------
Rows    : 90,000
Columns : 35
----------------

,id,country,job_role,ai_specialization,experience_level,experience_years,salary_usd,bonus_usd,education_required,industry,company_size,interview_rounds,year,work_mode,weekly_hours,company_rating,job_openings,hiring_difficulty_score,layoff_risk,ai_adoption_score,company_funding_billion,economic_index,ai_maturity_years,offer_acceptance_rate,tax_rate_percent,vacation_days,skill_demand_score,automation_risk,job_security_score,career_growth_score,work_life_balance_score,promotion_speed,salary_percentile,cost_of_living_index,employee_satisfaction
0,1,UAE,Machine Learning Engineer,Reinforcement Learning,Entry,0,66465,5395,Master,Automotive,Small,7,2020,Remote,44.7,3.67,10,52.77,0.404,91,3.30,78.65,13,60.58,20.8,27,12,76,57,65,73,15,55,1.23,76
1,2,USA,AI Engineer,LLM,Entry,1,75507,11713,Bootcamp,Retail,Small,3,2021,Onsite,48.9,4.26,27,53.11,0.387,71,4.39,62.14,13,75.80,28.4,27,54,29,69,60,51,15,58,0.87,67
2,3,Brazil,Research Scientist,Analytics,Entry,0,41660,5268,Phd,Healthcare,Large,3,2020,Remote,46.8,4.78,10,76.40,0.415,69,5.04,87.47,8,62.95,12.2,13,12,49,70,59,68,37,13,2.13,61
3,4,India,AI Software Engineer,Computer Vision,Senior,6,43268,7975,Diploma,Tech,Large,2,2026,Onsite,52.2,4.34,23,59.34,0.115,74,4.38,86.84,7,77.45,35.1,30,80,47,79,65,55,46,74,1.49,56
4,5,Germany,Machine Learning Engineer,Computer Vision,Entry,0,69119,4758,Master,Retail,Medium,2,2021,Hybrid,46.7,4.49,17,72.30,0.311,68,6.67,79.84,7,89.86,36.1,24,82,47,64,52,69,17,21,0.87,72

## Career Growth Overview

**Business Question:** Analyze **career growth overview** to identify meaningful workforce trends and support career growth insights.

In [50]:
# Career Growth Overview

df[[
    "career_growth_score",
    "promotion_speed",
    "salary_percentile"
]].describe().round(2)

       career_growth_score  promotion_speed  salary_percentile
count              90000.0         90000.00           90000.00
mean                  57.2            38.44              50.54
std                   12.9            18.43              28.89
min                   25.0            12.00               1.00
25%                   48.0            24.00              25.00
50%                   57.0            37.00              51.00
75%                   66.0            51.00              76.00
max                   99.0            98.00             100.00

## Career Growth by Experience Level

**Business Question:** Analyze **career growth by experience level** to identify meaningful workforce trends and support career growth insights.

In [51]:
# Career Growth by Experience Level

df.groupby("experience_level")[
    "career_growth_score"
].agg(["mean", "median", "min", "max"]).round(2)

                   mean  median  min  max
experience_level
Entry             57.04    57.0   25   99
Lead              57.33    57.0   25   99
Mid               57.19    57.0   25   99
Senior            57.23    57.0   25   99

## Promotion Speed by Experience Level

**Business Question:** Analyze **promotion speed by experience level** to identify meaningful workforce trends and support career growth insights.

In [52]:
# Promotion Speed by Experience Level

df.groupby("experience_level")[
    "promotion_speed"
].agg(["mean", "median", "min", "max"]).round(2)

                   mean  median  min  max
experience_level
Entry             31.20    29.0   12   98
Lead              48.14    47.0   12   98
Mid               34.38    32.0   12   98
Senior            39.93    38.0   12   98

## Career Growth by Experience Years

**Business Question:** Analyze **career growth by experience years** to identify meaningful workforce trends and support career growth insights.

In [53]:
# Career Growth by Experience Years

df.groupby("experience_years")[
    "career_growth_score"
].mean().round(2)

experience_years
0     56.96
1     57.12
2     57.06
3     57.40
4     57.24
5     57.06
6     56.99
7     57.35
8     57.34
9     57.24
10    57.42
11    57.07
12    57.49
13    57.32
14    57.31
15    57.01
16    57.45
17    57.55
18    57.13
19    57.38
Name: career_growth_score, dtype: float64

## Career Growth by Country

**Business Question:** Analyze **career growth by country** to identify meaningful workforce trends and support career growth insights.

In [54]:
# Career Growth by Country

df.groupby("country")[
    "career_growth_score"
].mean().sort_values(ascending=False).round(2)

country
India          57.38
UAE            57.29
Singapore      57.29
Brazil         57.29
Australia      57.28
UK             57.24
Germany        57.22
Netherlands    57.18
Japan          57.15
Canada         57.08
USA            57.06
France         56.93
Name: career_growth_score, dtype: float64

## Career Growth by Job Role

**Business Question:** Analyze **career growth by job role** to identify meaningful workforce trends and support career growth insights.

In [55]:
# Career Growth by Job Role

df.groupby("job_role")[
    "career_growth_score"
].mean().sort_values(ascending=False).round(2)

job_role
AI Engineer                  57.30
Computer Vision Engineer     57.28
Research Scientist           57.28
NLP Engineer                 57.27
Data Scientist               57.24
Data Analyst                 57.17
AI Software Engineer         57.14
Machine Learning Engineer    56.91
Name: career_growth_score, dtype: float64

## Career Growth by AI Specialization

**Business Question:** Analyze **career growth by ai specialization** to identify meaningful workforce trends and support career growth insights.

In [56]:
# Career Growth by AI Specialization

df.groupby("ai_specialization")[
    "career_growth_score"
].mean().sort_values(ascending=False).round(2)

ai_specialization
LLM                       57.33
Generative AI             57.31
Analytics                 57.27
Reinforcement Learning    57.19
MLOps                     57.18
NLP                       57.14
Forecasting               57.10
Computer Vision           57.07
Name: career_growth_score, dtype: float64

## Promotion Speed by Job Role

**Business Question:** Analyze **promotion speed by job role** to identify meaningful workforce trends and support career growth insights.

In [57]:
# Promotion Speed by Job Role

df.groupby("job_role")[
    "promotion_speed"
].mean().sort_values(ascending=False).round(2)

job_role
AI Software Engineer         38.72
NLP Engineer                 38.64
Computer Vision Engineer     38.55
Data Scientist               38.47
AI Engineer                  38.43
Machine Learning Engineer    38.34
Data Analyst                 38.22
Research Scientist           38.15
Name: promotion_speed, dtype: float64

## Promotion Speed by AI Specialization

**Business Question:** Analyze **promotion speed by ai specialization** to identify meaningful workforce trends and support career growth insights.

In [58]:
# Promotion Speed by AI Specialization

df.groupby("ai_specialization")[
    "promotion_speed"
].mean().sort_values(ascending=False).round(2)

ai_specialization
Generative AI             38.68
LLM                       38.65
NLP                       38.54
Reinforcement Learning    38.50
MLOps                     38.43
Forecasting               38.33
Computer Vision           38.21
Analytics                 38.20
Name: promotion_speed, dtype: float64

## Salary Percentile by Experience Level

**Business Question:** Analyze **salary percentile by experience level** to identify meaningful workforce trends and support career growth insights.

In [59]:
# Salary Percentile by Experience Level

df.groupby("experience_level")[
    "salary_percentile"
].mean().round(2)

experience_level
Entry     50.69
Lead      50.34
Mid       50.51
Senior    50.62
Name: salary_percentile, dtype: float64

# Career Growth Intelligence - Ranking & Elite Segment Analysis

This notebook section contains ranking analysis, percentile analysis, and elite workforce segmentation for Career Growth Intelligence. Each business question is organized into its own markdown and code cell.

## Top 10 Countries by Career Growth Score

**Business Question:** Analyze **top 10 countries by career growth score** to identify high-performing segments, benchmark workforce performance, and support strategic career growth decisions.

In [60]:
# Top 10 Countries by Career Growth Score

df.groupby("country")[
    "career_growth_score"
].mean().sort_values(ascending=False).head(10).round(2)

country
India          57.38
UAE            57.29
Singapore      57.29
Brazil         57.29
Australia      57.28
UK             57.24
Germany        57.22
Netherlands    57.18
Japan          57.15
Canada         57.08
Name: career_growth_score, dtype: float64

## Bottom 10 Countries by Career Growth Score

**Business Question:** Analyze **bottom 10 countries by career growth score** to identify high-performing segments, benchmark workforce performance, and support strategic career growth decisions.

In [61]:
# Bottom 10 Countries by Career Growth Score

df.groupby("country")[
    "career_growth_score"
].mean().sort_values().head(10).round(2)

country
France         56.93
USA            57.06
Canada         57.08
Japan          57.15
Netherlands    57.18
Germany        57.22
UK             57.24
Australia      57.28
Brazil         57.29
Singapore      57.29
Name: career_growth_score, dtype: float64

## Top 10 Job Roles by Career Growth Score

**Business Question:** Analyze **top 10 job roles by career growth score** to identify high-performing segments, benchmark workforce performance, and support strategic career growth decisions.

In [62]:
# Top 10 Job Roles by Career Growth Score

df.groupby("job_role")[
    "career_growth_score"
].mean().sort_values(ascending=False).head(10).round(2)

job_role
AI Engineer                  57.30
Computer Vision Engineer     57.28
Research Scientist           57.28
NLP Engineer                 57.27
Data Scientist               57.24
Data Analyst                 57.17
AI Software Engineer         57.14
Machine Learning Engineer    56.91
Name: career_growth_score, dtype: float64

## Top 10 AI Specializations by Career Growth Score

**Business Question:** Analyze **top 10 ai specializations by career growth score** to identify high-performing segments, benchmark workforce performance, and support strategic career growth decisions.

In [63]:
# Top 10 AI Specializations by Career Growth Score

df.groupby("ai_specialization")[
    "career_growth_score"
].mean().sort_values(ascending=False).head(10).round(2)

ai_specialization
LLM                       57.33
Generative AI             57.31
Analytics                 57.27
Reinforcement Learning    57.19
MLOps                     57.18
NLP                       57.14
Forecasting               57.10
Computer Vision           57.07
Name: career_growth_score, dtype: float64

## Promotion Speed by Experience Level

**Business Question:** Analyze **promotion speed by experience level** to identify high-performing segments, benchmark workforce performance, and support strategic career growth decisions.

In [64]:
# Promotion Speed by Experience Level

df.groupby("experience_level")[
    "promotion_speed"
].mean().sort_values(ascending=False).round(2)

experience_level
Lead      48.14
Senior    39.93
Mid       34.38
Entry     31.20
Name: promotion_speed, dtype: float64

## Top 10 Experience Years by Career Growth Score

**Business Question:** Analyze **top 10 experience years by career growth score** to identify high-performing segments, benchmark workforce performance, and support strategic career growth decisions.

In [65]:
# Top 10 Experience Years by Career Growth Score

df.groupby("experience_years")[
    "career_growth_score"
].mean().sort_values(ascending=False).head(10).round(2)

experience_years
17    57.55
12    57.49
16    57.45
10    57.42
3     57.40
19    57.38
7     57.35
8     57.34
13    57.32
14    57.31
Name: career_growth_score, dtype: float64

## Career Growth Score Quartiles

**Business Question:** Analyze **career growth score quartiles** to identify high-performing segments, benchmark workforce performance, and support strategic career growth decisions.

In [66]:
# Career Growth Score Quartiles

df["career_growth_score"].quantile(
    [0.25, 0.50, 0.75]
).round(2)

0.25    48.0
0.50    57.0
0.75    66.0
Name: career_growth_score, dtype: float64

## Promotion Speed Quartiles

**Business Question:** Analyze **promotion speed quartiles** to identify high-performing segments, benchmark workforce performance, and support strategic career growth decisions.

In [67]:
# Promotion Speed Quartiles

df["promotion_speed"].quantile(
    [0.25, 0.50, 0.75]
).round(2)

0.25    24.0
0.50    37.0
0.75    51.0
Name: promotion_speed, dtype: float64

## Salary Percentile Quartiles

**Business Question:** Analyze **salary percentile quartiles** to identify high-performing segments, benchmark workforce performance, and support strategic career growth decisions.

In [68]:
# Salary Percentile Quartiles

df["salary_percentile"].quantile(
    [0.25, 0.50, 0.75]
).round(2)

0.25    25.0
0.50    51.0
0.75    76.0
Name: salary_percentile, dtype: float64

## Top 10% Career Growth Professionals

**Business Question:** Analyze **top 10% career growth professionals** to identify high-performing segments, benchmark workforce performance, and support strategic career growth decisions.

In [69]:
# Top 10% Career Growth Professionals

career_growth_top_10 = (
    df[
        df["career_growth_score"] >=
        df["career_growth_score"].quantile(0.90)
    ]
)

career_growth_top_10.head()

,id,country,job_role,ai_specialization,experience_level,experience_years,salary_usd,bonus_usd,education_required,industry,company_size,interview_rounds,year,work_mode,weekly_hours,company_rating,job_openings,hiring_difficulty_score,layoff_risk,ai_adoption_score,company_funding_billion,economic_index,ai_maturity_years,offer_acceptance_rate,tax_rate_percent,vacation_days,skill_demand_score,automation_risk,job_security_score,career_growth_score,work_life_balance_score,promotion_speed,salary_percentile,cost_of_living_index,employee_satisfaction
26,27,UK,Research Scientist,NLP,Entry,1,67130,13519,Phd,Finance,Enterprise,4,2022,Onsite,37.7,4.78,25,54.86,0.297,95,5.20,78.32,6,64.49,15.1,20,27,88,78,76,98,12,82,0.81,82
27,28,France,Computer Vision Engineer,Generative AI,Senior,9,126464,8212,Phd,Tech,Startup,2,2023,Remote,51.6,3.38,19,87.31,0.175,83,6.88,78.58,8,66.55,29.4,14,82,34,60,86,49,46,21,0.81,72
31,32,Germany,Research Scientist,LLM,Mid,3,89465,10234,Diploma,Finance,Large,3,2026,Remote,45.2,3.94,10,100.00,0.216,100,4.00,97.10,10,61.13,29.6,21,40,30,82,83,71,27,29,1.51,68
42,43,Germany,Research Scientist,Forecasting,Lead,14,180739,9690,Bachelor,Retail,Medium,7,2023,Hybrid,45.1,4.34,13,80.37,0.084,86,6.04,77.40,6,66.09,39.3,18,43,41,92,79,68,38,70,0.59,79
46,47,UK,AI Engineer,LLM,Lead,15,172678,34093,Bachelor,Education,Enterprise,7,2026,Hybrid,47.8,3.51,26,76.05,0.121,79,7.20,49.63,5,68.06,28.8,24,24,7,83,76,70,21,34,0.73,84

## Top 5% Career Growth Professionals

**Business Question:** Analyze **top 5% career growth professionals** to identify high-performing segments, benchmark workforce performance, and support strategic career growth decisions.

In [70]:
# Top 5% Career Growth Professionals

career_growth_top_5 = (
    df[
        df["career_growth_score"] >=
        df["career_growth_score"].quantile(0.95)
    ]
)

career_growth_top_5.head()

,id,country,job_role,ai_specialization,experience_level,experience_years,salary_usd,bonus_usd,education_required,industry,company_size,interview_rounds,year,work_mode,weekly_hours,company_rating,job_openings,hiring_difficulty_score,layoff_risk,ai_adoption_score,company_funding_billion,economic_index,ai_maturity_years,offer_acceptance_rate,tax_rate_percent,vacation_days,skill_demand_score,automation_risk,job_security_score,career_growth_score,work_life_balance_score,promotion_speed,salary_percentile,cost_of_living_index,employee_satisfaction
27,28,France,Computer Vision Engineer,Generative AI,Senior,9,126464,8212,Phd,Tech,Startup,2,2023,Remote,51.6,3.38,19,87.31,0.175,83,6.88,78.58,8,66.55,29.4,14,82,34,60,86,49,46,21,0.81,72
31,32,Germany,Research Scientist,LLM,Mid,3,89465,10234,Diploma,Finance,Large,3,2026,Remote,45.2,3.94,10,100.00,0.216,100,4.00,97.10,10,61.13,29.6,21,40,30,82,83,71,27,29,1.51,68
42,43,Germany,Research Scientist,Forecasting,Lead,14,180739,9690,Bachelor,Retail,Medium,7,2023,Hybrid,45.1,4.34,13,80.37,0.084,86,6.04,77.40,6,66.09,39.3,18,43,41,92,79,68,38,70,0.59,79
52,53,Canada,NLP Engineer,Generative AI,Senior,6,114541,22686,Master,Consulting,Small,7,2026,Onsite,37.5,4.24,26,45.37,0.125,80,8.52,71.36,13,79.63,21.9,18,79,69,83,86,93,26,100,1.44,83
53,54,Netherlands,Computer Vision Engineer,Analytics,Lead,16,141862,26137,Master,Education,Medium,2,2024,Hybrid,40.3,4.55,31,62.85,0.079,100,9.47,79.58,10,84.41,35.0,17,97,60,86,92,80,28,73,1.51,81

## Top 1% Career Growth Professionals

**Business Question:** Analyze **top 1% career growth professionals** to identify high-performing segments, benchmark workforce performance, and support strategic career growth decisions.

In [71]:
# Top 1% Career Growth Professionals

career_growth_top_1 = (
    df[
        df["career_growth_score"] >=
        df["career_growth_score"].quantile(0.99)
    ]
)

career_growth_top_1.head()

,id,country,job_role,ai_specialization,experience_level,experience_years,salary_usd,bonus_usd,education_required,industry,company_size,interview_rounds,year,work_mode,weekly_hours,company_rating,job_openings,hiring_difficulty_score,layoff_risk,ai_adoption_score,company_funding_billion,economic_index,ai_maturity_years,offer_acceptance_rate,tax_rate_percent,vacation_days,skill_demand_score,automation_risk,job_security_score,career_growth_score,work_life_balance_score,promotion_speed,salary_percentile,cost_of_living_index,employee_satisfaction
27,28,France,Computer Vision Engineer,Generative AI,Senior,9,126464,8212,Phd,Tech,Startup,2,2023,Remote,51.6,3.38,19,87.31,0.175,83,6.88,78.58,8,66.55,29.4,14,82,34,60,86,49,46,21,0.81,72
52,53,Canada,NLP Engineer,Generative AI,Senior,6,114541,22686,Master,Consulting,Small,7,2026,Onsite,37.5,4.24,26,45.37,0.125,80,8.52,71.36,13,79.63,21.9,18,79,69,83,86,93,26,100,1.44,83
53,54,Netherlands,Computer Vision Engineer,Analytics,Lead,16,141862,26137,Master,Education,Medium,2,2024,Hybrid,40.3,4.55,31,62.85,0.079,100,9.47,79.58,10,84.41,35.0,17,97,60,86,92,80,28,73,1.51,81
124,125,Australia,AI Software Engineer,MLOps,Mid,4,81521,17090,Diploma,Consulting,Enterprise,3,2021,Onsite,43.3,3.21,19,45.98,0.108,92,8.91,68.85,6,58.71,34.5,19,61,25,84,86,84,15,48,2.33,80
134,135,UK,Data Scientist,MLOps,Entry,1,70233,4650,Master,Consulting,Startup,2,2026,Remote,42.7,4.16,27,100.00,0.297,97,6.50,80.98,3,90.57,29.4,20,40,66,56,87,71,38,51,1.76,66

# Career Growth Intelligence - Multi-Factor Analysis

This notebook section explores relationships between multiple workforce variables using correlation analysis, pivot tables, and cross-tabulations. Each analysis answers a specific business question and is organized into separate markdown and code cells.

## Correlation with Career Growth Score

**Business Question:** Analyze **correlation with career growth score** to uncover multi-dimensional workforce patterns and support data-driven career growth decisions.

In [72]:
# Correlation with Career Growth Score

career_growth_corr = (
    df[[
        "career_growth_score",
        "promotion_speed",
        "salary_percentile",
        "experience_years",
        "salary_usd",
        "bonus_usd",
        "company_rating",
        "skill_demand_score",
        "job_security_score",
        "work_life_balance_score",
        "employee_satisfaction"
    ]]
    .corr()["career_growth_score"]
    .sort_values(ascending=False)
    .round(2)
)

career_growth_corr

career_growth_score        1.00
job_security_score         0.06
employee_satisfaction      0.01
experience_years           0.01
promotion_speed            0.01
bonus_usd                  0.00
salary_usd                 0.00
skill_demand_score         0.00
salary_percentile         -0.00
company_rating            -0.00
work_life_balance_score   -0.01
Name: career_growth_score, dtype: float64

## Average Career Growth by Country and Experience Level

**Business Question:** Analyze **average career growth by country and experience level** to uncover multi-dimensional workforce patterns and support data-driven career growth decisions.

In [73]:
# Average Career Growth by Country and Experience Level

pd.pivot_table(
    df,
    values="career_growth_score",
    index="country",
    columns="experience_level",
    aggfunc="mean"
).round(2)

experience_level  Entry   Lead    Mid  Senior
country
Australia         57.14  57.28  57.16   57.55
Brazil            57.23  57.60  57.16   57.15
Canada            56.54  57.40  57.33   57.04
France            56.48  57.03  57.17   57.07
Germany           57.10  57.35  57.11   57.30
India             57.09  57.58  57.44   57.42
Japan             57.05  57.30  57.07   57.16
Netherlands       57.30  57.29  56.69   57.45
Singapore         57.30  57.46  57.36   57.06
UAE               57.39  57.04  57.26   57.49
UK                56.74  57.62  57.35   57.25
USA               57.18  56.99  57.18   56.88

## Average Career Growth by AI Specialization and Experience Level

**Business Question:** Analyze **average career growth by ai specialization and experience level** to uncover multi-dimensional workforce patterns and support data-driven career growth decisions.

In [74]:
# Average Career Growth by AI Specialization and Experience Level

pd.pivot_table(
    df,
    values="career_growth_score",
    index="ai_specialization",
    columns="experience_level",
    aggfunc="mean"
).round(2)

experience_level        Entry   Lead    Mid  Senior
ai_specialization
Analytics               57.08  57.14  57.59   57.24
Computer Vision         56.71  57.15  57.11   57.29
Forecasting             57.21  57.02  57.04   57.12
Generative AI           57.12  57.48  57.19   57.43
LLM                     57.40  57.23  57.07   57.62
MLOps                   57.12  57.42  57.21   56.97
NLP                     56.64  57.73  57.14   57.06
Reinforcement Learning  57.04  57.46  57.15   57.12

## Average Career Growth by Job Role and Experience Level

**Business Question:** Analyze **average career growth by job role and experience level** to uncover multi-dimensional workforce patterns and support data-driven career growth decisions.

In [75]:
# Average Career Growth by Job Role and Experience Level

pd.pivot_table(
    df,
    values="career_growth_score",
    index="job_role",
    columns="experience_level",
    aggfunc="mean"
).round(2)

experience_level           Entry   Lead    Mid  Senior
job_role
AI Engineer                57.09  57.63  57.36   57.12
AI Software Engineer       57.25  57.14  56.85   57.29
Computer Vision Engineer   56.72  57.89  57.51   57.01
Data Analyst               57.37  56.98  56.84   57.47
Data Scientist             57.14  57.42  57.16   57.25
Machine Learning Engineer  56.80  56.77  56.95   57.13
NLP Engineer               56.94  57.51  57.26   57.36
Research Scientist         57.04  57.27  57.58   57.23

## Average Promotion Speed by AI Specialization

**Business Question:** Analyze **average promotion speed by ai specialization** to uncover multi-dimensional workforce patterns and support data-driven career growth decisions.

In [76]:
# Average Promotion Speed by AI Specialization

pd.pivot_table(
    df,
    values="promotion_speed",
    index="ai_specialization",
    columns="experience_level",
    aggfunc="mean"
).round(2)

experience_level        Entry   Lead    Mid  Senior
ai_specialization
Analytics               30.51  48.26  34.28   39.81
Computer Vision         30.81  47.87  33.94   39.75
Forecasting             31.44  47.99  34.34   39.71
Generative AI           31.77  48.69  34.01   39.90
LLM                     31.55  48.69  34.28   39.69
MLOps                   31.30  47.44  34.69   40.19
NLP                     31.02  47.74  34.94   40.35
Reinforcement Learning  31.22  48.40  34.54   40.07

## Average Salary Percentile by Job Role

**Business Question:** Analyze **average salary percentile by job role** to uncover multi-dimensional workforce patterns and support data-driven career growth decisions.

In [77]:
# Average Salary Percentile by Job Role

pd.pivot_table(
    df,
    values="salary_percentile",
    index="job_role",
    columns="experience_level",
    aggfunc="mean"
).round(2)

experience_level           Entry   Lead    Mid  Senior
job_role
AI Engineer                51.32  50.81  50.38   50.47
AI Software Engineer       50.43  50.50  50.90   50.89
Computer Vision Engineer   50.87  50.11  50.79   50.62
Data Analyst               50.30  49.50  50.86   50.96
Data Scientist             51.31  51.27  50.39   51.10
Machine Learning Engineer  50.26  49.85  50.57   50.12
NLP Engineer               50.75  50.01  50.47   50.97
Research Scientist         50.33  50.68  49.75   49.85

## Career Growth by Country and AI Specialization

**Business Question:** Analyze **career growth by country and ai specialization** to uncover multi-dimensional workforce patterns and support data-driven career growth decisions.

In [78]:
# Career Growth by Country and AI Specialization

pd.crosstab(
    index=df["country"],
    columns=df["ai_specialization"],
    values=df["career_growth_score"],
    aggfunc="mean"
).round(2)

ai_specialization,Analytics,Computer Vision,Forecasting,Generative AI,LLM,MLOps,NLP,Reinforcement Learning
country,,,,,,,,
Australia,57.41,57.36,57.23,57.06,57.58,56.62,57.54,57.48
Brazil,57.66,56.70,57.59,57.41,56.94,57.29,57.19,57.57
Canada,56.86,57.43,56.62,57.12,57.33,56.96,57.08,57.21
France,56.63,57.31,56.77,57.14,56.77,57.23,56.84,56.75
Germany,57.00,56.86,57.79,58.19,56.79,56.72,57.42,56.90
India,57.42,57.23,56.97,57.30,57.74,57.28,57.32,57.76
Japan,57.17,56.60,57.60,57.66,57.35,57.00,57.30,56.60
Netherlands,57.28,57.39,56.28,57.31,57.92,57.97,56.83,56.33
Singapore,58.19,56.94,56.90,57.16,57.02,58.21,56.95,57.06
UAE,57.34,56.71,57.30,57.16,57.89,56.93,56.98,57.99
UK,57.49,57.65,57.37,56.97,57.46,56.57,56.97,57.36
USA,56.73,56.70,56.75,57.26,57.13,57.46,57.28,57.18

## Promotion Speed by Country and Job Role

**Business Question:** Analyze **promotion speed by country and job role** to uncover multi-dimensional workforce patterns and support data-driven career growth decisions.

In [79]:
# Promotion Speed by Country and Job Role

pd.crosstab(
    index=df["country"],
    columns=df["job_role"],
    values=df["promotion_speed"],
    aggfunc="mean"
).round(2)

job_role,AI Engineer,AI Software Engineer,Computer Vision Engineer,Data Analyst,Data Scientist,Machine Learning Engineer,NLP Engineer,Research Scientist
country,,,,,,,,
Australia,38.14,38.60,37.68,38.37,38.53,37.76,38.43,38.35
Brazil,38.65,38.61,39.10,38.05,37.94,38.88,38.40,38.90
Canada,38.46,38.06,38.09,37.24,37.62,37.85,39.25,38.92
France,37.03,39.66,38.74,38.45,38.96,38.80,39.98,37.27
Germany,39.31,39.74,38.17,37.15,38.37,38.21,39.07,37.80
India,38.27,39.29,38.51,38.13,38.68,38.17,38.96,38.58
Japan,39.60,38.15,39.20,38.32,38.03,38.22,38.43,37.31
Netherlands,38.41,38.76,38.13,37.90,39.12,39.10,37.45,38.35
Singapore,38.68,38.36,38.37,39.16,38.46,37.95,38.06,37.48
UAE,38.34,39.29,38.50,38.85,38.92,38.71,38.54,38.37
UK,38.56,38.07,39.69,38.36,38.32,37.97,38.33,38.64
USA,37.59,38.14,38.46,38.77,38.63,38.49,38.80,37.76

# Career Growth Intelligence - Feature Engineering

This notebook section creates engineered workforce metrics to quantify career progression, promotion efficiency, growth potential, and career momentum. Each engineered feature and its analysis is organized into separate markdown and code cells.

## Career Acceleration Index

**Business Question:** Evaluate **career acceleration index** to derive actionable workforce intelligence from engineered career growth metrics and identify high-performing talent segments.

In [80]:
# Career Acceleration Index

df["career_acceleration_index"] = (
    df["career_growth_score"] /
    (df["experience_years"] + 1)
).round(2)

## Promotion Efficiency Index

**Business Question:** Evaluate **promotion efficiency index** to derive actionable workforce intelligence from engineered career growth metrics and identify high-performing talent segments.

In [81]:
# Promotion Efficiency Index

df["promotion_efficiency"] = (
    df["promotion_speed"] /
    (df["experience_years"] + 1)
).round(2)

## Career Momentum Score

**Business Question:** Evaluate **career momentum score** to derive actionable workforce intelligence from engineered career growth metrics and identify high-performing talent segments.

In [82]:
# Career Momentum Score

df["career_momentum_score"] = (
    (
        df["career_growth_score"] +
        df["promotion_speed"] +
        df["salary_percentile"]
    ) / 3
).round(2)

## Growth Potential Index

**Business Question:** Evaluate **growth potential index** to derive actionable workforce intelligence from engineered career growth metrics and identify high-performing talent segments.

In [83]:
# Growth Potential Index

df["growth_potential_index"] = (
    (
        df["career_growth_score"] *
        df["skill_demand_score"]
    ) / 100
).round(2)

## Experience Efficiency Score

**Business Question:** Evaluate **experience efficiency score** to derive actionable workforce intelligence from engineered career growth metrics and identify high-performing talent segments.

In [84]:
# Experience Efficiency Score

df["experience_efficiency_score"] = (
    df["career_growth_score"] /
    (df["experience_years"] + 1)
).round(2)

## Engineered Features Summary

**Business Question:** Evaluate **engineered features summary** to derive actionable workforce intelligence from engineered career growth metrics and identify high-performing talent segments.

In [85]:
# Engineered Features Summary

df[[
    "career_acceleration_index",
    "promotion_efficiency",
    "career_momentum_score",
    "growth_potential_index",
    "experience_efficiency_score"
]].describe().round(2)

,career_acceleration_index,promotion_efficiency,career_momentum_score,growth_potential_index,experience_efficiency_score
count,90000.00,90000.00,90000.00,90000.00,90000.00
mean,16.45,9.61,48.73,28.87,16.45
std,18.00,11.28,12.21,18.13,18.00
min,1.25,0.63,12.67,0.25,1.25
25%,4.45,3.07,39.67,13.72,4.45
50%,8.40,5.25,48.67,27.30,8.40
75%,21.50,11.67,57.33,42.00,21.50
max,99.00,98.00,93.33,93.10,99.00

## Top Career Acceleration

**Business Question:** Evaluate **top career acceleration** to derive actionable workforce intelligence from engineered career growth metrics and identify high-performing talent segments.

In [86]:
# Top Career Acceleration

df.nlargest(
    10,
    "career_acceleration_index"
)[[
    "job_role",
    "country",
    "career_acceleration_index"
]]

                        job_role    country  career_acceleration_index
38858  Machine Learning Engineer        UAE                       99.0
32505                AI Engineer  Australia                       97.0
35601         Research Scientist  Singapore                       97.0
2626        AI Software Engineer     Brazil                       96.0
11754               NLP Engineer  Singapore                       96.0
20016             Data Scientist        USA                       96.0
35110               Data Analyst     Brazil                       95.0
63117               NLP Engineer      Japan                       95.0
72137               NLP Engineer         UK                       95.0
19758                AI Engineer        USA                       94.0

## Top Career Momentum

**Business Question:** Evaluate **top career momentum** to derive actionable workforce intelligence from engineered career growth metrics and identify high-performing talent segments.

In [87]:
# Top Career Momentum

df.nlargest(
    10,
    "career_momentum_score"
)[[
    "job_role",
    "country",
    "career_momentum_score"
]]

                        job_role    country  career_momentum_score
74727             Data Scientist  Australia                  93.33
32446       AI Software Engineer  Singapore                  91.33
40818             Data Scientist         UK                  91.33
84670  Machine Learning Engineer        UAE                  90.00
78404       AI Software Engineer     France                  89.67
33827               NLP Engineer        USA                  89.33
79881             Data Scientist        USA                  89.33
5110          Research Scientist     Brazil                  89.00
27508                AI Engineer        USA                  88.67
35986   Computer Vision Engineer    Germany                  88.67

## Highest Growth Potential

**Business Question:** Evaluate **highest growth potential** to derive actionable workforce intelligence from engineered career growth metrics and identify high-performing talent segments.

In [88]:
# Highest Growth Potential

df.nlargest(
    10,
    "growth_potential_index"
)[[
    "job_role",
    "country",
    "growth_potential_index"
]]

                        job_role      country  growth_potential_index
6644              Data Scientist        India                   93.10
78391  Machine Learning Engineer  Netherlands                   93.10
35351             Data Scientist           UK                   92.00
78571             Data Scientist       France                   91.00
55405  Machine Learning Engineer    Australia                   90.09
53      Computer Vision Engineer  Netherlands                   89.24
2776   Machine Learning Engineer    Singapore                   89.10
10989         Research Scientist       Brazil                   89.10
33468                AI Engineer       Canada                   89.10
89422             Data Scientist           UK                   89.10

## Correlation of Engineered Features

**Business Question:** Evaluate **correlation of engineered features** to derive actionable workforce intelligence from engineered career growth metrics and identify high-performing talent segments.

In [89]:
# Correlation of Engineered Features

df[[
    "career_growth_score",
    "promotion_speed",
    "career_acceleration_index",
    "promotion_efficiency",
    "career_momentum_score",
    "growth_potential_index",
    "experience_efficiency_score"
]].corr().round(2)

,career_growth_score,promotion_speed,career_acceleration_index,promotion_efficiency,career_momentum_score,growth_potential_index,experience_efficiency_score
career_growth_score,1.00,0.01,0.20,-0.00,0.35,0.36,0.20
promotion_speed,0.01,1.00,-0.25,0.18,0.51,-0.00,-0.25
career_acceleration_index,0.20,-0.25,1.00,0.76,-0.05,0.07,1.00
promotion_efficiency,-0.00,0.18,0.76,1.00,0.09,-0.01,0.76
career_momentum_score,0.35,0.51,-0.05,0.09,1.00,0.12,-0.05
growth_potential_index,0.36,-0.00,0.07,-0.01,0.12,1.00,0.07
experience_efficiency_score,0.20,-0.25,1.00,0.76,-0.05,0.07,1.00