# Module 6: Recruitment Intelligence

## Objective

Analyze recruitment effectiveness by evaluating offer acceptance, interview process efficiency, hiring difficulty, and candidate decision patterns.

### Business Questions

- What influences offer acceptance?
- Does salary improve offer acceptance?
- Does hiring difficulty reduce acceptance?
- Which countries have the highest offer acceptance?
- Which job roles experience better recruitment success?

In [16]:
import warnings
import platform
import numpy as np
import pandas as pd

# Configure execution environment and suppress warnings
warnings.filterwarnings("ignore")

# Optimize pandas display configurations for comprehensive data inspection.
pd.set_option("display.max_columns", None)
pd.set_option("display.max_rows", 100)
pd.set_option("display.width", None)

# Log framework metadata and verification metrics.

print("Environment Information")
print("-" * 22)
print(f"Python Version : {platform.python_version()}")
print(f"Pandas Version : {pd.__version__}")
print(f"NumPy Version  : {np.__version__}")

Environment Information
----------------------
Python Version : 3.14.6
Pandas Version : 3.0.3
NumPy Version  : 2.4.6

In [17]:
# Load target dataset

DATA_PATH = "../../../data/processed/cleaned_ai_jobs.csv"
df = pd.read_csv(DATA_PATH)
print("\nDataset Loaded Successfully")

# Execute descriptive matrix shape verification.

print("\nDataset Shape")
print("-" * 16)

total_rows, total_columns = df.shape

print(f"Rows    : {total_rows:,}")
print(f"Columns : {total_columns}")
print("-" * 16)

# Display a quick preview of the dataset schema.

display(df.head())

Dataset Loaded Successfully

Dataset Shape
----------------
Rows    : 90,000
Columns : 35
----------------

,id,country,job_role,ai_specialization,experience_level,experience_years,salary_usd,bonus_usd,education_required,industry,company_size,interview_rounds,year,work_mode,weekly_hours,company_rating,job_openings,hiring_difficulty_score,layoff_risk,ai_adoption_score,company_funding_billion,economic_index,ai_maturity_years,offer_acceptance_rate,tax_rate_percent,vacation_days,skill_demand_score,automation_risk,job_security_score,career_growth_score,work_life_balance_score,promotion_speed,salary_percentile,cost_of_living_index,employee_satisfaction
0,1,UAE,Machine Learning Engineer,Reinforcement Learning,Entry,0,66465,5395,Master,Automotive,Small,7,2020,Remote,44.7,3.67,10,52.77,0.404,91,3.30,78.65,13,60.58,20.8,27,12,76,57,65,73,15,55,1.23,76
1,2,USA,AI Engineer,LLM,Entry,1,75507,11713,Bootcamp,Retail,Small,3,2021,Onsite,48.9,4.26,27,53.11,0.387,71,4.39,62.14,13,75.80,28.4,27,54,29,69,60,51,15,58,0.87,67
2,3,Brazil,Research Scientist,Analytics,Entry,0,41660,5268,Phd,Healthcare,Large,3,2020,Remote,46.8,4.78,10,76.40,0.415,69,5.04,87.47,8,62.95,12.2,13,12,49,70,59,68,37,13,2.13,61
3,4,India,AI Software Engineer,Computer Vision,Senior,6,43268,7975,Diploma,Tech,Large,2,2026,Onsite,52.2,4.34,23,59.34,0.115,74,4.38,86.84,7,77.45,35.1,30,80,47,79,65,55,46,74,1.49,56
4,5,Germany,Machine Learning Engineer,Computer Vision,Entry,0,69119,4758,Master,Retail,Medium,2,2021,Hybrid,46.7,4.49,17,72.30,0.311,68,6.67,79.84,7,89.86,36.1,24,82,47,64,52,69,17,21,0.87,72

# Recruitment Intelligence

This notebook contains the foundation analysis, relationship analytics, and feature engineering for Recruitment Intelligence.

## Recruitment Overview

**Business Question:** What are the overall recruitment metrics?

In [18]:
df[[
    "offer_acceptance_rate",
    "interview_rounds",
    "hiring_difficulty_score"
]].describe().round(2)

       offer_acceptance_rate  interview_rounds  hiring_difficulty_score
count               90000.00           90000.0                 90000.00
mean                   75.01               4.5                    55.03
std                    11.51               1.7                    17.90
min                    55.00               2.0                     0.00
25%                    65.07               3.0                    42.88
50%                    75.00               4.0                    55.07
75%                    84.99               6.0                    67.12
max                    95.00               7.0                   100.00

## Offer Acceptance by Country

**Business Question:** How does offer acceptance vary across countries?

In [19]:
df.groupby("country")["offer_acceptance_rate"].agg(["mean","median","min","max"]).round(2)

              mean  median    min    max
country
Australia    74.93   74.87  55.00  95.00
Brazil       75.00   74.87  55.00  95.00
Canada       75.13   75.10  55.00  94.99
France       75.33   75.45  55.01  95.00
Germany      75.05   74.99  55.00  94.99
India        74.90   75.02  55.01  94.99
Japan        75.04   75.16  55.00  94.99
Netherlands  74.97   75.06  55.00  95.00
Singapore    74.94   74.93  55.00  94.99
UAE          74.91   74.94  55.01  95.00
UK           75.06   75.06  55.00  95.00
USA          74.85   74.81  55.01  95.00

## Offer Acceptance by Job Role

**Business Question:** Which job roles have the highest offer acceptance?

In [20]:
df.groupby("job_role")["offer_acceptance_rate"].mean().sort_values(ascending=False).round(2)

job_role
Data Analyst                 75.19
Machine Learning Engineer    75.12
Data Scientist               74.99
Computer Vision Engineer     74.99
Research Scientist           74.99
AI Software Engineer         74.96
NLP Engineer                 74.93
AI Engineer                  74.89
Name: offer_acceptance_rate, dtype: float64

## Offer Acceptance by AI Specialization

**Business Question:** Which AI specializations have the highest offer acceptance?

In [21]:
df.groupby("ai_specialization")["offer_acceptance_rate"].mean().sort_values(ascending=False).round(2)

ai_specialization
LLM                       75.21
NLP                       75.06
Analytics                 75.03
MLOps                     75.01
Computer Vision           75.01
Forecasting               74.94
Reinforcement Learning    74.92
Generative AI             74.90
Name: offer_acceptance_rate, dtype: float64

## Offer Acceptance by Industry

**Business Question:** How does offer acceptance vary across industries?

In [22]:
df.groupby("industry")["offer_acceptance_rate"].mean().sort_values(ascending=False).round(2)

industry
Retail        75.11
Finance       75.09
Telecom       75.05
Education     75.04
Energy        75.02
Consulting    74.99
Gaming        74.97
Tech          74.96
Automotive    74.93
Healthcare    74.93
Name: offer_acceptance_rate, dtype: float64

# Recruitment Intelligence - Relationship Analytics

## Correlation with Offer Acceptance

**Business Question:** Which variables influence offer acceptance?

In [23]:
recruitment_corr=(df[[
"offer_acceptance_rate","salary_usd","bonus_usd","interview_rounds",
"hiring_difficulty_score","career_growth_score","company_rating",
"employee_satisfaction"]].corr()["offer_acceptance_rate"].sort_values(ascending=False).round(2))
recruitment_corr

offer_acceptance_rate      1.00
career_growth_score        0.00
employee_satisfaction      0.00
salary_usd                -0.00
bonus_usd                 -0.00
interview_rounds          -0.00
company_rating            -0.00
hiring_difficulty_score   -0.01
Name: offer_acceptance_rate, dtype: float64

## Offer Acceptance by Experience Level

**Business Question:** How does offer acceptance vary by experience and work mode?

In [24]:
pd.pivot_table(df,values="offer_acceptance_rate",index="experience_level",columns="work_mode",aggfunc="mean").round(2)

work_mode         Hybrid  Onsite  Remote
experience_level
Entry              74.86   74.91   75.01
Lead               74.91   75.05   74.97
Mid                74.91   74.98   75.25
Senior             75.17   75.05   75.04

## Offer Acceptance by Industry

**Business Question:** How does offer acceptance vary by industry and experience?

In [25]:
pd.pivot_table(df,values="offer_acceptance_rate",index="industry",columns="experience_level",aggfunc="mean").round(2)

experience_level  Entry   Lead    Mid  Senior
industry
Automotive        74.80  74.93  75.08   74.92
Consulting        74.94  74.82  75.02   75.20
Education         74.80  74.68  75.16   75.52
Energy            74.78  75.19  75.28   74.85
Finance           74.94  75.44  74.71   75.27
Gaming            74.77  74.90  75.19   75.00
Healthcare        75.24  74.85  74.71   74.90
Retail            75.22  75.14  75.05   75.04
Tech              74.54  74.73  75.26   75.30
Telecom           75.24  75.08  75.01   74.86

## Hiring Difficulty by Job Role

**Business Question:** How does hiring difficulty vary across job roles?

In [26]:
pd.crosstab(index=df["job_role"],columns=df["experience_level"],values=df["hiring_difficulty_score"],aggfunc="mean").round(2)

experience_level           Entry   Lead    Mid  Senior
job_role
AI Engineer                54.49  55.31  55.12   55.22
AI Software Engineer       54.60  55.14  54.78   55.20
Computer Vision Engineer   55.08  54.93  54.98   55.10
Data Analyst               54.57  55.70  54.94   55.11
Data Scientist             55.63  54.80  54.78   54.96
Machine Learning Engineer  54.94  55.07  54.91   55.29
NLP Engineer               55.33  54.52  55.17   55.44
Research Scientist         55.42  55.05  54.77   54.60

# Recruitment Intelligence - Feature Engineering

## Recruitment Success Index

**Business Question:** Can recruitment effectiveness be summarized into one metric?

In [27]:
df["recruitment_success_index"]=((df["offer_acceptance_rate"]+(100-df["hiring_difficulty_score"])+(100-(df["interview_rounds"]*10)))/3).round(2)

## Candidate Attraction Score

**Business Question:** Can candidate attraction be summarized into one metric?

In [28]:
df["candidate_attraction_score"]=((df["offer_acceptance_rate"]+df["salary_percentile"]+df["company_rating"]*20)/3).round(2)

## Recruitment Metrics Summary

**Business Question:** What is the summary of engineered metrics?

In [29]:
df[["recruitment_success_index","candidate_attraction_score"]].describe().round(2)

       recruitment_success_index  candidate_attraction_score
count                   90000.00                    90000.00
mean                       58.34                       68.50
std                         9.12                       10.81
min                        28.65                       40.39
25%                        51.94                       60.06
50%                        58.35                       68.49
75%                        64.71                       76.91
max                        91.06                       96.47

## Top Recruitment Success

**Business Question:** Which records have the highest recruitment success index?

In [30]:
df.nlargest(10,"recruitment_success_index")[["job_role","country","recruitment_success_index"]]

                        job_role    country  recruitment_success_index
55238             Data Scientist      Japan                      91.06
39515   Computer Vision Engineer      Japan                      90.39
67969               Data Analyst        UAE                      90.14
86542   Computer Vision Engineer  Australia                      90.00
81287   Computer Vision Engineer      India                      89.60
19453               Data Analyst        UAE                      89.23
710           Research Scientist  Australia                      88.90
18848  Machine Learning Engineer    Germany                      88.80
76264       AI Software Engineer        USA                      88.76
82542   Computer Vision Engineer     Canada                      88.53