### Section 1: Imports

In [1]:
import pandas as pd
import numpy as np
import warnings

warnings.filterwarnings("ignore")

pd.set_option("display.max_columns", None)
pd.set_option("display.max_rows", 100)

print("\nEnvironment Information")
print("-" * 22)

print(f"Pandas Version : {pd.__version__}")
print(f"NumPy Version  : {np.__version__}")

Environment Information
----------------------
Pandas Version : 3.0.3
NumPy Version  : 2.4.6

### Section 2: Load Dataset and copy

In [2]:
df = pd.read_excel("../data/raw/ai_jobs.xlsx")

df_clean = df.copy()

print("-" * 28)
print("Dataset loaded successfully")
print("-" * 28)

print(f"Rows    : {df_clean.shape[0]:,}")
print(f"Columns : {df_clean.shape[1]}")

df_clean.head()

----------------------------
Dataset loaded successfully
----------------------------
Rows    : 90,000
Columns : 35

,id,country,job_role,ai_specialization,experience_level,experience_years,salary_usd,bonus_usd,education_required,industry,company_size,interview_rounds,year,work_mode,weekly_hours,company_rating,job_openings,hiring_difficulty_score,layoff_risk,ai_adoption_score,company_funding_billion,economic_index,ai_maturity_years,offer_acceptance_rate,tax_rate_percent,vacation_days,skill_demand_score,automation_risk,job_security_score,career_growth_score,work_life_balance_score,promotion_speed,salary_percentile,cost_of_living_index,employee_satisfaction
0,1,UAE,Machine Learning Engineer,Reinforcement Learning,Entry,0,66465,5395,Master,Automotive,Small,7,2020,Remote,44.7,3.67,10,52.765351,0.404,91,3.30,78.65,13,60.58,20.8,27,12,76,57,65,73,15,55,1.23,76
1,2,USA,AI Engineer,LLM,Entry,1,75507,11713,Bootcamp,Retail,Small,3,2021,Onsite,48.9,4.26,27,53.114580,0.387,71,4.39,62.14,13,75.80,28.4,27,54,29,69,60,51,15,58,0.87,67
2,3,Brazil,Research Scientist,Analytics,Entry,0,41660,5268,PhD,Healthcare,Large,3,2020,Remote,46.8,4.78,10,76.395263,0.415,69,5.04,87.47,8,62.95,12.2,13,12,49,70,59,68,37,13,2.13,61
3,4,India,Software Engineer AI,Computer Vision,Senior,6,43268,7975,Diploma,Tech,Large,2,2026,Onsite,52.2,4.34,23,59.340199,0.115,74,4.38,86.84,7,77.45,35.1,30,80,47,79,65,55,46,74,1.49,56
4,5,Germany,Machine Learning Engineer,Computer Vision,Entry,0,69119,4758,Master,Retail,Medium,2,2021,Hybrid,46.7,4.49,17,72.301128,0.311,68,6.67,79.84,7,89.86,36.1,24,82,47,64,52,69,17,21,0.87,72

### Section 3: Missing value treatment

In [3]:
numerical_columns = (
    df_clean.select_dtypes(
        include=np.number
    ).columns
)

for col in numerical_columns:

    df_clean[col] = (
        df_clean[col]
        .fillna(
            df_clean[col].median()
        )
    )

df_clean.head()

,id,country,job_role,ai_specialization,experience_level,experience_years,salary_usd,bonus_usd,education_required,industry,company_size,interview_rounds,year,work_mode,weekly_hours,company_rating,job_openings,hiring_difficulty_score,layoff_risk,ai_adoption_score,company_funding_billion,economic_index,ai_maturity_years,offer_acceptance_rate,tax_rate_percent,vacation_days,skill_demand_score,automation_risk,job_security_score,career_growth_score,work_life_balance_score,promotion_speed,salary_percentile,cost_of_living_index,employee_satisfaction
0,1,UAE,Machine Learning Engineer,Reinforcement Learning,Entry,0,66465,5395,Master,Automotive,Small,7,2020,Remote,44.7,3.67,10,52.765351,0.404,91,3.30,78.65,13,60.58,20.8,27,12,76,57,65,73,15,55,1.23,76
1,2,USA,AI Engineer,LLM,Entry,1,75507,11713,Bootcamp,Retail,Small,3,2021,Onsite,48.9,4.26,27,53.114580,0.387,71,4.39,62.14,13,75.80,28.4,27,54,29,69,60,51,15,58,0.87,67
2,3,Brazil,Research Scientist,Analytics,Entry,0,41660,5268,PhD,Healthcare,Large,3,2020,Remote,46.8,4.78,10,76.395263,0.415,69,5.04,87.47,8,62.95,12.2,13,12,49,70,59,68,37,13,2.13,61
3,4,India,Software Engineer AI,Computer Vision,Senior,6,43268,7975,Diploma,Tech,Large,2,2026,Onsite,52.2,4.34,23,59.340199,0.115,74,4.38,86.84,7,77.45,35.1,30,80,47,79,65,55,46,74,1.49,56
4,5,Germany,Machine Learning Engineer,Computer Vision,Entry,0,69119,4758,Master,Retail,Medium,2,2021,Hybrid,46.7,4.49,17,72.301128,0.311,68,6.67,79.84,7,89.86,36.1,24,82,47,64,52,69,17,21,0.87,72

### Section 4: Categorical Columns treatment

In [4]:
categorical_columns = (
    df_clean.select_dtypes(
        include=["object"]
    ).columns
)

for col in categorical_columns:

    df_clean[col] = (
        df_clean[col]
        .fillna(
            df_clean[col].mode()[0]
        )
    )

df_clean.head()

,id,country,job_role,ai_specialization,experience_level,experience_years,salary_usd,bonus_usd,education_required,industry,company_size,interview_rounds,year,work_mode,weekly_hours,company_rating,job_openings,hiring_difficulty_score,layoff_risk,ai_adoption_score,company_funding_billion,economic_index,ai_maturity_years,offer_acceptance_rate,tax_rate_percent,vacation_days,skill_demand_score,automation_risk,job_security_score,career_growth_score,work_life_balance_score,promotion_speed,salary_percentile,cost_of_living_index,employee_satisfaction
0,1,UAE,Machine Learning Engineer,Reinforcement Learning,Entry,0,66465,5395,Master,Automotive,Small,7,2020,Remote,44.7,3.67,10,52.765351,0.404,91,3.30,78.65,13,60.58,20.8,27,12,76,57,65,73,15,55,1.23,76
1,2,USA,AI Engineer,LLM,Entry,1,75507,11713,Bootcamp,Retail,Small,3,2021,Onsite,48.9,4.26,27,53.114580,0.387,71,4.39,62.14,13,75.80,28.4,27,54,29,69,60,51,15,58,0.87,67
2,3,Brazil,Research Scientist,Analytics,Entry,0,41660,5268,PhD,Healthcare,Large,3,2020,Remote,46.8,4.78,10,76.395263,0.415,69,5.04,87.47,8,62.95,12.2,13,12,49,70,59,68,37,13,2.13,61
3,4,India,Software Engineer AI,Computer Vision,Senior,6,43268,7975,Diploma,Tech,Large,2,2026,Onsite,52.2,4.34,23,59.340199,0.115,74,4.38,86.84,7,77.45,35.1,30,80,47,79,65,55,46,74,1.49,56
4,5,Germany,Machine Learning Engineer,Computer Vision,Entry,0,69119,4758,Master,Retail,Medium,2,2021,Hybrid,46.7,4.49,17,72.301128,0.311,68,6.67,79.84,7,89.86,36.1,24,82,47,64,52,69,17,21,0.87,72

### Section 5: Remove duplicate rows

In [5]:
before_rows = len(df_clean)

df_clean = (
    df_clean
    .drop_duplicates()
)

after_rows = len(df_clean)

print(
    f"\nRemoved {before_rows - after_rows} duplicate rows"
)

Removed 0 duplicate rows

### Section 6: Remove Leading and Trailing Spaces

In [6]:
for col in categorical_columns:

    df_clean[col] = (
        df_clean[col]
        .astype(str)
        .str.strip()
    )

print("\nRemoved Leading and Trailing Spaces Successfully")

Removed Leading and Trailing Spaces Successfully

### Section 7: Text Standardization

In [17]:
print("-" * 20)
print("Text Standardization")
print("-" * 20)

categorical_columns = (
    df_clean.select_dtypes(
        include="object"
    ).columns
)

# Country mapping
df_clean["country"] = (
    df_clean["country"]
    .astype(str)
    .str.strip()
    .str.title()
)

country_mapping = {
    "Uae" : "UAE",
    "Usa" : "USA",
    "Uk" : "UK"
    }

df_clean["country"] = (
    df_clean["country"]
    .replace(country_mapping)
)

# Job role mapping
df_clean["job_role"] = (
    df_clean["job_role"]
    .astype(str)
    .str.strip()
    .str.title()
)

job_role_mapping = {
    "Ai Engineer" : "AI Engineer",
    "Software Engineer Ai" : "AI Software Engineer",
    "Nlp Engineer" : "NLP Engineer"
    }

df_clean["job_role"] = (
    df_clean["job_role"]
    .replace(job_role_mapping)
)

# AI Specialization mapping
df_clean["ai_specialization"] = (
    df_clean["ai_specialization"]
    .astype(str)
    .str.strip()
    .str.title()
)

ai_specialization_mapping = {
    "Llm" : "LLM",
    "Nlp" : "NLP",
    "Mlops" : "MLOps",
    "Generative Ai" : "Generative AI"
    }

df_clean["ai_specialization"] = (
    df_clean["ai_specialization"]
    .replace(ai_specialization_mapping)
)


# Round Score
df_clean["hiring_difficulty_score"] = (
    df_clean["hiring_difficulty_score"]
    .round(2)
)

# Standardize Remaining Text Columns
for col in categorical_columns:

    if col == "country" or col == "job_role" or col == "ai_specialization":
        continue

    df_clean[col] = (
        df_clean[col]
        .astype(str)
        .str.strip()
        .str.title()
    )

print("Text Standardization Completed")

# Check modifications

job = df["job_role"].unique().tolist()
ai_spec = df["ai_specialization"].unique().tolist()
country = df["country"].unique().tolist()

print(job)
print(ai_spec)
print(country)

--------------------
Text Standardization
--------------------
Text Standardization Completed
['Machine Learning Engineer', 'AI Engineer', 'Research Scientist', 'Software Engineer AI', 'Data Analyst', 'Computer Vision Engineer', 'NLP Engineer', 'Data Scientist']
['Reinforcement Learning', 'LLM', 'Analytics', 'Computer Vision', 'NLP', 'MLOps', 'Forecasting', 'Generative AI']
['UAE', 'USA', 'Brazil', 'India', 'Germany', 'Japan', 'Australia', 'France', 'Singapore', 'Netherlands', 'Canada', 'UK']

### Section 8: Replace Empty Strings

In [8]:
for col in categorical_columns:

    df_clean[col] = (
        df_clean[col]
        .replace(
            "",
            np.nan
        )
    )

print("\nReplaced Empty Strings Successfully")

Replaced Empty Strings Successfully

### Section 9: Replace index

In [9]:
# Reset the index

df_clean = (
    df_clean
    .reset_index(
        drop=True
    )
)

### Section 10: Export Clean Dataset

In [10]:
import time

print("-" * 25)
print("Clean Dataset Export")
print("-" * 25)

steps = [
    "Preparing dataset...",
    "Validating records...",
    "Writing CSV file...",
    "Finalizing export..."
]

for step in steps:
    print(step)
    time.sleep(0.5)

df_clean.to_csv(
    "../data/processed/cleaned_ai_jobs.csv",
    index=False
)

print()
print("Export Completed Successfully")
print("-" * 50)

print(
    "Saved To: ../data/processed/cleaned_ai_jobs.csv"
)

print(
    f"Final Shape : {df_clean.shape}"
)

-------------------------
Clean Dataset Export
-------------------------
Preparing dataset...
Validating records...
Writing CSV file...
Finalizing export...

Export Completed Successfully
--------------------------------------------------
Saved To: ../data/processed/cleaned_ai_jobs.csv
Final Shape : (90000, 35)