# 01 Salary Intelligence

## Module 1: Salary Intelligence
### Level 1: Descriptive Analytics

### Objective

Establish a baseline understanding of the global AI jobs dataset by analyzing basic distributions, identifying central tendencies for raw salaries and bonuses, and exploring linear relationships among continuous numerical variables.

The objective of this level is to understand the overall salary landscape of the global AI job market.

This section establishes the analytical foundation by exploring:

- Salary distribution across key business dimensions
- Major salary drivers
- Bonus compensation trends
- Relationships between salary and workforce attributes

The insights generated here will be used throughout the remaining levels of the Salary Intelligence module.

### 1.1 Environment Setup
Configure the notebook execution environment and suppress non-critical runtime warnings.

In [441]:
import warnings
import platform
import numpy as np
import pandas as pd

# Configure execution environment and suppress warnings
warnings.filterwarnings("ignore")

# Optimize pandas display configurations for comprehensive data inspection.
pd.set_option("display.max_columns", None)
pd.set_option("display.max_rows", 100)
pd.set_option("display.width", None)

# Log framework metadata and verification metrics.

print("Environment Information")
print("-" * 22)
print(f"Python Version : {platform.python_version()}")
print(f"Pandas Version : {pd.__version__}")
print(f"NumPy Version  : {np.__version__}")

Environment Information
----------------------
Python Version : 3.14.6
Pandas Version : 3.0.3
NumPy Version  : 2.4.6

### 1.2 Data Ingestion
Load the core processed Global AI Jobs dataset.

In [442]:
# Load target dataset

DATA_PATH = "../../data/processed/cleaned_ai_jobs.csv"
df = pd.read_csv(DATA_PATH)
print("\nDataset Loaded Successfully")

# Execute descriptive matrix shape verification.

print("\nDataset Shape")
print("-" * 16)

total_rows, total_columns = df.shape

print(f"Rows    : {total_rows:,}")
print(f"Columns : {total_columns}")
print("-" * 16)

# Display a quick preview of the dataset schema.

display(df.head())

Dataset Loaded Successfully

Dataset Shape
----------------
Rows    : 90,000
Columns : 35
----------------

,id,country,job_role,ai_specialization,experience_level,experience_years,salary_usd,bonus_usd,education_required,industry,company_size,interview_rounds,year,work_mode,weekly_hours,company_rating,job_openings,hiring_difficulty_score,layoff_risk,ai_adoption_score,company_funding_billion,economic_index,ai_maturity_years,offer_acceptance_rate,tax_rate_percent,vacation_days,skill_demand_score,automation_risk,job_security_score,career_growth_score,work_life_balance_score,promotion_speed,salary_percentile,cost_of_living_index,employee_satisfaction
0,1,UAE,Machine Learning Engineer,Reinforcement Learning,Entry,0,66465,5395,Master,Automotive,Small,7,2020,Remote,44.7,3.67,10,52.77,0.404,91,3.30,78.65,13,60.58,20.8,27,12,76,57,65,73,15,55,1.23,76
1,2,USA,AI Engineer,LLM,Entry,1,75507,11713,Bootcamp,Retail,Small,3,2021,Onsite,48.9,4.26,27,53.11,0.387,71,4.39,62.14,13,75.80,28.4,27,54,29,69,60,51,15,58,0.87,67
2,3,Brazil,Research Scientist,Analytics,Entry,0,41660,5268,Phd,Healthcare,Large,3,2020,Remote,46.8,4.78,10,76.40,0.415,69,5.04,87.47,8,62.95,12.2,13,12,49,70,59,68,37,13,2.13,61
3,4,India,AI Software Engineer,Computer Vision,Senior,6,43268,7975,Diploma,Tech,Large,2,2026,Onsite,52.2,4.34,23,59.34,0.115,74,4.38,86.84,7,77.45,35.1,30,80,47,79,65,55,46,74,1.49,56
4,5,Germany,Machine Learning Engineer,Computer Vision,Entry,0,69119,4758,Master,Retail,Medium,2,2021,Hybrid,46.7,4.49,17,72.30,0.311,68,6.67,79.84,7,89.86,36.1,24,82,47,64,52,69,17,21,0.87,72

### Salary Intelligence Overview

### Business Objective

Salary is one of the primary indicators of workforce value.

The following analyses examine salary across several important business dimensions to understand how compensation varies throughout the AI job market.

### Analysis 1 - Salary by Experience Level

This analysis evaluates how salary changes as professionals progress through different experience levels.

In [443]:
# Calculate descriptive salary statistics across experience levels

salary_by_experience_level = (
    df.groupby("experience_level")
      .agg(
          job_posting_count=("salary_usd", "count"),
          average_salary=("salary_usd", "mean"),
          median_salary=("salary_usd", "median"),
          minimum_salary=("salary_usd", "min"),
          maximum_salary=("salary_usd", "max"),
          salary_standard_deviation=("salary_usd", "std")
      )
      .round(2)
      .sort_values(by="average_salary", ascending=False)
)

salary_by_experience_level

,job_posting_count,average_salary,median_salary,minimum_salary,maximum_salary,salary_standard_deviation
experience_level,,,,,,
Lead,22556,142318.95,146926.5,31735,300622,44646.44
Senior,22680,104608.04,107619.0,28000,220989,32564.19
Mid,22459,77411.91,79970.0,28000,160043,23861.33
Entry,22305,61327.59,63542.0,28000,119807,18105.46

### Analysis 2 - Salary by Country

This analysis compares average salary across countries to identify the highest and lowest paying AI job markets.

In [444]:
# Calculate descriptive salary statistics by country

salary_by_country = (
    df.groupby("country")
      .agg(
          job_posting_count=("salary_usd", "count"),
          average_salary=("salary_usd", "mean"),
          median_salary=("salary_usd", "median"),
          minimum_salary=("salary_usd", "min"),
          maximum_salary=("salary_usd", "max"),
          salary_standard_deviation=("salary_usd", "std")
      )
      .round(2)
      .sort_values(by="average_salary", ascending=False)
)

salary_by_country

,job_posting_count,average_salary,median_salary,minimum_salary,maximum_salary,salary_standard_deviation
country,,,,,,
USA,7405,132995.21,121887.0,47057,300622,49793.07
Singapore,7583,116954.73,107137.0,41399,263559,43115.37
Australia,7589,110549.81,101083.0,39026,246866,41155.81
Canada,7602,108671.05,99709.5,38547,247266,40260.85
UK,7532,102826.24,93746.0,36685,232850,37907.95
Netherlands,7514,102379.05,93740.5,36263,232080,38322.35
Germany,7461,100007.78,91867.0,35436,226492,36877.81
Japan,7350,98507.66,90088.0,35079,215632,36721.88
France,7440,95170.46,88105.5,34527,215958,35279.41
UAE,7529,93507.70,86097.0,33010,210545,34266.57
Brazil,7545,53704.84,49270.0,28000,120334,19750.04
India,7450,43106.30,38511.5,28000,95348,14976.33

### Analysis 3 - Salary by AI Specialization

Different AI domains often command different compensation levels.

This analysis compares salary across AI specializations.

In [445]:
# Calculate descriptive salary statistics by AI specialization

salary_by_specialization = (
    df.groupby("ai_specialization")
      .agg(
          job_posting_count=("salary_usd", "count"),
          average_salary=("salary_usd", "mean"),
          median_salary=("salary_usd", "median"),
          minimum_salary=("salary_usd", "min"),
          maximum_salary=("salary_usd", "max"),
          salary_standard_deviation=("salary_usd", "std")
      )
      .round(2)
      .sort_values(by="average_salary", ascending=False)
)

salary_by_specialization

,job_posting_count,average_salary,median_salary,minimum_salary,maximum_salary,salary_standard_deviation
ai_specialization,,,,,,
Generative AI,11208,97096.78,87253.0,28000,286008,44498.96
LLM,11466,97076.65,88086.0,28000,289776,44131.09
Analytics,11258,96905.55,87892.0,28000,288941,44111.58
MLOps,11133,96742.07,87644.0,28000,297267,44034.49
Computer Vision,11487,96655.16,88080.0,28000,299543,43803.63
NLP,11072,96443.81,87936.5,28000,300622,43560.48
Forecasting,11115,96010.56,87063.0,28000,284840,43603.29
Reinforcement Learning,11261,95423.81,86191.0,28000,288779,43711.79

### Analysis 4 - Salary by Industry

Industries invest differently in AI talent.

This analysis evaluates salary variation across industries.

In [446]:
# Calculate descriptive salary statistics by industry

salary_by_industry = (
    df.groupby("industry")
      .agg(
          job_posting_count=("salary_usd", "count"),
          average_salary=("salary_usd", "mean"),
          median_salary=("salary_usd", "median"),
          minimum_salary=("salary_usd", "min"),
          maximum_salary=("salary_usd", "max"),
          salary_standard_deviation=("salary_usd", "std")
      )
      .round(2)
      .sort_values(by="average_salary", ascending=False)
)

salary_by_industry

,job_posting_count,average_salary,median_salary,minimum_salary,maximum_salary,salary_standard_deviation
industry,,,,,,
Retail,8987,97266.10,88285.0,28000,283182,44087.76
Gaming,9190,97265.59,88390.5,28000,286008,44088.64
Automotive,8930,96841.79,87736.0,28000,300622,44245.74
Tech,8984,96606.28,87234.0,28000,289000,43775.62
Education,9067,96587.20,87428.0,28000,297267,43982.84
Consulting,8954,96545.42,87512.0,28000,283321,43989.42
Healthcare,8875,96289.60,87739.0,28000,299543,43873.83
Finance,9057,96223.29,87121.0,28000,275933,43900.68
Telecom,8939,95959.90,86918.0,28000,288779,43770.27
Energy,9017,95861.07,86714.0,28000,279406,43632.31

### Analysis 5 - Salary by Hiring Difficulty

Hiring difficulty often reflects market demand for specialized talent.

This analysis examines salary across hiring difficulty scores.

In [447]:
# Calculate descriptive salary statistics by hiring difficulty score

salary_by_hiring_difficulty = (
    df.groupby("hiring_difficulty_score")
      .agg(
          job_posting_count=("salary_usd", "count"),
          average_salary=("salary_usd", "mean"),
          median_salary=("salary_usd", "median"),
          minimum_salary=("salary_usd", "min"),
          maximum_salary=("salary_usd", "max"),
          salary_standard_deviation=("salary_usd", "std")
      )
      .round(2)
      .sort_values(by="average_salary", ascending=False)
      .head(10)
)

salary_by_hiring_difficulty

,job_posting_count,average_salary,median_salary,minimum_salary,maximum_salary,salary_standard_deviation
hiring_difficulty_score,,,,,,
15.26,1,252741.0,252741.0,252741,252741,NaN
9.53,1,251684.0,251684.0,251684,251684,NaN
16.08,1,238350.0,238350.0,238350,238350,NaN
1.99,1,232601.0,232601.0,232601,232601,NaN
93.71,1,231676.0,231676.0,231676,231676,NaN
15.03,1,230908.0,230908.0,230908,230908,NaN
7.94,1,225560.0,225560.0,225560,225560,NaN
89.13,2,223435.0,223435.0,181555,265315,59227.26
17.00,1,219917.0,219917.0,219917,219917,NaN
14.18,1,219208.0,219208.0,219208,219208,NaN

### Analysis 6 - Salary by Education

Education remains an important factor in compensation.

This analysis compares salary across educational qualifications.

In [448]:
# Calculate descriptive salary statistics by education level

salary_by_education = (
    df.groupby("education_required")
      .agg(
          job_posting_count=("salary_usd", "count"),
          average_salary=("salary_usd", "mean"),
          median_salary=("salary_usd", "median"),
          minimum_salary=("salary_usd", "min"),
          maximum_salary=("salary_usd", "max"),
          salary_standard_deviation=("salary_usd", "std")
      )
      .round(2)
      .sort_values(by="average_salary", ascending=False)
)

salary_by_education

,job_posting_count,average_salary,median_salary,minimum_salary,maximum_salary,salary_standard_deviation
education_required,,,,,,
Bootcamp,18148,97206.04,88233.0,28000,297267,44188.73
Bachelor,18005,97026.41,87710.0,28000,288941,44164.25
Diploma,17914,96283.37,87356.5,28000,289000,43844.91
Phd,18070,96131.33,87465.0,28000,300622,43525.85
Master,17863,96075.31,86946.0,28000,284840,43941.39

### Analysis 7 - Salary by Job Role

Job responsibilities have a significant influence on compensation.

This analysis compares salary across AI job roles.

In [449]:
# Calculate descriptive salary statistics by job role

salary_by_job_role = (
    df.groupby("job_role")
      .agg(
          job_posting_count=("salary_usd", "count"),
          average_salary=("salary_usd", "mean"),
          median_salary=("salary_usd", "median"),
          minimum_salary=("salary_usd", "min"),
          maximum_salary=("salary_usd", "max"),
          salary_standard_deviation=("salary_usd", "std")
      )
      .round(2)
      .sort_values(by="average_salary", ascending=False)
)

salary_by_job_role

,job_posting_count,average_salary,median_salary,minimum_salary,maximum_salary,salary_standard_deviation
job_role,,,,,,
Research Scientist,11309,109797.50,99659.0,28000,300622,48013.57
Machine Learning Engineer,11263,102121.80,93257.0,28000,277408,44699.42
Computer Vision Engineer,11227,101303.94,91730.0,28000,276175,44656.17
NLP Engineer,11412,99745.32,90826.0,28000,272950,43797.47
AI Engineer,11247,97974.71,88501.0,28000,268390,42883.10
AI Software Engineer,11333,97375.53,88723.0,28000,263226,42572.31
Data Scientist,11146,94029.90,85501.5,28000,255231,41243.03
Data Analyst,11063,69429.27,62657.0,28000,187484,29706.67

## Bonus Intelligence

### Business Objective

In addition to salary, bonuses contribute significantly to overall employee compensation.

The following analyses evaluate bonus distribution across different workforce dimensions.

In [450]:
# Generate descriptive statistics for bonus distribution

df["bonus_usd"].describe().round()

count    90000.0
mean     13028.0
std       7887.0
min       1404.0
25%       7105.0
50%      11279.0
75%      16997.0
max      57681.0
Name: bonus_usd, dtype: float64

In [451]:
# Calculate descriptive bonus statistics by experience level

bonus_by_experience_level = (
    df.groupby("experience_level")
      .agg(
          job_posting_count=("bonus_usd", "count"),
          average_bonus=("bonus_usd", "mean"),
          median_bonus=("bonus_usd", "median"),
          minimum_bonus=("bonus_usd", "min"),
          maximum_bonus=("bonus_usd", "max"),
          bonus_standard_deviation=("bonus_usd", "std")
      )
      .round(2)
      .sort_values(by="average_bonus", ascending=False)
)

bonus_by_experience_level

,job_posting_count,average_bonus,median_bonus,minimum_bonus,maximum_bonus,bonus_standard_deviation
experience_level,,,,,,
Lead,22556,19254.55,17803.5,1810,57681,9486.26
Senior,22680,14069.43,13096.0,1437,46812,6876.56
Mid,22459,10439.59,9688.0,1404,34065,5134.88
Entry,22305,8280.42,7679.0,1409,23994,3969.32

In [452]:
# Compare salary distribution across countries

salary_by_country_summary = (
    df.groupby("country")
      .agg(
          job_posting_count=("salary_usd", "count"),
          minimum_salary=("salary_usd", "min"),
          maximum_salary=("salary_usd", "max"),
          average_salary=("salary_usd", "mean"),
          median_salary=("salary_usd", "median"),
          salary_standard_deviation=("salary_usd", "std")
      )
      .round(2)
      .sort_values(by="maximum_salary", ascending=False)
)

salary_by_country_summary

,job_posting_count,minimum_salary,maximum_salary,average_salary,median_salary,salary_standard_deviation
country,,,,,,
USA,7405,47057,300622,132995.21,121887.0,49793.07
Singapore,7583,41399,263559,116954.73,107137.0,43115.37
Canada,7602,38547,247266,108671.05,99709.5,40260.85
Australia,7589,39026,246866,110549.81,101083.0,41155.81
UK,7532,36685,232850,102826.24,93746.0,37907.95
Netherlands,7514,36263,232080,102379.05,93740.5,38322.35
Germany,7461,35436,226492,100007.78,91867.0,36877.81
France,7440,34527,215958,95170.46,88105.5,35279.41
Japan,7350,35079,215632,98507.66,90088.0,36721.88
UAE,7529,33010,210545,93507.70,86097.0,34266.57
Brazil,7545,28000,120334,53704.84,49270.0,19750.04
India,7450,28000,95348,43106.30,38511.5,14976.33

In [453]:
# Compare salary distribution across job roles

salary_by_job_role_summary = (
    df.groupby("job_role")
      .agg(
          job_posting_count=("salary_usd", "count"),
          minimum_salary=("salary_usd", "min"),
          maximum_salary=("salary_usd", "max"),
          average_salary=("salary_usd", "mean"),
          median_salary=("salary_usd", "median"),
          salary_standard_deviation=("salary_usd", "std")
      )
      .round(2)
      .sort_values(by="maximum_salary", ascending=False)
)

salary_by_job_role_summary

,job_posting_count,minimum_salary,maximum_salary,average_salary,median_salary,salary_standard_deviation
job_role,,,,,,
Research Scientist,11309,28000,300622,109797.50,99659.0,48013.57
Machine Learning Engineer,11263,28000,277408,102121.80,93257.0,44699.42
Computer Vision Engineer,11227,28000,276175,101303.94,91730.0,44656.17
NLP Engineer,11412,28000,272950,99745.32,90826.0,43797.47
AI Engineer,11247,28000,268390,97974.71,88501.0,42883.10
AI Software Engineer,11333,28000,263226,97375.53,88723.0,42572.31
Data Scientist,11146,28000,255231,94029.90,85501.5,41243.03
Data Analyst,11063,28000,187484,69429.27,62657.0,29706.67

In [454]:
# Compare salary distribution across AI specializations

salary_by_specialization_summary = (
    df.groupby("ai_specialization")
      .agg(
          job_posting_count=("salary_usd", "count"),
          minimum_salary=("salary_usd", "min"),
          maximum_salary=("salary_usd", "max"),
          average_salary=("salary_usd", "mean"),
          median_salary=("salary_usd", "median"),
          salary_standard_deviation=("salary_usd", "std")
      )
      .round(2)
      .sort_values(by="maximum_salary", ascending=False)
)

salary_by_specialization_summary

,job_posting_count,minimum_salary,maximum_salary,average_salary,median_salary,salary_standard_deviation
ai_specialization,,,,,,
NLP,11072,28000,300622,96443.81,87936.5,43560.48
Computer Vision,11487,28000,299543,96655.16,88080.0,43803.63
MLOps,11133,28000,297267,96742.07,87644.0,44034.49
LLM,11466,28000,289776,97076.65,88086.0,44131.09
Analytics,11258,28000,288941,96905.55,87892.0,44111.58
Reinforcement Learning,11261,28000,288779,95423.81,86191.0,43711.79
Generative AI,11208,28000,286008,97096.78,87253.0,44498.96
Forecasting,11115,28000,284840,96010.56,87063.0,43603.29

## Correlation Analysis

### Business Objective

Understanding relationships between salary and workforce characteristics helps identify the strongest factors associated with employee compensation.

Correlation values range from **-1** to **1**, indicating the strength and direction of linear relationships.

In [455]:
# Evaluate correlations between salary and key workforce metrics

salary_correlation_features = [
    "salary_usd",
    "experience_years",
    "hiring_difficulty_score",
    "skill_demand_score",
    "career_growth_score",
    "job_security_score",
    "promotion_speed"
]

salary_correlation_matrix = (
    df[salary_correlation_features]
    .corr()
    .round(2)
)

salary_correlation_matrix

,salary_usd,experience_years,hiring_difficulty_score,skill_demand_score,career_growth_score,job_security_score,promotion_speed
salary_usd,1.00,0.72,-0.00,0.00,0.00,0.43,0.26
experience_years,0.72,1.00,0.00,0.00,0.01,0.60,0.36
hiring_difficulty_score,-0.00,0.00,1.00,0.00,-0.00,0.00,0.01
skill_demand_score,0.00,0.00,0.00,1.00,0.00,-0.00,-0.01
career_growth_score,0.00,0.01,-0.00,0.00,1.00,0.06,0.01
job_security_score,0.43,0.60,0.00,-0.00,0.06,1.00,0.06
promotion_speed,0.26,0.36,0.01,-0.01,0.01,0.06,1.00

## Level 1 Summary

In this level, we established the baseline salary intelligence for the global AI workforce.

Key analyses completed include:

- Salary overview across major workforce dimensions
- Bonus intelligence
- Country, industry, education, specialization, and job role comparisons
- Salary relationship with important workforce metrics

These findings provide the analytical foundation for **Level 2: Segmentation Analytics**, where compensation patterns will be explored across combinations of workforce attributes.

## Level 2 • Segmentation Analytics

### Objective

While descriptive analytics provides insights into individual workforce attributes, real-world business decisions often require analyzing the interaction between multiple dimensions simultaneously.

This level explores how salary and bonus compensation vary when experience level is combined with country, job role, industry, education, and AI specialization.

The objective is to identify workforce segments that consistently demonstrate higher compensation and uncover patterns that cannot be observed through single-variable analysis.

## Salary Segmentation

The following analyses compare average salary across combinations of workforce attributes.

Each segmentation reveals how experience level influences compensation within different business dimensions.

In [456]:
# Compare average salary across countries and experience levels

salary_by_country_and_experience = (
    pd.pivot_table(
        data=df,
        values="salary_usd",
        index="country",
        columns="experience_level",
        aggfunc="mean"
    )
    .round(2)
)

salary_by_country_and_experience

experience_level     Entry       Lead        Mid     Senior
country
Australia         69828.58  163659.49   88438.30  119652.38
Brazil            34073.38   78634.81   42519.65   58307.23
Canada            69239.30  160558.39   87764.59  118161.01
France            60507.76  140554.17   76539.67  103718.16
Germany           63217.73  146904.43   80086.09  107784.37
India             29367.15   63014.32   34656.46   45757.61
Japan             61811.99  145512.93   78742.48  105935.31
Netherlands       64959.80  151713.46   81623.91  110242.15
Singapore         74109.77  172604.69   94096.38  126494.42
UAE               59033.18  136858.10   75119.71  100619.86
UK                65835.30  152454.07   82945.90  112082.51
USA               83936.84  197397.86  106142.66  144487.64

In [457]:
# Compare average salary across AI specializations and experience levels

salary_by_specialization_and_experience = (
    pd.pivot_table(
        data=df,
        values="salary_usd",
        index="ai_specialization",
        columns="experience_level",
        aggfunc="mean"
    )
    .round(2)
)

salary_by_specialization_and_experience

experience_level           Entry       Lead       Mid     Senior
ai_specialization
Analytics               61859.60  142775.48  78520.61  104794.04
Computer Vision         61530.52  141837.93  77024.52  104026.18
Forecasting             61330.94  141785.68  77003.74  104645.09
Generative AI           61486.32  144657.03  76512.82  104209.52
LLM                     61094.07  141876.88  77145.39  106350.34
MLOps                   61145.08  142946.22  78011.66  104425.37
NLP                     61236.47  141338.09  77839.88  104925.72
Reinforcement Learning  60946.20  141263.13  77204.37  103447.33

In [458]:
# Compare average salary across industries and experience levels

salary_by_industry_and_experience = (
    pd.pivot_table(
        data=df,
        values="salary_usd",
        index="industry",
        columns="experience_level",
        aggfunc="mean"
    )
    .round(2)
)

salary_by_industry_and_experience

experience_level     Entry       Lead       Mid     Senior
industry
Automotive        61051.24  142421.99  77523.89  104769.24
Consulting        61460.54  142472.67  77919.98  104678.10
Education         61238.68  142953.03  77709.32  103977.99
Energy            61314.24  141679.03  77194.62  104823.03
Finance           61351.98  141375.37  76508.16  105870.87
Gaming            62563.43  144869.80  77857.74  104502.44
Healthcare        60598.46  142724.59  77601.30  104453.05
Retail            61175.78  143159.13  77614.18  104649.17
Tech              61304.61  139977.06  76678.37  104220.31
Telecom           61160.98  141588.87  77505.36  104151.10

In [459]:
# Compare average salary across education levels and experience levels

salary_by_education_and_experience = (
    pd.pivot_table(
        data=df,
        values="salary_usd",
        index="education_required",
        columns="experience_level",
        aggfunc="mean"
    )
    .round(3)
)

salary_by_education_and_experience

experience_level        Entry        Lead        Mid      Senior
education_required
Bachelor            61428.389  143653.947  77742.492  104644.068
Bootcamp            61949.238  142783.174  77736.594  104336.024
Diploma             60796.250  142241.018  77506.846  104182.945
Master              61080.512  142043.153  77034.505  105183.290
Phd                 61372.048  140856.080  77050.538  104702.378

## Workforce Compensation Matrix

Single-level segmentation provides valuable insights, but workforce compensation is often influenced by multiple factors simultaneously.

The following analysis combines job role, AI specialization, and experience level into a single analytical view to better understand compensation patterns across complex workforce segments.

In [460]:
# Analyze average salary and bonus across job role, AI specialization, and experience level

compensation_segmentation_matrix = (
    pd.pivot_table(
        data=df,
        values=["salary_usd", "bonus_usd"],
        index=["job_role", "ai_specialization"],
        columns="experience_level",
        aggfunc="mean",
        fill_value=0,
        margins=True,
        margins_name="Grand Total"
    )
    .round()
)

display(compensation_segmentation_matrix)

                                                 bonus_usd                    \
experience_level                                     Entry     Lead      Mid
job_role                  ai_specialization
AI Engineer               Analytics                 8519.0  19318.0  10646.0
                          Computer Vision           8438.0  19235.0  10656.0
                          Forecasting               8386.0  19778.0  10968.0
                          Generative AI             8666.0  19651.0  10559.0
                          LLM                       8153.0  18900.0  10710.0
                          MLOps                     8619.0  19098.0  10844.0
                          NLP                       8367.0  18981.0  10433.0
                          Reinforcement Learning    8598.0  20300.0  10611.0
AI Software Engineer      Analytics                 8782.0  19371.0  10710.0
                          Computer Vision           8380.0  19508.0  10777.0
                          Forecasting               8081.0  19045.0  10638.0
                          Generative AI             8220.0  19755.0   9882.0
                          LLM                       8160.0  19486.0  10439.0
                          MLOps                     8522.0  19634.0  10450.0
                          NLP                       8436.0  18488.0  10628.0
                          Reinforcement Learning    8366.0  19965.0  10044.0
Computer Vision Engineer  Analytics                 8832.0  20575.0  11167.0
                          Computer Vision           8507.0  20593.0  10913.0
                          Forecasting               8797.0  19425.0  10478.0
                          Generative AI             8151.0  20501.0  11001.0
                          LLM                       8797.0  19955.0  11244.0
                          MLOps                     8964.0  20711.0  10317.0
                          NLP                       8996.0  20199.0  10936.0
                          Reinforcement Learning    8559.0  20384.0  10903.0
Data Analyst              Analytics                 6024.0  13490.0   7847.0
                          Computer Vision           6154.0  14191.0   7244.0
                          Forecasting               6097.0  13266.0   7858.0
                          Generative AI             5988.0  14771.0   7369.0
                          LLM                       6108.0  13995.0   7256.0
                          MLOps                     6012.0  13274.0   7563.0
                          NLP                       6128.0  13889.0   7278.0
                          Reinforcement Learning    6168.0  13793.0   7816.0
Data Scientist            Analytics                 8129.0  18931.0  10309.0
                          Computer Vision           7886.0  19156.0   9927.0
                          Forecasting               7948.0  18261.0  10169.0
                          Generative AI             8105.0  18745.0   9763.0
                          LLM                       7838.0  18630.0  10348.0
                          MLOps                     7963.0  19311.0  10273.0
                          NLP                       8460.0  18052.0  10409.0
                          Reinforcement Learning    7732.0  18723.0   9968.0
Machine Learning Engineer Analytics                 8992.0  20901.0  11565.0
                          Computer Vision           8693.0  20000.0  10826.0
                          Forecasting               8618.0  19744.0  11294.0
                          Generative AI             8709.0  21091.0  11285.0
                          LLM                       8762.0  19671.0  11074.0
                          MLOps                     8353.0  19913.0  10852.0
                          NLP                       8779.0  19266.0  11207.0
                          Reinforcement Learning    8785.0  20594.0  11156.0
NLP Engineer              Analytics                 8689.0  19965.0  10938.0
                          Computer Vision           8557.0  19325.0  10709.0
                          Forecasting               8370.0  19739.0  10399.0
                          Generative AI             8502.0  19828.0  10797.0
                          LLM                       7860.0  20841.0  10703.0
                          MLOps                     8436.0  21523.0  11323.0
                          NLP                       8427.0  20388.0  10624.0
                          Reinforcement Learning    8440.0  19924.0  10597.0
Research Scientist        Analytics                 9309.0  22133.0  11892.0
                          Computer Vision           9580.0  21775.0  12103.0
                          Forecasting               9423.0  21841.0  11679.0
                          Generative AI             9622.0  21426.0  11518.0
                          LLM                       9374.0  21396.0  12057.0
                          MLOps                     9403.0  21608.0  12147.0
                          NLP                       9596.0  22416.0  12239.0
                          Reinforcement Learning    9165.0  21254.0  11788.0
Grand Total                                         8280.0  19255.0  10440.0

                                                                       \
experience_level                                   Senior Grand Total
job_role                  ai_specialization
AI Engineer               Analytics               14154.0     13229.0
                          Computer Vision         14212.0     13175.0
                          Forecasting             13981.0     13177.0
                          Generative AI           14016.0     13323.0
                          LLM                     14243.0     13219.0
                          MLOps                   14643.0     13256.0
                          NLP                     13940.0     13097.0
                          Reinforcement Learning  13683.0     13216.0
AI Software Engineer      Analytics               14308.0     13431.0
                          Computer Vision         14205.0     13237.0
                          Forecasting             14054.0     13106.0
                          Generative AI           14194.0     13141.0
                          LLM                     14591.0     13460.0
                          MLOps                   13982.0     13046.0
                          NLP                     14075.0     12931.0
                          Reinforcement Learning  14323.0     13218.0
Computer Vision Engineer  Analytics               15323.0     13858.0
                          Computer Vision         13753.0     13525.0
                          Forecasting             14478.0     13206.0
                          Generative AI           14335.0     13549.0
                          LLM                     15226.0     13954.0
                          MLOps                   14466.0     13665.0
                          NLP                     15529.0     13818.0
                          Reinforcement Learning  14902.0     13600.0
Data Analyst              Analytics                9754.0      9315.0
                          Computer Vision         10561.0      9723.0
                          Forecasting             10224.0      9230.0
                          Generative AI           10768.0      9519.0
                          LLM                     10113.0      9137.0
                          MLOps                   10428.0      9323.0
                          NLP                     10313.0      9362.0
                          Reinforcement Learning  10065.0      9537.0
Data Scientist            Analytics               13659.0     12703.0
                          Computer Vision         13389.0     12635.0
                          Forecasting             13384.0     12426.0
                          Generative AI           13674.0     12639.0
                          LLM                     13548.0     12664.0
                          MLOps                   13979.0     12906.0
                          NLP                     14083.0     12783.0
                          Reinforcement Learning  13710.0     12538.0
Machine Learning Engineer Analytics               14919.0     13991.0
                          Computer Vision         14995.0     13861.0
                          Forecasting             15468.0     13803.0
                          Generative AI           14565.0     13900.0
                          LLM                     14968.0     13443.0
                          MLOps                   14914.0     13817.0
                          NLP                     15435.0     13470.0
                          Reinforcement Learning  14769.0     13744.0
NLP Engineer              Analytics               14250.0     13345.0
                          Computer Vision         14864.0     13238.0
                          Forecasting             14602.0     13405.0
                          Generative AI           14495.0     13580.0
                          LLM                     14468.0     13669.0
                          MLOps                   14383.0     13908.0
                          NLP                     14574.0     13720.0
                          Reinforcement Learning  14362.0     13232.0
Research Scientist        Analytics               15918.0     14843.0
                          Computer Vision         15648.0     14868.0
                          Forecasting             16007.0     14642.0
                          Generative AI           16150.0     14847.0
                          LLM                     15726.0     14731.0
                          MLOps                   16039.0     14671.0
                          NLP                     15847.0     15087.0
                          Reinforcement Learning  16186.0     14466.0
Grand Total                                       14069.0     13028.0

                                                 salary_usd            \
experience_level                                      Entry      Lead
job_role                  ai_specialization
AI Engineer               Analytics                 61966.0  144514.0
                          Computer Vision           62650.0  142517.0
                          Forecasting               62229.0  143088.0
                          Generative AI             63357.0  146859.0
                          LLM                       62122.0  144380.0
                          MLOps                     62018.0  141429.0
                          NLP                       61798.0  140960.0
                          Reinforcement Learning    62542.0  144307.0
AI Software Engineer      Analytics                 62422.0  141854.0
                          Computer Vision           61385.0  144206.0
                          Forecasting               61246.0  144444.0
                          Generative AI             60793.0  142974.0
                          LLM                       61856.0  142595.0
                          MLOps                     62007.0  143868.0
                          NLP                       61437.0  140927.0
                          Reinforcement Learning    62312.0  145911.0
Computer Vision Engineer  Analytics                 64996.0  151084.0
                          Computer Vision           65339.0  148774.0
                          Forecasting               65464.0  145080.0
                          Generative AI             64941.0  150461.0
                          LLM                       64770.0  145269.0
                          MLOps                     65124.0  153412.0
                          NLP                       64209.0  150450.0
                          Reinforcement Learning    63219.0  153340.0
Data Analyst              Analytics                 44889.0  101976.0
                          Computer Vision           44979.0  102727.0
                          Forecasting               45413.0  103578.0
                          Generative AI             44979.0  106210.0
                          LLM                       45243.0  102436.0
                          MLOps                     44274.0  100906.0
                          NLP                       45265.0  100584.0
                          Reinforcement Learning    45073.0  101508.0
Data Scientist            Analytics                 61140.0  140833.0
                          Computer Vision           58733.0  139373.0
                          Forecasting               58775.0  136980.0
                          Generative AI             59034.0  140454.0
                          LLM                       58152.0  136552.0
                          MLOps                     59442.0  141585.0
                          NLP                       60509.0  137389.0
                          Reinforcement Learning    58940.0  138777.0
Machine Learning Engineer Analytics                 65755.0  152396.0
                          Computer Vision           63863.0  149284.0
                          Forecasting               63557.0  148053.0
                          Generative AI             64519.0  155161.0
                          LLM                       66027.0  148358.0
                          MLOps                     63406.0  149173.0
                          NLP                       65280.0  149281.0
                          Reinforcement Learning    64521.0  150198.0
NLP Engineer              Analytics                 62400.0  145512.0
                          Computer Vision           62785.0  145518.0
                          Forecasting               63105.0  146480.0
                          Generative AI             64164.0  148362.0
                          LLM                       62600.0  148189.0
                          MLOps                     63470.0  149957.0
                          NLP                       61237.0  146449.0
                          Reinforcement Learning    61496.0  145651.0
Research Scientist        Analytics                 69885.0  162876.0
                          Computer Vision           70668.0  162680.0
                          Forecasting               70046.0  160280.0
                          Generative AI             69940.0  160643.0
                          LLM                       69385.0  163487.0
                          MLOps                     68574.0  161013.0
                          NLP                       71611.0  163811.0
                          Reinforcement Learning    68754.0  156014.0
Grand Total                                         61328.0  142319.0

                                                                     \
experience_level                                      Mid    Senior
job_role                  ai_specialization
AI Engineer               Analytics               77883.0  106656.0
                          Computer Vision         78373.0  104096.0
                          Forecasting             81058.0  107732.0
                          Generative AI           79213.0  106247.0
                          LLM                     78700.0  105745.0
                          MLOps                   77765.0  108457.0
                          NLP                     79189.0  105941.0
                          Reinforcement Learning  77870.0  102748.0
AI Software Engineer      Analytics               78626.0  104655.0
                          Computer Vision         78415.0  104188.0
                          Forecasting             75782.0  106104.0
                          Generative AI           75416.0  104278.0
                          LLM                     77869.0  106252.0
                          MLOps                   79302.0  101563.0
                          NLP                     77827.0  104743.0
                          Reinforcement Learning  76140.0  104362.0
Computer Vision Engineer  Analytics               82844.0  110611.0
                          Computer Vision         82023.0  107759.0
                          Forecasting             79347.0  108277.0
                          Generative AI           80875.0  108295.0
                          LLM                     82254.0  114539.0
                          MLOps                   78165.0  109229.0
                          NLP                     80097.0  110594.0
                          Reinforcement Learning  83555.0  109136.0
Data Analyst              Analytics               56579.0   75028.0
                          Computer Vision         54330.0   75752.0
                          Forecasting             56557.0   75633.0
                          Generative AI           55589.0   75423.0
                          LLM                     56295.0   75630.0
                          MLOps                   57709.0   75628.0
                          NLP                     54911.0   75332.0
                          Reinforcement Learning  56557.0   74120.0
Data Scientist            Analytics               76650.0  102658.0
                          Computer Vision         73712.0  102026.0
                          Forecasting             74323.0  102172.0
                          Generative AI           73033.0  101779.0
                          LLM                     74471.0  101474.0
                          MLOps                   76957.0  103326.0
                          NLP                     75899.0  102002.0
                          Reinforcement Learning  74460.0  101867.0
Machine Learning Engineer Analytics               83465.0  111898.0
                          Computer Vision         82146.0  111696.0
                          Forecasting             80854.0  110501.0
                          Generative AI           82575.0  112196.0
                          LLM                     81110.0  111556.0
                          MLOps                   81211.0  109503.0
                          NLP                     81959.0  113644.0
                          Reinforcement Learning  83272.0  112140.0
NLP Engineer              Analytics               81008.0  108437.0
                          Computer Vision         79198.0  107822.0
                          Forecasting             79896.0  110493.0
                          Generative AI           80028.0  105217.0
                          LLM                     79701.0  108937.0
                          MLOps                   81982.0  106903.0
                          NLP                     79916.0  109524.0
                          Reinforcement Learning  78808.0  106928.0
Research Scientist        Analytics               89982.0  119049.0
                          Computer Vision         87179.0  118101.0
                          Forecasting             88142.0  118146.0
                          Generative AI           87725.0  118106.0
                          LLM                     89870.0  122596.0
                          MLOps                   88984.0  118706.0
                          NLP                     90017.0  118083.0
                          Reinforcement Learning  89398.0  116208.0
Grand Total                                       77412.0  104608.0


experience_level                                 Grand Total
job_role                  ai_specialization
AI Engineer               Analytics                  98323.0
                          Computer Vision            97200.0
                          Forecasting                97729.0
                          Generative AI              99651.0
                          LLM                        99370.0
                          MLOps                      97087.0
                          NLP                        98233.0
                          Reinforcement Learning     96219.0
AI Software Engineer      Analytics                  97911.0

## Bonus Segmentation

Bonus compensation represents an important component of employee rewards.

The following analyses evaluate bonus distribution across different workforce segments to identify where incentive compensation is concentrated.

In [461]:
# Compare average bonus across job role, country, and experience level

bonus_by_role_country_and_experience = (
    pd.pivot_table(
        data=df,
        values="bonus_usd",
        index=["job_role", "country"],
        columns="experience_level",
        aggfunc="mean"
    )
    .round(2)
)

bonus_by_role_country_and_experience

experience_level                          Entry      Lead       Mid    Senior
job_role                  country
AI Engineer               Australia     9742.32  22212.21  11784.10  16218.97
                          Brazil        4757.24  10622.74   5697.87   7779.13
                          Canada        9419.38  22535.15  12760.40  16021.37
                          France        8407.49  19019.77   9983.01  14068.03
                          Germany       8441.20  19767.35  11277.41  14511.75
                          India         4087.63   8881.06   4789.28   6199.48
                          Japan         8192.58  20776.09  11000.66  14637.03
                          Netherlands   9095.12  21096.12  10784.77  14913.55
                          Singapore    10330.82  23123.25  12968.68  16710.78
                          UAE           8181.38  18687.61  10768.13  13055.83
                          UK            9288.14  21316.08  11440.11  15119.57
                          USA          11441.55  26935.87  14963.78  19701.97
AI Software Engineer      Australia     9540.78  22701.20  11703.75  15649.80
                          Brazil        4442.74  10883.11   5847.04   8021.18
                          Canada        9579.61  22251.88  12103.20  16484.15
                          France        8089.22  18067.80  10360.11  13948.49
                          Germany       8148.61  20114.12  10448.04  14850.88
                          India         4061.62   8540.02   4540.91   6234.84
                          Japan         8342.68  19079.21  10683.55  14663.71
                          Netherlands   9136.84  21035.37  11149.68  14868.95
                          Singapore     9899.02  23899.44  12291.14  17328.26
                          UAE           8049.95  18268.54  10210.60  14293.92
                          UK            9172.35  20333.74  11646.91  15578.70
                          USA          11049.44  26482.75  14116.97  19026.10
Computer Vision Engineer  Australia    10205.11  23197.04  12223.75  17653.20
                          Brazil        4565.15  11168.21   5907.18   8060.21
                          Canada        9587.40  22734.30  12307.64  15689.23
                          France        8387.06  19948.28  10950.66  14774.73
                          Germany       8540.49  20444.17  11428.25  15000.88
                          India         3939.49   8879.59   4710.21   6608.36
                          Japan         9189.02  21488.09  11734.70  15196.61
                          Netherlands   9322.72  21428.50  11073.29  15437.14
                          Singapore    10479.42  25870.95  13132.68  17370.78
                          UAE           8320.84  19278.64  10956.45  14394.56
                          UK            9380.36  21908.93  11901.51  16382.52
                          USA          11908.98  27519.41  14688.70  20273.90
Data Analyst              Australia     7052.19  15682.91   8688.28  11608.65
                          Brazil        3815.86   7692.56   4289.95   5878.51
                          Canada        6536.66  15983.80   8382.41  12088.54
                          France        6076.51  13622.68   7622.49  10095.45
                          Germany       6025.32  13858.74   7439.41  10656.80
                          India         3887.24   5895.87   3811.37   4505.64
                          Japan         5890.10  13900.85   7693.75  10470.18
                          Netherlands   6241.47  14416.77   7627.66  10924.17
                          Singapore     7425.56  16504.41   9279.04  12733.99
                          UAE           5807.83  13280.85   7316.08   9181.94
                          UK            6376.68  15869.71   7715.44  10760.18
                          USA           7843.45  18948.39  10721.86  14284.70
Data Scientist            Australia     8987.16  21361.93  11707.12  14740.62
                          Brazil        4425.22  10229.90   6019.30   8014.62
                          Canada        8796.80  20707.46  11409.73  15380.03
                          France        7832.46  19176.69   9873.72  13595.48
                          Germany       8387.11  19843.08  10536.44  14396.32
                          India         3842.54   8168.57   4369.44   5903.88
                          Japan         8237.44  19383.30  10488.30  13640.67
                          Netherlands   8418.04  19891.98  10731.17  14551.42
                          Singapore     9823.73  22339.08  12216.11  17186.54
                          UAE           7778.63  17713.26   9438.58  13391.33
                          UK            8697.06  20307.18  10865.79  14637.84
                          USA          11470.48  25060.81  14054.73  18486.54
Machine Learning Engineer Australia     9777.56  22106.05  12623.31  16936.98
                          Brazil        4811.93  10805.42   6113.90   8500.77
                          Canada       10171.65  22458.88  13015.19  17096.71
                          France        8862.20  19851.73  10971.47  14641.61
                          Germany       9233.82  21608.74  12017.51  15862.89
                          India         4067.69   9161.75   4803.37   6598.37
                          Japan         8511.86  21599.83  11615.33  15052.47
                          Netherlands   9309.84  21324.30  11948.92  15458.55
                          Singapore    10394.67  24690.70  13817.18  17702.69
                          UAE           8406.16  19658.18  10617.61  14694.65
                          UK            8903.27  22021.32  11491.22  16068.31
                          USA          12433.04  28386.84  15262.13  19705.65
NLP Engineer              Australia     9424.90  23102.27  12014.44  16907.13
                          Brazil        4691.67  11019.33   5657.05   8213.97
                          Canada        9610.59  21972.00  12428.84  16833.69
                          France        8481.21  20499.12  10553.43  13881.58
                          Germany       8574.16  20255.46  11413.11  15439.16
                          India         4083.94   9119.59   4813.89   6243.63
                          Japan         8543.82  20796.88  10777.36  14929.47
                          Netherlands   9025.67  20899.95  11548.28  15123.25
                          Singapore    10340.90  23414.92  12851.29  17532.39
                          UAE           7998.17  19402.05  10454.87  13394.44
                          UK            9045.68  22768.45  11495.38  15826.23
                          USA          11744.07  28555.55  15157.22  19598.07
Research Scientist        Australia    10927.52  24620.78  13183.69  18866.36
                          Brazil        5013.05  12298.59   6326.19   8899.30
                          Canada       10627.71  26392.74  13491.76  18154.20
                          France        9343.98  22144.60  11747.52  15998.98
                          Germany       9738.73  21744.74  12461.93  16468.65
                          India         4172.41  10149.95   5260.74   7418.24
                          Japan         9715.43  22200.90  11707.67  16295.48
                          Netherlands   9953.43  21467.95  12280.61  16786.01
                          Singapore    11488.20  26638.15  14059.23  18986.93
                          UAE           9417.62  20204.72  11872.57  14901.82
                          UK           10127.71  23690.40  12892.76  15849.75
                          USA          13075.85  31048.92  16682.73  22551.28

In [462]:
# Compare average bonus across AI specialization, country, and experience level

bonus_by_specialization_country_and_experience = (
    pd.pivot_table(
        data=df,
        values="bonus_usd",
        index=["ai_specialization", "country"],
        columns="experience_level",
        aggfunc="mean"
    )
    .round(2)
)

bonus_by_specialization_country_and_experience

experience_level                       Entry      Lead       Mid    Senior
ai_specialization      country
Analytics              Australia    10020.46  22676.25  11739.39  15575.31
                       Brazil        4504.31  10350.35   5679.05   8326.93
                       Canada        9123.68  22230.17  11894.18  15950.70
                       France        8312.56  20164.49  10556.11  13273.69
                       Germany       8691.72  20349.31  10912.40  15308.31
                       India         4074.96   8456.07   4610.20   6174.96
                       Japan         8643.33  20006.89  10404.84  14715.39
                       Netherlands   9011.12  20214.53  11689.88  14940.41
                       Singapore    10102.94  23064.14  12336.01  16080.10
                       UAE           7763.44  18277.73  10517.39  13249.43
                       UK            9265.77  21206.22  11541.55  14628.07
                       USA          11411.70  26625.06  15137.83  19060.95
Computer Vision        Australia     9528.31  20734.44  12037.20  15525.72
                       Brazil        4547.38  10701.16   5672.28   7868.06
                       Canada        9494.16  21897.05  11765.11  15896.85
                       France        8335.04  18695.63   9859.65  14121.97
                       Germany       8269.22  19231.85  10744.85  14877.02
                       India         3862.51   8360.26   4636.89   6153.87
                       Japan         8200.44  20442.57  10828.65  14049.90
                       Netherlands   9056.74  20411.97  11146.33  14948.27
                       Singapore     9739.50  23707.27  12907.90  17039.11
                       UAE           7923.68  18207.87  10355.46  13116.95
                       UK            8966.37  20473.17  11442.90  15111.30
                       USA          11266.47  27386.58  14309.60  19287.36
Forecasting            Australia     9322.70  21891.81  12015.32  15653.49
                       Brazil        4591.00  10456.21   5650.56   7982.91
                       Canada        9634.33  22187.57  12041.63  15888.13
                       France        7885.59  18844.63  10037.09  13859.39
                       Germany       8625.53  19211.86  11160.35  14583.95
                       India         3944.26   8850.00   4695.35   6113.48
                       Japan         7904.57  18597.49  10459.98  14602.40
                       Netherlands   8908.23  20421.52  10874.21  14497.75
                       Singapore     9965.61  22597.50  13219.97  16846.77
                       UAE           7977.19  18458.33  10107.42  13136.25
                       UK            8575.65  20242.89  10878.60  14881.14
                       USA          11479.77  26687.78  14512.60  19123.42
Generative AI          Australia     9092.54  21792.24  11647.68  16817.97
                       Brazil        4675.14  10143.60   5755.61   7777.99
                       Canada        9034.18  21348.51  11760.82  15888.87
                       France        8410.32  19237.69  10156.09  13744.10
                       Germany       8089.62  20071.92  10582.26  14388.64
                       India         3966.69   8263.92   4450.10   6334.78
                       Japan         7848.11  20465.37  10719.92  14181.25
                       Netherlands   8977.00  19824.20  10220.15  14712.51
                       Singapore    10269.37  24204.59  12521.62  16347.77
                       UAE           7935.43  18882.43  10254.97  13390.91
                       UK            8788.69  21263.72  11145.34  15957.16
                       USA          11472.81  26517.06  14071.29  19660.04
LLM                    Australia     8986.44  21896.45  11653.29  16576.55
                       Brazil        4472.15  11174.90   5693.86   8186.39
                       Canada        9169.75  22407.53  12241.88  16153.37
                       France        8004.75  18423.02  10337.06  13942.19
                       Germany       8021.92  19764.47  10903.02  14035.57
                       India         4189.50   8752.48   4467.08   6088.46
                       Japan         8106.59  18888.82  10831.18  13946.28
                       Netherlands   8482.72  20800.07  10885.57  14419.65
                       Singapore     9656.13  23197.94  12680.70  17698.74
                       UAE           8017.39  18111.94  10342.29  13125.07
                       UK            8698.77  20399.05  10694.47  14900.83
                       USA          11554.68  27853.50  14035.65  19079.13
MLOps                  Australia     9337.30  21541.15  11499.81  15821.78
                       Brazil        4414.54  10793.25   5600.54   7836.43
                       Canada        9611.60  22219.68  12247.44  15881.40
                       France        8197.17  18499.50  10482.90  13936.95
                       Germany       8577.18  20918.40  10965.96  15209.97
                       India         4059.75   8969.44   4673.05   6419.09
                       Japan         8540.08  20360.82  10681.79  14065.38
                       Netherlands   9049.14  20137.76  10458.68  14314.10
                       Singapore    10269.73  22805.01  12690.20  17316.64
                       UAE           8244.51  18972.91  10467.27  14091.22
                       UK            9023.38  21443.53  11345.97  15093.58
                       USA          10972.52  25938.64  14211.20  20176.71
NLP                    Australia     9637.44  21696.26  11612.77  16269.08
                       Brazil        4712.94  10716.84   6018.12   7949.25
                       Canada        9111.15  21118.53  11984.52  16577.32
                       France        8099.66  19005.27  10319.47  13998.80
                       Germany       8566.09  19012.21  10662.39  14160.99
                       India         4117.04   8773.02   4649.27   6068.07
                       Japan         8491.86  19945.21  11236.33  14431.92
                       Netherlands   8670.25  20732.17  10503.07  15137.76
                       Singapore    10361.56  23602.25  12940.38  17270.14
                       UAE           8102.68  17651.61  10067.87  13696.15
                       UK            9027.00  21127.14  11772.60  14693.01
                       USA          11473.21  25697.24  14458.35  19342.53
Reinforcement Learning Australia     9653.34  23301.81  11916.31  16633.80
                       Brazil        4603.20  10586.01   5733.11   7820.31
                       Canada        9041.82  22373.45  11850.18  15490.38
                       France        8098.71  19070.96  10321.34  14227.48
                       Germany       8516.60  19054.11  10974.34  14587.22
                       India         3956.85   8744.46   4900.63   6291.91
                       Japan         8425.61  20164.94  10488.55  14471.12
                       Netherlands   8436.32  19735.68  10783.06  14795.94
                       Singapore    10293.17  23053.47  11726.01  16979.99
                       UAE           8049.11  18207.79   9790.38  13582.68
                       UK            9010.37  21695.46  10723.43  14960.27
                       USA          11310.79  26650.40  14457.96  18959.64

In [463]:
# Compare average bonus across job role, country, and experience level

bonus_by_job_role_and_country = (
    pd.pivot_table(
        data=df,
        values="bonus_usd",
        index=["job_role", "country"],
        columns="experience_level",
        aggfunc="mean"
    )
    .round(2)
)

bonus_by_job_role_and_country

experience_level                          Entry      Lead       Mid    Senior
job_role                  country
AI Engineer               Australia     9742.32  22212.21  11784.10  16218.97
                          Brazil        4757.24  10622.74   5697.87   7779.13
                          Canada        9419.38  22535.15  12760.40  16021.37
                          France        8407.49  19019.77   9983.01  14068.03
                          Germany       8441.20  19767.35  11277.41  14511.75
                          India         4087.63   8881.06   4789.28   6199.48
                          Japan         8192.58  20776.09  11000.66  14637.03
                          Netherlands   9095.12  21096.12  10784.77  14913.55
                          Singapore    10330.82  23123.25  12968.68  16710.78
                          UAE           8181.38  18687.61  10768.13  13055.83
                          UK            9288.14  21316.08  11440.11  15119.57
                          USA          11441.55  26935.87  14963.78  19701.97
AI Software Engineer      Australia     9540.78  22701.20  11703.75  15649.80
                          Brazil        4442.74  10883.11   5847.04   8021.18
                          Canada        9579.61  22251.88  12103.20  16484.15
                          France        8089.22  18067.80  10360.11  13948.49
                          Germany       8148.61  20114.12  10448.04  14850.88
                          India         4061.62   8540.02   4540.91   6234.84
                          Japan         8342.68  19079.21  10683.55  14663.71
                          Netherlands   9136.84  21035.37  11149.68  14868.95
                          Singapore     9899.02  23899.44  12291.14  17328.26
                          UAE           8049.95  18268.54  10210.60  14293.92
                          UK            9172.35  20333.74  11646.91  15578.70
                          USA          11049.44  26482.75  14116.97  19026.10
Computer Vision Engineer  Australia    10205.11  23197.04  12223.75  17653.20
                          Brazil        4565.15  11168.21   5907.18   8060.21
                          Canada        9587.40  22734.30  12307.64  15689.23
                          France        8387.06  19948.28  10950.66  14774.73
                          Germany       8540.49  20444.17  11428.25  15000.88
                          India         3939.49   8879.59   4710.21   6608.36
                          Japan         9189.02  21488.09  11734.70  15196.61
                          Netherlands   9322.72  21428.50  11073.29  15437.14
                          Singapore    10479.42  25870.95  13132.68  17370.78
                          UAE           8320.84  19278.64  10956.45  14394.56
                          UK            9380.36  21908.93  11901.51  16382.52
                          USA          11908.98  27519.41  14688.70  20273.90
Data Analyst              Australia     7052.19  15682.91   8688.28  11608.65
                          Brazil        3815.86   7692.56   4289.95   5878.51
                          Canada        6536.66  15983.80   8382.41  12088.54
                          France        6076.51  13622.68   7622.49  10095.45
                          Germany       6025.32  13858.74   7439.41  10656.80
                          India         3887.24   5895.87   3811.37   4505.64
                          Japan         5890.10  13900.85   7693.75  10470.18
                          Netherlands   6241.47  14416.77   7627.66  10924.17
                          Singapore     7425.56  16504.41   9279.04  12733.99
                          UAE           5807.83  13280.85   7316.08   9181.94
                          UK            6376.68  15869.71   7715.44  10760.18
                          USA           7843.45  18948.39  10721.86  14284.70
Data Scientist            Australia     8987.16  21361.93  11707.12  14740.62
                          Brazil        4425.22  10229.90   6019.30   8014.62
                          Canada        8796.80  20707.46  11409.73  15380.03
                          France        7832.46  19176.69   9873.72  13595.48
                          Germany       8387.11  19843.08  10536.44  14396.32
                          India         3842.54   8168.57   4369.44   5903.88
                          Japan         8237.44  19383.30  10488.30  13640.67
                          Netherlands   8418.04  19891.98  10731.17  14551.42
                          Singapore     9823.73  22339.08  12216.11  17186.54
                          UAE           7778.63  17713.26   9438.58  13391.33
                          UK            8697.06  20307.18  10865.79  14637.84
                          USA          11470.48  25060.81  14054.73  18486.54
Machine Learning Engineer Australia     9777.56  22106.05  12623.31  16936.98
                          Brazil        4811.93  10805.42   6113.90   8500.77
                          Canada       10171.65  22458.88  13015.19  17096.71
                          France        8862.20  19851.73  10971.47  14641.61
                          Germany       9233.82  21608.74  12017.51  15862.89
                          India         4067.69   9161.75   4803.37   6598.37
                          Japan         8511.86  21599.83  11615.33  15052.47
                          Netherlands   9309.84  21324.30  11948.92  15458.55
                          Singapore    10394.67  24690.70  13817.18  17702.69
                          UAE           8406.16  19658.18  10617.61  14694.65
                          UK            8903.27  22021.32  11491.22  16068.31
                          USA          12433.04  28386.84  15262.13  19705.65
NLP Engineer              Australia     9424.90  23102.27  12014.44  16907.13
                          Brazil        4691.67  11019.33   5657.05   8213.97
                          Canada        9610.59  21972.00  12428.84  16833.69
                          France        8481.21  20499.12  10553.43  13881.58
                          Germany       8574.16  20255.46  11413.11  15439.16
                          India         4083.94   9119.59   4813.89   6243.63
                          Japan         8543.82  20796.88  10777.36  14929.47
                          Netherlands   9025.67  20899.95  11548.28  15123.25
                          Singapore    10340.90  23414.92  12851.29  17532.39
                          UAE           7998.17  19402.05  10454.87  13394.44
                          UK            9045.68  22768.45  11495.38  15826.23
                          USA          11744.07  28555.55  15157.22  19598.07
Research Scientist        Australia    10927.52  24620.78  13183.69  18866.36
                          Brazil        5013.05  12298.59   6326.19   8899.30
                          Canada       10627.71  26392.74  13491.76  18154.20
                          France        9343.98  22144.60  11747.52  15998.98
                          Germany       9738.73  21744.74  12461.93  16468.65
                          India         4172.41  10149.95   5260.74   7418.24
                          Japan         9715.43  22200.90  11707.67  16295.48
                          Netherlands   9953.43  21467.95  12280.61  16786.01
                          Singapore    11488.20  26638.15  14059.23  18986.93
                          UAE           9417.62  20204.72  11872.57  14901.82
                          UK           10127.71  23690.40  12892.76  15849.75
                          USA          13075.85  31048.92  16682.73  22551.28

## Level 2 Summary

This level extended the salary intelligence analysis by examining interactions between multiple workforce attributes.

The analyses demonstrated how compensation changes across combinations of:

- Country and experience level
- AI specialization and experience level
- Industry and experience level
- Education and experience level
- Job role, AI specialization, and experience level
- Bonus compensation across workforce segments

These segmentation insights provide a stronger understanding of compensation behavior and prepare the foundation for ranking the highest-performing workforce segments in the next level.

## Level 3 • Ranking Analytics

### Objective

Descriptive and segmentation analyses explain *how* compensation varies across the workforce. This level focuses on *who performs best*.

Ranking analytics identifies the highest and lowest performing workforce segments based on salary, bonus, and compensation metrics. These rankings help answer important business questions such as:

- Which countries provide the highest salaries?
- Which AI job roles receive the greatest compensation?
- Which AI specializations dominate the market?
- How does salary progress across experience levels?
- Which workforce segments consistently outperform others?

The outputs from this level are valuable for benchmarking, workforce planning, talent acquisition, and strategic compensation analysis.

## Country Performance Ranking

This section compares countries based on average salary to identify the highest-paying and lowest-paying AI job markets.

In [464]:
# Identify the highest and lowest paying countries based on average salary

average_salary_by_country = (
    df.groupby("country")["salary_usd"]
      .mean()
      .round(2)
      .sort_values(ascending=False)
)

top_countries_by_salary = average_salary_by_country.head(3)
bottom_countries_by_salary = average_salary_by_country.tail(3).sort_values()

display(
    top_countries_by_salary,
    bottom_countries_by_salary
)

country
USA          132995.21
Singapore    116954.73
Australia    110549.81
Name: salary_usd, dtype: float64

country
India     43106.30
Brazil    53704.84
UAE       93507.70
Name: salary_usd, dtype: float64

## Job Role Performance Ranking

The following analysis ranks AI job roles according to their average salary.

In [465]:
# Identify the highest and lowest paying job roles based on average salary

average_salary_by_job_role = (
    df.groupby("job_role")["salary_usd"]
      .mean()
      .round(2)
      .sort_values(ascending=False)
)

top_job_roles_by_salary = average_salary_by_job_role.head(3)
bottom_job_roles_by_salary = average_salary_by_job_role.tail(3).sort_values()

display(
    top_job_roles_by_salary,
    bottom_job_roles_by_salary
)

job_role
Research Scientist           109797.50
Machine Learning Engineer    102121.80
Computer Vision Engineer     101303.94
Name: salary_usd, dtype: float64

job_role
Data Analyst            69429.27
Data Scientist          94029.90
AI Software Engineer    97375.53
Name: salary_usd, dtype: float64

## AI Specialization Ranking

Different AI domains command different compensation levels.

This analysis identifies the highest and lowest paying AI specializations.

In [466]:
# Identify the highest and lowest paying AI specializations based on average salary

average_salary_by_specialization = (
    df.groupby("ai_specialization")["salary_usd"]
      .mean()
      .round(2)
      .sort_values(ascending=False)
)

top_specializations_by_salary = average_salary_by_specialization.head(3)
bottom_specializations_by_salary = average_salary_by_specialization.tail(3).sort_values()

display(
    top_specializations_by_salary,
    bottom_specializations_by_salary
)

ai_specialization
Generative AI    97096.78
LLM              97076.65
Analytics        96905.55
Name: salary_usd, dtype: float64

ai_specialization
Reinforcement Learning    95423.81
Forecasting               96010.56
NLP                       96443.81
Name: salary_usd, dtype: float64

## Bonus Compensation Ranking

Salary alone does not represent total employee rewards.

This analysis compares average bonus distribution across AI job roles.

In [467]:
# Rank job roles based on average bonus compensation

average_bonus_by_job_role = (
    df.groupby("job_role")["bonus_usd"]
      .mean()
      .round(2)
      .sort_values(ascending=False)
)

top_job_roles_by_bonus = average_bonus_by_job_role.head(3)
bottom_job_roles_by_bonus = average_bonus_by_job_role.tail(3).sort_values()

display(
    top_job_roles_by_bonus,
    bottom_job_roles_by_bonus
)

job_role
Research Scientist           14770.48
Machine Learning Engineer    13755.60
Computer Vision Engineer     13649.66
Name: bonus_usd, dtype: float64

job_role
Data Analyst             9393.20
Data Scientist          12660.66
AI Software Engineer    13196.87
Name: bonus_usd, dtype: float64

## Workforce Salary Progression

Ranking is useful not only across workforce groups but also across career progression.

The following analysis measures how average salary changes as professionals advance through experience levels.

In [468]:
# Measure salary growth across experience levels

salary_by_experience_level = (
    df.groupby("experience_level")["salary_usd"]
      .mean()
      .sort_values()
      .round(3)
)

salary_growth_percentage = (
    salary_by_experience_level
        .pct_change()
        .mul(100)
        .round(3)
)

salary_growth_percentage

experience_level
Entry        NaN
Mid       26.227
Senior    35.132
Lead      36.050
Name: salary_usd, dtype: float64

## Workforce Ranking

Dense ranking assigns the same rank to equal values without leaving gaps in the ranking sequence.

This provides an alternative perspective on workforce performance.

In [469]:
# Rank job roles based on average salary

average_salary_by_job_role = (
    df.groupby("job_role")["salary_usd"]
      .mean()
)

job_role_salary_rank = (
    average_salary_by_job_role
    .rank(
        ascending=False,
        method="dense"
    )
    .astype(int)
    .sort_values()
)

job_role_salary_rank

job_role
Research Scientist           1
Machine Learning Engineer    2
Computer Vision Engineer     3
NLP Engineer                 4
AI Engineer                  5
AI Software Engineer         6
Data Scientist               7
Data Analyst                 8
Name: salary_usd, dtype: int64

In [470]:
# Rank countries based on average salary

country_salary_rank = (
    df.groupby("country")["salary_usd"]
      .mean()
      .sort_values(ascending=False)
      .rank(
          ascending=False,
          method="dense"
      )
      .head(5)
)

country_salary_rank

country
USA          1.0
Singapore    2.0
Australia    3.0
Canada       4.0
UK           5.0
Name: salary_usd, dtype: float64

## Level 3 Summary

This level transformed descriptive salary statistics into comparative workforce rankings.

The analyses identified:

- Top and bottom performing countries
- Highest and lowest paying AI job roles
- Best and weakest AI specializations
- Bonus compensation leaders
- Salary progression across experience levels
- Workforce rankings using dense ranking methodology

These rankings establish the benchmark groups that will be explored further in **Level 4: Distribution Analytics**, where compensation variability, percentiles, quartiles, and salary spread are examined.

## Level 4 - Distribution Analytics

### Objective

Business averages provide only a partial understanding of workforce compensation. To fully understand salary behavior, it is essential to analyze how compensation is distributed across the workforce.

This level explores salary and bonus distributions using statistical measures such as percentiles, quartiles, variance, standard deviation, and compensation spread.

These analyses help answer questions such as:

- How are salaries distributed across the workforce?
- Where are the highest-paid professionals located within the distribution?
- How large is the compensation gap?
- How much variability exists in salaries?
- What defines low, medium, and high salary ranges?

The results establish statistical benchmarks that will be used in the next level for identifying elite workforce segments.

## Salary Distribution Analysis

The following analyses summarize salary distribution using percentiles and quartiles, providing a deeper understanding of compensation across the AI workforce.

In [471]:
# Calculate salary percentiles

salary_percentile_values = np.percentile(
    df["salary_usd"],
    [10, 30, 50, 75, 100]
)

salary_percentile_summary = pd.DataFrame({
    "Percentile": [
        "10%",
        "30%",
        "50%",
        "75%",
        "100%"
    ],
    "Salary": salary_percentile_values
})

salary_percentile_summary

  Percentile    Salary
0        10%   45389.7
1        30%   69147.4
2        50%   87544.0
3        75%  123906.0
4       100%  300622.0

In [472]:
# Calculate bonus percentiles

bonus_percentile_values = np.percentile(
    df["bonus_usd"],
    [10, 30, 50, 75, 100]
)

bonus_percentile_summary = pd.DataFrame({
    "Percentile": [
        "10%",
        "30%",
        "50%",
        "75%",
        "100%"
    ],
    "Bonus": bonus_percentile_values,
    "Country": country_salary_rank
})

bonus_percentile_summary

          Percentile     Bonus  Country
country
USA              10%   4705.00      1.0
Singapore        30%   7898.00      2.0
Australia        50%  11279.00      3.0
Canada           75%  16997.25      4.0
UK              100%  57681.00      5.0

In [473]:
# Create salary quartile categories

df["salary_quartile"] = pd.qcut(
    df["salary_usd"],
    q=4,
    labels=[
        "Low",
        "Mid",
        "High",
        "Best"
    ]
)

df["salary_percentile"].value_counts(
    normalize=True
).mul(100)

salary_percentile
95     1.075556
24     1.067778
82     1.065556
2      1.064444
25     1.061111
1      1.058889
85     1.055556
77     1.048889
37     1.048889
23     1.042222
69     1.041111
58     1.033333
86     1.032222
98     1.031111
33     1.031111
75     1.027778
73     1.025556
10     1.024444
79     1.024444
89     1.023333
57     1.023333
46     1.022222
72     1.022222
27     1.022222
52     1.021111
97     1.020000
19     1.020000
68     1.020000
11     1.020000
54     1.018889
50     1.015556
6      1.015556
32     1.014444
40     1.013333
63     1.013333
64     1.011111
78     1.011111
60     1.010000
90     1.008889
53     1.008889
13     1.007778
76     1.004444
28     1.004444
41     1.002222
94     1.002222
51     1.002222
15     1.002222
96     1.000000
8      1.000000
59     0.998889
14     0.997778
18     0.997778
55     0.996667
74     0.995556
29     0.994444
67     0.994444
43     0.993333
61     0.993333
66     0.992222
34     0.991111
4      0.987778
92     0.987778
3      0.986667
56     0.985556
48     0.985556
21     0.984444
39     0.984444
9      0.983333
65     0.983333
22     0.983333
35     0.983333
12     0.982222
80     0.982222
71     0.981111
49     0.981111
81     0.980000
70     0.978889
100    0.977778
99     0.975556
87     0.974444
5      0.974444
45     0.972222
84     0.971111
62     0.971111
36     0.967778
88     0.966667
44     0.966667
26     0.962222
17     0.961111
91     0.961111
30     0.960000
42     0.957778
7      0.955556
31     0.954444
47     0.953333
20     0.952222
83     0.952222
16     0.950000
93     0.934444
38     0.920000
Name: proportion, dtype: float64

## Workforce Distribution

Beyond statistical summaries, identifying where employees fall within the salary distribution provides valuable workforce intelligence.

The following analyses identify the highest-paid workforce segments using percentile thresholds.

In [474]:
# Identify professionals within the top 10 percent salary bracket

top_10_percent_salary = np.percentile(
    df["salary_usd"],
    90
)

top_salary_workforce = (
    df[df["salary_usd"] >= top_10_percent_salary]
)

top_salary_workforce.shape

(9000, 36)

In [475]:
# Analyze workforce composition within the top salary bracket

top_salary_workforce["experience_level"].value_counts()

top_salary_workforce["country"].value_counts()

top_salary_workforce["job_role"].value_counts()

top_salary_workforce["ai_specialization"].value_counts()

ai_specialization
Generative AI             1191
LLM                       1160
Analytics                 1153
Computer Vision           1141
MLOps                     1132
Reinforcement Learning    1080
Forecasting               1078
NLP                       1065
Name: count, dtype: int64

## Compensation Spread

Spread measures the distance between the highest and lowest values within a distribution.

These metrics provide a quick indication of compensation inequality across the workforce.

In [476]:
# Calculate salary and bonus spread

salary_spread = (
    df["salary_usd"].max() - df["salary_usd"].min()
)

bonus_spread = (
    df["bonus_usd"].max() - df["bonus_usd"].min()
)

distribution_spread_summary = pd.DataFrame({
    "Metric": [
        "Salary Spread",
        "Bonus Spread"
    ],
    "Value": [
        salary_spread,
        bonus_spread
    ]
})

distribution_spread_summary

          Metric   Value
0  Salary Spread  272622
1   Bonus Spread   56277

## Statistical Variability

Variance and standard deviation measure how widely salaries vary across the workforce.

Higher values indicate greater salary dispersion.

In [477]:
# Calculate salary variance

salary_variance = np.var(
    df["salary_usd"]
).round(3)

salary_variance

np.float64(1930304915.442)

In [478]:
# Calculate salary standard deviation

salary_standard_deviation = np.std(
    df["salary_usd"]
).round(3)

salary_standard_deviation

np.float64(43935.235)

## Level 4 Summary

This level expanded salary intelligence from descriptive averages to statistical distribution analysis.

The following insights were generated:

- Salary percentile benchmarks
- Bonus percentile benchmarks
- Salary quartile segmentation
- Top salary workforce identification
- Workforce composition within high-income segments
- Salary and bonus spread
- Salary variance
- Salary standard deviation

These statistical measures establish the foundation for **Level 5: Elite Workforce Analytics**, where the highest-paid professionals and premium compensation segments will be analyzed in greater detail.

# Level 5 • Elite Workforce Analytics

## Objective

After understanding the overall salary distribution, the next step is to identify the highest-performing workforce segments.

This level focuses on professionals who belong to the top compensation brackets and investigates the characteristics that distinguish them from the rest of the workforce.

The analyses answer questions such as:

- Who belongs to the top 1% and top 5% salary groups?
- Which countries dominate elite compensation?
- Which AI roles consistently appear among the highest earners?
- Which AI specializations produce premium salaries?
- How does total compensation compare with base salary?

These insights help organizations understand where premium AI talent exists and support strategic hiring and compensation planning.

## Top Salary Workforce

The following analyses identify professionals who belong to the highest salary brackets based on percentile thresholds.

In [479]:
# Identify professionals earning within the top 1% salary bracket

top_1_percent_salary = np.percentile(
    df["salary_usd"],
    99
)

top_1_percent_earners = (
    df[df["salary_usd"] >= top_1_percent_salary]
)

top_1_percent_earners

,id,country,job_role,ai_specialization,experience_level,experience_years,salary_usd,bonus_usd,education_required,industry,company_size,interview_rounds,year,work_mode,weekly_hours,company_rating,job_openings,hiring_difficulty_score,layoff_risk,ai_adoption_score,company_funding_billion,economic_index,ai_maturity_years,offer_acceptance_rate,tax_rate_percent,vacation_days,skill_demand_score,automation_risk,job_security_score,career_growth_score,work_life_balance_score,promotion_speed,salary_percentile,cost_of_living_index,employee_satisfaction,salary_quartile
121,122,Canada,Research Scientist,Computer Vision,Lead,19,246257,38602,Diploma,Gaming,Small,6,2022,Hybrid,43.8,3.29,8,47.18,0.047,65,8.90,65.57,3,92.78,31.3,21,40,24,87,57,79,60,28,1.84,86,Best
154,155,USA,Machine Learning Engineer,Reinforcement Learning,Lead,19,221290,12958,Master,Energy,Large,6,2020,Hybrid,47.7,4.09,15,27.63,0.109,73,2.55,53.58,3,88.38,22.8,11,37,64,73,58,64,51,77,2.33,89,Best
201,202,Canada,Computer Vision Engineer,Computer Vision,Lead,19,216227,25332,Bootcamp,Gaming,Enterprise,2,2026,Remote,50.2,3.37,13,89.92,0.074,64,3.52,74.22,6,70.83,30.4,28,61,35,88,50,59,52,6,2.11,80,Best
336,337,Australia,Research Scientist,Computer Vision,Lead,16,223295,37479,Bachelor,Tech,Enterprise,5,2026,Remote,36.5,4.47,21,82.73,0.120,80,7.91,78.91,3,94.44,31.2,11,26,35,79,76,98,20,97,2.22,90,Best
470,471,USA,AI Software Engineer,Generative AI,Lead,16,222197,24792,Master,Energy,Small,6,2021,Remote,51.6,3.32,5,35.72,0.121,60,0.85,52.98,7,82.97,12.7,20,91,5,82,46,64,23,35,2.21,96,Best
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
89438,89439,Australia,AI Engineer,Generative AI,Lead,19,217328,27915,Bachelor,Consulting,Startup,7,2020,Hybrid,49.4,3.62,27,39.05,0.114,52,7.17,69.86,7,65.62,32.3,11,73,80,61,48,60,97,15,0.99,78,Best
89876,89877,Canada,Machine Learning Engineer,Analytics,Lead,19,226378,40646,Master,Consulting,Large,3,2026,Onsite,54.0,3.84,16,60.16,0.041,78,6.10,64.51,6,81.45,20.3,24,44,94,87,70,49,40,59,1.77,84,Best
89884,89885,USA,Research Scientist,Reinforcement Learning,Lead,14,220659,45548,Bootcamp,Gaming,Large,5,2022,Remote,40.0,4.78,28,52.32,0.003,100,3.27,67.28,10,79.14,22.2,20,79,23,85,66,74,52,2,1.57,92,Best
89949,89950,USA,Research Scientist,Generative AI,Lead,18,248719,26815,Bachelor,Energy,Medium,2,2024,Onsite,40.3,4.19,17,55.30,0.037,66,0.65,77.13,3,92.91,35.9,30,79,63,90,49,86,42,2,1.08,95,Best
89961,89962,USA,Machine Learning Engineer,Computer Vision,Lead,15,232744,21275,Bachelor,Education,Enterprise,7,2023,Remote,44.3,3.52,11,36.51,0.065,57,3.97,96.48,10,62.18,27.7,10,67,41,84,51,87,39,35,1.37,91,Best

In [480]:
# Analyze the composition of the top 1% salary workforce

top_1_percent_earners["experience_level"].value_counts()

top_1_percent_earners["country"].value_counts()

top_1_percent_earners["job_role"].value_counts()

top_1_percent_earners["ai_specialization"].value_counts()

ai_specialization
Analytics                 127
LLM                       119
Generative AI             118
Computer Vision           117
Forecasting               109
NLP                       108
Reinforcement Learning    105
MLOps                      98
Name: count, dtype: int64

In [481]:
# Identify professionals earning within the top 5% salary bracket

top_5_percent_salary = np.percentile(
    df["salary_usd"],
    95
)

top_5_percent_earners = (
    df[df["salary_usd"] >= top_5_percent_salary]
)

top_5_percent_earners

,id,country,job_role,ai_specialization,experience_level,experience_years,salary_usd,bonus_usd,education_required,industry,company_size,interview_rounds,year,work_mode,weekly_hours,company_rating,job_openings,hiring_difficulty_score,layoff_risk,ai_adoption_score,company_funding_billion,economic_index,ai_maturity_years,offer_acceptance_rate,tax_rate_percent,vacation_days,skill_demand_score,automation_risk,job_security_score,career_growth_score,work_life_balance_score,promotion_speed,salary_percentile,cost_of_living_index,employee_satisfaction,salary_quartile
7,8,Germany,Computer Vision Engineer,MLOps,Lead,19,194659,14720,Master,Consulting,Small,3,2021,Onsite,40.2,4.77,14,70.44,0.177,73,6.81,73.41,11,65.43,41.9,27,34,96,84,66,77,57,75,2.43,81,Best
24,25,Canada,AI Engineer,Computer Vision,Lead,19,183108,29935,Bachelor,Education,Enterprise,6,2026,Remote,37.7,4.02,14,40.32,0.182,65,1.32,53.63,11,70.09,12.1,18,17,45,69,42,88,68,9,2.24,88,Best
41,42,Netherlands,AI Software Engineer,Generative AI,Lead,18,187810,36355,Bootcamp,Education,Enterprise,5,2020,Remote,40.4,4.38,18,46.68,0.127,64,1.32,73.61,14,72.07,38.3,25,58,34,78,50,87,24,97,1.34,77,Best
42,43,Germany,Research Scientist,Forecasting,Lead,14,180739,9690,Bachelor,Retail,Medium,7,2023,Hybrid,45.1,4.34,13,80.37,0.084,86,6.04,77.40,6,66.09,39.3,18,43,41,92,79,68,38,70,0.59,79,Best
56,57,Netherlands,Computer Vision Engineer,MLOps,Lead,19,187463,31897,Master,Tech,Startup,5,2024,Onsite,52.0,4.22,15,92.38,0.063,67,7.69,57.36,6,62.20,14.7,19,85,75,78,61,55,64,48,0.71,75,Best
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
89961,89962,USA,Machine Learning Engineer,Computer Vision,Lead,15,232744,21275,Bachelor,Education,Enterprise,7,2023,Remote,44.3,3.52,11,36.51,0.065,57,3.97,96.48,10,62.18,27.7,10,67,41,84,51,87,39,35,1.37,91,Best
89969,89970,UK,Research Scientist,LLM,Lead,12,180004,13509,Diploma,Finance,Small,4,2021,Onsite,49.9,4.42,15,47.41,0.148,73,4.01,54.54,12,77.38,38.4,21,34,57,77,57,53,34,69,1.99,69,Best
89981,89982,Canada,Research Scientist,LLM,Lead,17,194422,15794,Phd,Consulting,Startup,7,2024,Remote,41.8,3.79,29,63.11,0.043,49,6.49,86.85,5,70.32,19.7,27,36,60,83,44,62,58,22,0.75,82,Best
89993,89994,Singapore,AI Software Engineer,NLP,Lead,15,192451,12820,Diploma,Gaming,Small,6,2021,Remote,46.0,3.63,26,54.39,0.000,57,2.08,98.79,9,55.96,39.3,10,84,49,90,51,63,49,93,1.93,79,Best
89994,89995,UK,Research Scientist,Reinforcement Learning,Lead,18,190141,31443,Master,Consulting,Large,7,2024,Hybrid,50.0,3.80,28,44.08,0.000,47,5.45,80.32,14,78.83,32.8,17,3,66,99,41,70,80,71,1.20,86,Best

In [482]:
# Analyze the composition of the top 5% salary workforce

top_5_percent_earners["experience_level"].value_counts()

top_5_percent_earners["industry"].value_counts()

top_5_percent_earners["job_role"].value_counts()

top_5_percent_earners["country"].value_counts()

country
USA            1425
Singapore       794
Australia       561
Canada          489
Netherlands     313
UK              300
Germany         217
Japan           198
France          130
UAE              73
Name: count, dtype: int64

## Total Compensation Intelligence

Salary alone does not fully represent employee earnings.

This section evaluates workforce performance using total compensation, which combines both salary and bonus payments.

In [483]:
# Calculate total compensation for every workforce record

df["total_compensation"] = (
    df["salary_usd"]
    + df["bonus_usd"]
)

df["total_compensation"].sample(5).reset_index()

   index  total_compensation
0  36590               85140
1  25395              154430
2  10615               44644
3   7537               54690
4  66641              101104

In [484]:
# Generate descriptive statistics for total compensation

df["total_compensation"].describe().round(2)

count     90000.00
mean     109574.67
std       50136.88
min       29404.00
25%       73190.75
50%       99364.00
75%      140532.25
max      348957.00
Name: total_compensation, dtype: float64

In [485]:
# Calculate descriptive total compensation statistics by experience level

compensation_by_experience_level = (
    df.groupby("experience_level")
      .agg(
          job_posting_count=("total_compensation", "count"),
          average_total_compensation=("total_compensation", "mean"),
          median_total_compensation=("total_compensation", "median"),
          minimum_total_compensation=("total_compensation", "min"),
          maximum_total_compensation=("total_compensation", "max"),
          total_compensation_standard_deviation=("total_compensation", "std")
      )
      .round(2)
      .sort_values(by="average_total_compensation", ascending=False)
)

compensation_by_experience_level

,job_posting_count,average_total_compensation,median_total_compensation,minimum_total_compensation,maximum_total_compensation,total_compensation_standard_deviation
experience_level,,,,,,
Lead,22556,161573.50,166111.5,35295,348957,51193.28
Senior,22680,118677.47,121917.0,29437,264423,37288.04
Mid,22459,87851.50,90478.0,29404,194108,27406.61
Entry,22305,69608.00,71874.0,29409,142566,20772.01

In [486]:
# Evaluate the relationship between salary, bonus, and total compensation

df[
    [
        "salary_usd",
        "bonus_usd",
        "total_compensation"
    ]
].corr().round(3)

                    salary_usd  bonus_usd  total_compensation
salary_usd               1.000      0.752               0.995
bonus_usd                0.752      1.000               0.816
total_compensation       0.995      0.816               1.000

## Elite Compensation Segments

Instead of focusing only on salary, this analysis identifies professionals belonging to the highest total compensation bracket.

In [487]:
# Identify professionals within the top 5% total compensation bracket

top_5_percent_compensation = np.percentile(
    df["total_compensation"],
    95
)

top_total_compensation_earners = (
    df[
        df["total_compensation"]
        >= top_5_percent_compensation
    ]
)

top_total_compensation_earners

,id,country,job_role,ai_specialization,experience_level,experience_years,salary_usd,bonus_usd,education_required,industry,company_size,interview_rounds,year,work_mode,weekly_hours,company_rating,job_openings,hiring_difficulty_score,layoff_risk,ai_adoption_score,company_funding_billion,economic_index,ai_maturity_years,offer_acceptance_rate,tax_rate_percent,vacation_days,skill_demand_score,automation_risk,job_security_score,career_growth_score,work_life_balance_score,promotion_speed,salary_percentile,cost_of_living_index,employee_satisfaction,salary_quartile,total_compensation
7,8,Germany,Computer Vision Engineer,MLOps,Lead,19,194659,14720,Master,Consulting,Small,3,2021,Onsite,40.2,4.77,14,70.44,0.177,73,6.81,73.41,11,65.43,41.9,27,34,96,84,66,77,57,75,2.43,81,Best,209379
24,25,Canada,AI Engineer,Computer Vision,Lead,19,183108,29935,Bachelor,Education,Enterprise,6,2026,Remote,37.7,4.02,14,40.32,0.182,65,1.32,53.63,11,70.09,12.1,18,17,45,69,42,88,68,9,2.24,88,Best,213043
41,42,Netherlands,AI Software Engineer,Generative AI,Lead,18,187810,36355,Bootcamp,Education,Enterprise,5,2020,Remote,40.4,4.38,18,46.68,0.127,64,1.32,73.61,14,72.07,38.3,25,58,34,78,50,87,24,97,1.34,77,Best,224165
46,47,UK,AI Engineer,LLM,Lead,15,172678,34093,Bachelor,Education,Enterprise,7,2026,Hybrid,47.8,3.51,26,76.05,0.121,79,7.20,49.63,5,68.06,28.8,24,24,7,83,76,70,21,34,0.73,84,Best,206771
56,57,Netherlands,Computer Vision Engineer,MLOps,Lead,19,187463,31897,Master,Tech,Startup,5,2024,Onsite,52.0,4.22,15,92.38,0.063,67,7.69,57.36,6,62.20,14.7,19,85,75,78,61,55,64,48,0.71,75,Best,219360
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
89949,89950,USA,Research Scientist,Generative AI,Lead,18,248719,26815,Bachelor,Energy,Medium,2,2024,Onsite,40.3,4.19,17,55.30,0.037,66,0.65,77.13,3,92.91,35.9,30,79,63,90,49,86,42,2,1.08,95,Best,275534
89961,89962,USA,Machine Learning Engineer,Computer Vision,Lead,15,232744,21275,Bachelor,Education,Enterprise,7,2023,Remote,44.3,3.52,11,36.51,0.065,57,3.97,96.48,10,62.18,27.7,10,67,41,84,51,87,39,35,1.37,91,Best,254019
89981,89982,Canada,Research Scientist,LLM,Lead,17,194422,15794,Phd,Consulting,Startup,7,2024,Remote,41.8,3.79,29,63.11,0.043,49,6.49,86.85,5,70.32,19.7,27,36,60,83,44,62,58,22,0.75,82,Best,210216
89993,89994,Singapore,AI Software Engineer,NLP,Lead,15,192451,12820,Diploma,Gaming,Small,6,2021,Remote,46.0,3.63,26,54.39,0.000,57,2.08,98.79,9,55.96,39.3,10,84,49,90,51,63,49,93,1.93,79,Best,205271
89994,89995,UK,Research Scientist,Reinforcement Learning,Lead,18,190141,31443,Master,Consulting,Large,7,2024,Hybrid,50.0,3.80,28,44.08,0.000,47,5.45,80.32,14,78.83,32.8,17,3,66,99,41,70,80,71,1.20,86,Best,221584

In [488]:
# Analyze the composition of the highest compensated workforce

top_total_compensation_earners["country"].value_counts()

top_total_compensation_earners["job_role"].value_counts()

top_total_compensation_earners["ai_specialization"].value_counts()

ai_specialization
Analytics                 588
Generative AI             581
LLM                       577
MLOps                     572
Reinforcement Learning    563
Computer Vision           557
Forecasting               533
NLP                       529
Name: count, dtype: int64

## Premium Compensation Rankings

The final analyses identify the highest-paid workforce records based on salary and total compensation.

In [489]:
# Display the highest salary job postings

highest_salary_records = (
    df.nlargest(20, "salary_usd")[
        [
            "job_role",
            "country",
            "ai_specialization",
            "salary_usd"
        ]
    ]
    .reset_index(drop=True)
)

highest_salary_records

                     job_role country       ai_specialization  salary_usd
0          Research Scientist     USA                     NLP      300622
1          Research Scientist     USA         Computer Vision      299543
2          Research Scientist     USA                   MLOps      297267
3          Research Scientist     USA                     LLM      289776
4          Research Scientist     USA         Computer Vision      289000
5          Research Scientist     USA               Analytics      288941
6          Research Scientist     USA  Reinforcement Learning      288779
7          Research Scientist     USA           Generative AI      286008
8          Research Scientist     USA             Forecasting      284840
9          Research Scientist     USA                   MLOps      284028
10         Research Scientist     USA         Computer Vision      283321
11         Research Scientist     USA  Reinforcement Learning      283182
12         Research Scientist     USA           Generative AI      279609
13         Research Scientist     USA         Computer Vision      279406
14         Research Scientist     USA                     NLP      278553
15         Research Scientist     USA               Analytics      278343
16  Machine Learning Engineer     USA                   MLOps      277408
17  Machine Learning Engineer     USA           Generative AI      277271
18   Computer Vision Engineer     USA  Reinforcement Learning      276175
19         Research Scientist     USA  Reinforcement Learning      275933

In [490]:
# Display the highest total compensation job postings

highest_compensation_records = (
    df.nlargest(20, "total_compensation")[
        [
            "job_role",
            "ai_specialization",
            "country",
            "total_compensation"
        ]
    ]
    .reset_index(drop=True)
)

highest_compensation_records

,job_role,ai_specialization,country,total_compensation
0,Research Scientist,Computer Vision,USA,348957
1,Research Scientist,LLM,USA,345315
2,Research Scientist,Reinforcement Learning,USA,344826
3,Research Scientist,NLP,USA,341932
4,Research Scientist,Forecasting,USA,339468
5,Research Scientist,Computer Vision,USA,331441
6,Research Scientist,Forecasting,USA,330419
7,Research Scientist,Generative AI,USA,326893
8,Machine Learning Engineer,Generative AI,USA,326665
9,Research Scientist,MLOps,USA,326480
10,Research Scientist,Computer Vision,USA,326014
11,Research Scientist,Reinforcement Learning,USA,325519
12,Research Scientist,MLOps,USA,324351
13,NLP Engineer,Computer Vision,USA,323666
14,Computer Vision Engineer,Reinforcement Learning,USA,323161
15,Machine Learning Engineer,Generative AI,USA,323114
16,NLP Engineer,Forecasting,USA,321830
17,Research Scientist,Reinforcement Learning,USA,319989
18,Research Scientist,Analytics,USA,319430
19,Research Scientist,Computer Vision,USA,319273

## Level 5 Summary

This level focused on identifying the highest-performing workforce segments within the AI job market.

The completed analyses include:

- Top 1% salary workforce
- Top 5% salary workforce
- Total compensation calculation
- Compensation summary statistics
- Compensation by experience level
- Salary and bonus correlation with total compensation
- Top 5% compensation workforce
- Highest salary records
- Highest total compensation records

These insights establish a detailed profile of elite AI professionals and prepare the foundation for **Level 6: Career Progression Analytics**, where salary growth, compensation evolution, and workforce mobility across career stages will be explored.

## 02 Salary Intelligence Advanced

## Level 6: Cohort Analytics

### Objective

Cohort Analytics studies how compensation evolves throughout an AI professional's career.

Unlike descriptive analytics, cohort analytics focuses on progression across different career stages and identifies where the largest improvements in salary, bonus, and total compensation occur.

This section answers questions such as:

- How does salary evolve across experience levels?
- How does bonus change during career progression?
- How does total compensation grow?
- Which career stage experiences the highest compensation growth?
- How much does compensation increase from Entry level to Lead level?

## 6.1 Experience Level Progression Analysis

Measure the average salary, bonus, and total compensation across experience levels, and calculate the percentage growth between consecutive career stages.

In [491]:
# Define the experience level hierarchy

experience_level_order = [
    "Entry",
    "Mid",
    "Senior",
    "Lead"
]

# Calculate average salary by experience level

average_salary_by_experience = (
    df.groupby("experience_level")["salary_usd"]
      .mean()
      .reindex(experience_level_order)
      .round(2)
)

average_salary_by_experience

experience_level
Entry      61327.59
Mid        77411.91
Senior    104608.04
Lead      142318.95
Name: salary_usd, dtype: float64

In [492]:
# Calculate salary growth across experience levels

salary_growth_percentage = (
    average_salary_by_experience
    .pct_change()
    .mul(100)
    .round(2)
)

salary_growth_percentage

experience_level
Entry       NaN
Mid       26.23
Senior    35.13
Lead      36.05
Name: salary_usd, dtype: float64

## 6.3 Analyze Bonus Progression Across Experience Levels

Evaluate how bonus compensation changes as professionals progress through different experience levels.

In [493]:
# Calculate average bonus by experience level

average_bonus_by_experience = (
    df.groupby("experience_level")["bonus_usd"]
      .mean()
      .reindex(experience_level_order)
      .round(2)
)

average_bonus_by_experience

experience_level
Entry      8280.42
Mid       10439.59
Senior    14069.43
Lead      19254.55
Name: bonus_usd, dtype: float64

In [494]:
# Calculate bonus growth across experience levels

bonus_growth_percentage = (
    average_bonus_by_experience
    .pct_change()
    .mul(100)
    .round(2)
)

bonus_growth_percentage

experience_level
Entry       NaN
Mid       26.08
Senior    34.77
Lead      36.85
Name: bonus_usd, dtype: float64

## 6.4 Analyze Total Compensation Progression Across Experience Levels

Measure the overall compensation growth throughout the career journey.

In [495]:
# Calculate total compensation for every workforce record

df["total_compensation"] = (
    df["salary_usd"]
    + df["bonus_usd"]
)

df["total_compensation"].sample(5).reset_index()

# Calculate average total compensation by experience level

average_total_compensation_by_experience = (
    df.groupby("experience_level")["total_compensation"]
      .mean()
      .reindex(experience_level_order)
      .round(2)
)

average_total_compensation_by_experience

experience_level
Entry      69608.00
Mid        87851.50
Senior    118677.47
Lead      161573.50
Name: total_compensation, dtype: float64

In [496]:
# Calculate total compensation growth across experience levels

total_compensation_growth_percentage = (
    average_total_compensation_by_experience
    .pct_change()
    .mul(100)
    .round(2)
)

total_compensation_growth_percentage

experience_level
Entry       NaN
Mid       26.21
Senior    35.09
Lead      36.15
Name: total_compensation, dtype: float64

## 6.5 Create Career Stage Categories

Segment job postings into career stages using years of professional experience.

In [497]:
# Categorize job postings into career stages

df["career_stage"] = pd.cut(
    df["experience_years"],
    bins=[-1, 2, 5, 10, 20],
    labels=[
        "Early Career",
        "Developing",
        "Experienced",
        "Expert"
    ]
)

df["career_stage"].value_counts().sort_index()

career_stage
Early Career    28014
Developing      16750
Experienced     18825
Expert          26411
Name: count, dtype: int64

## 6.6 Evaluate Salary Distribution by Career Stage

Analyze descriptive salary statistics for each career stage.

In [498]:
# Calculate descriptive salary statistics by career stage

salary_by_career_stage = (
    df.groupby("career_stage")
      .agg(
          job_posting_count=("salary_usd", "count"),
          average_salary=("salary_usd", "mean"),
          median_salary=("salary_usd", "median"),
          minimum_salary=("salary_usd", "min"),
          maximum_salary=("salary_usd", "max"),
          salary_standard_deviation=("salary_usd", "std")
      )
      .round(2)
)

salary_by_career_stage

,job_posting_count,average_salary,median_salary,minimum_salary,maximum_salary,salary_standard_deviation
career_stage,,,,,,
Early Career,28014,63020.18,65095.5,28000,128943,18937.47
Developing,16750,80063.20,83093.5,28000,160043,24314.97
Experienced,18825,101836.23,105168.0,28000,210721,31372.78
Expert,26411,138790.25,142537.0,31265,300622,44182.23

## 6.7 Evaluate Bonus Distribution by Career Stage

Analyze descriptive bonus statistics across career stages.

In [499]:
# Calculate descriptive bonus statistics by career stage

bonus_by_career_stage = (
    df.groupby("career_stage")
      .agg(
          job_posting_count=("bonus_usd", "count"),
          average_bonus=("bonus_usd", "mean"),
          median_bonus=("bonus_usd", "median"),
          minimum_bonus=("bonus_usd", "min"),
          maximum_bonus=("bonus_usd", "max"),
          bonus_standard_deviation=("bonus_usd", "std")
      )
      .round(2)
)

bonus_by_career_stage

,job_posting_count,average_bonus,median_bonus,minimum_bonus,maximum_bonus,bonus_standard_deviation
career_stage,,,,,,
Early Career,28014,8506.69,7864.0,1409,27171,4116.55
Developing,16750,10797.09,10001.0,1404,34065,5274.91
Experienced,18825,13695.01,12788.0,1437,45474,6652.32
Expert,26411,18764.59,17315.0,1810,57681,9313.17

## 6.8 Evaluate Total Compensation Distribution by Career Stage

Analyze descriptive total compensation statistics across career stages.

In [500]:
# Calculate descriptive total compensation statistics by career stage

compensation_by_career_stage = (
    df.groupby("career_stage")
      .agg(
          job_posting_count=("total_compensation", "count"),
          average_total_compensation=("total_compensation", "mean"),
          median_total_compensation=("total_compensation", "median"),
          minimum_total_compensation=("total_compensation", "min"),
          maximum_total_compensation=("total_compensation", "max"),
          total_compensation_standard_deviation=("total_compensation", "std")
      )
      .round(2)
)

compensation_by_career_stage

,job_posting_count,average_total_compensation,median_total_compensation,minimum_total_compensation,maximum_total_compensation,total_compensation_standard_deviation
career_stage,,,,,,
Early Career,28014,71526.86,73699.0,29409,152620,21731.08
Developing,16750,90860.29,94060.0,29404,194108,27934.62
Experienced,18825,115531.25,118979.0,29437,255168,35921.15
Expert,26411,157554.84,161281.0,34080,348957,50650.47

## 6.9 Measure Career Mobility

Calculate the percentage increase in salary, bonus, and total compensation from Entry level to Lead level.

In [501]:
# Calculate salary mobility

salary_mobility_percentage = (
    (
        average_salary_by_experience["Lead"]
        - average_salary_by_experience["Entry"]
    )
    / average_salary_by_experience["Entry"]
) * 100

print(f"Salary Mobility: {salary_mobility_percentage:.2f}%")

Salary Mobility: 132.06%

In [502]:
# Calculate bonus mobility

bonus_mobility_percentage = (
    (
        average_bonus_by_experience["Lead"]
        - average_bonus_by_experience["Entry"]
    )
    / average_bonus_by_experience["Entry"]
) * 100

print(f"Bonus Mobility: {bonus_mobility_percentage:.2f}%")

Bonus Mobility: 132.53%

In [503]:
# Calculate total compensation mobility

total_compensation_mobility_percentage = (
    (
        average_total_compensation_by_experience["Lead"]
        - average_total_compensation_by_experience["Entry"]
    )
    / average_total_compensation_by_experience["Entry"]
) * 100

print(
    f"Total Compensation Mobility: "
    f"{total_compensation_mobility_percentage:.2f}%"
)

Total Compensation Mobility: 132.12%

## 6.10 Summarize Career Progression Metrics

Combine salary, bonus, and total compensation into a single summary table for comparative analysis across experience levels.

In [504]:
# Create a consolidated career progression summary

career_progression_summary = pd.DataFrame({
    "Average Salary": average_salary_by_experience,
    "Average Bonus": average_bonus_by_experience,
    "Average Total Compensation": average_total_compensation_by_experience
})

career_progression_summary

                  Average Salary  Average Bonus  Average Total Compensation
experience_level
Entry                   61327.59        8280.42                    69608.00
Mid                     77411.91       10439.59                    87851.50
Senior                 104608.04       14069.43                   118677.47
Lead                   142318.95       19254.55                   161573.50

## Level 7: Multi-Factor Analytics

## Objective

Analyze the combined influence of multiple workforce factors on salary and total compensation. Unlike single-variable analysis, this level explores interactions between countries, experience levels, job roles, AI specializations, industries, education, and work modes to uncover deeper compensation patterns.

## 7.1 Analyze Salary Across Experience-Level Combinations

Compare average salary across different experience levels using multiple business dimensions.

In [505]:
# Compare average salary across countries and experience levels

salary_by_country_and_experience = (
    pd.pivot_table(
        data=df,
        values="salary_usd",
        index="country",
        columns="experience_level",
        aggfunc="mean"
    )
    .round(2)
)

salary_by_country_and_experience

experience_level     Entry       Lead        Mid     Senior
country
Australia         69828.58  163659.49   88438.30  119652.38
Brazil            34073.38   78634.81   42519.65   58307.23
Canada            69239.30  160558.39   87764.59  118161.01
France            60507.76  140554.17   76539.67  103718.16
Germany           63217.73  146904.43   80086.09  107784.37
India             29367.15   63014.32   34656.46   45757.61
Japan             61811.99  145512.93   78742.48  105935.31
Netherlands       64959.80  151713.46   81623.91  110242.15
Singapore         74109.77  172604.69   94096.38  126494.42
UAE               59033.18  136858.10   75119.71  100619.86
UK                65835.30  152454.07   82945.90  112082.51
USA               83936.84  197397.86  106142.66  144487.64

## 7.2 Salary Analysis by Job Role and Experience Level

Evaluate how salary changes across experience levels for different AI job roles.

In [506]:
# Compare average salary across job roles and experience levels

salary_by_job_role_and_experience = (
    pd.pivot_table(
        data=df,
        values="salary_usd",
        index="job_role",
        columns="experience_level",
        aggfunc="mean"
    )
    .round(2)
)

salary_by_job_role_and_experience

experience_level              Entry       Lead       Mid     Senior
job_role
AI Engineer                62356.44  143516.13  78769.18  105949.08
AI Software Engineer       61672.76  143321.08  77448.52  104558.46
Computer Vision Engineer   64751.58  149702.58  81145.20  109800.70
Data Analyst               45019.30  102407.77  56067.57   75314.70
Data Scientist             59320.65  138985.49  74934.10  102153.95
Machine Learning Engineer  64646.16  150251.64  82093.72  111612.02
NLP Engineer               62644.86  147035.37  80061.64  108072.55
Research Scientist         69834.56  161450.78  88930.88  118671.23

## 7.3 Salary Analysis by AI Specialization and Experience Level

In [507]:
# Compare average salary across AI specialization roles and experience levels

salary_by_specialization_and_experience = (
    pd.pivot_table(
        data=df,
        values="salary_usd",
        index="ai_specialization",
        columns="experience_level",
        aggfunc="mean"
    )
    .round(2)
)

salary_by_specialization_and_experience

experience_level           Entry       Lead       Mid     Senior
ai_specialization
Analytics               61859.60  142775.48  78520.61  104794.04
Computer Vision         61530.52  141837.93  77024.52  104026.18
Forecasting             61330.94  141785.68  77003.74  104645.09
Generative AI           61486.32  144657.03  76512.82  104209.52
LLM                     61094.07  141876.88  77145.39  106350.34
MLOps                   61145.08  142946.22  78011.66  104425.37
NLP                     61236.47  141338.09  77839.88  104925.72
Reinforcement Learning  60946.20  141263.13  77204.37  103447.33

## 7.4 Salary Analysis by Industry and Experience Level

In [508]:
# Compare average salary across industry and experience levels

salary_by_industry_and_experience = (
    pd.pivot_table(
        data=df,
        values="salary_usd",
        index="industry",
        columns="experience_level",
        aggfunc="mean"
    )
    .round(2)
)

salary_by_industry_and_experience

experience_level     Entry       Lead       Mid     Senior
industry
Automotive        61051.24  142421.99  77523.89  104769.24
Consulting        61460.54  142472.67  77919.98  104678.10
Education         61238.68  142953.03  77709.32  103977.99
Energy            61314.24  141679.03  77194.62  104823.03
Finance           61351.98  141375.37  76508.16  105870.87
Gaming            62563.43  144869.80  77857.74  104502.44
Healthcare        60598.46  142724.59  77601.30  104453.05
Retail            61175.78  143159.13  77614.18  104649.17
Tech              61304.61  139977.06  76678.37  104220.31
Telecom           61160.98  141588.87  77505.36  104151.10

## 7.4 Salary Analysis by Education and Experience Level

In [509]:
# Compare average salary across industry and experience levels

salary_by_education_and_experience = (
    pd.pivot_table(
        data=df,
        values="salary_usd",
        index="education_required",
        columns="experience_level",
        aggfunc="mean"
    )
    .round(2)
)

salary_by_education_and_experience

experience_level       Entry       Lead       Mid     Senior
education_required
Bachelor            61428.39  143653.95  77742.49  104644.07
Bootcamp            61949.24  142783.17  77736.59  104336.02
Diploma             60796.25  142241.02  77506.85  104182.94
Master              61080.51  142043.15  77034.50  105183.29
Phd                 61372.05  140856.08  77050.54  104702.38

## 7.2 Analyze Salary Across Country-Based Combinations

Evaluate how salary varies when combining countries with AI specializations and industries.

In [510]:
# Compare average salary across country-based combinations

salary_by_country_and_specialization = (
    pd.pivot_table(
        data=df,
        values="salary_usd",
        index="country",
        columns="ai_specialization",
        aggfunc="mean"
    )
    .round(2)
)

salary_by_country_and_specialization

ai_specialization,Analytics,Computer Vision,Forecasting,Generative AI,LLM,MLOps,NLP,Reinforcement Learning
country,,,,,,,,
Australia,110618.48,111479.51,110269.31,111067.69,112462.48,108997.73,109045.84,110558.63
Brazil,53522.72,53728.33,53976.30,53819.39,53739.62,53326.61,54093.82,53451.06
Canada,109485.17,110303.60,107727.62,107085.18,110337.73,110862.64,107222.30,106271.89
France,95939.56,95942.63,92741.60,96344.88,94124.61,95801.22,95728.12,94794.24
Germany,100491.66,99819.93,100496.68,101980.56,99289.64,100885.03,99074.58,97953.52
India,43725.51,42882.27,43076.48,42666.96,43237.72,42707.25,43413.74,43129.88
Japan,97684.23,98894.48,97503.90,99403.49,98315.55,99382.50,99148.53,97744.53
Netherlands,103011.65,102719.40,104409.61,99846.80,103980.99,100246.23,101921.33,102713.48
Singapore,115824.21,116392.82,116331.21,118477.12,116965.73,117344.72,116751.47,117490.50
UAE,93447.62,94324.71,91827.43,92784.78,93772.77,95245.05,92612.27,93958.80
UK,102428.26,102792.41,101620.80,103192.32,103766.65,104967.15,104315.32,99842.93
USA,134394.80,131507.08,132859.07,136069.58,132729.84,131579.53,133882.68,131098.96

In [511]:
salary_by_country_and_industry = (
    pd.pivot_table(
        data=df,
        values="salary_usd",
        index="country",
        columns="industry",
        aggfunc="mean"
    )
    .round(2)
)

salary_by_country_and_industry

industry,Automotive,Consulting,Education,Energy,Finance,Gaming,Healthcare,Retail,Tech,Telecom
country,,,,,,,,,,
Australia,108351.88,110208.74,111098.09,109099.13,111651.54,110370.78,110603.37,111220.93,113321.49,109469.10
Brazil,52879.29,53933.81,54676.32,52966.06,54023.90,53584.17,52274.03,53700.68,54777.66,54159.45
Canada,107698.43,108274.23,110038.98,106779.13,106802.44,110040.30,108941.19,110492.66,108964.02,108280.92
France,97618.66,94107.04,95648.33,94353.23,96363.09,92934.25,93709.99,96200.12,95668.32,94933.45
Germany,100365.97,99260.63,99019.84,100305.02,98509.57,99779.36,101178.39,100775.88,102951.91,98150.83
India,43755.83,43461.82,43148.27,42518.73,42451.88,42253.68,43364.75,42730.28,44230.96,43040.48
Japan,97632.16,99805.99,99556.15,99767.05,98399.55,100155.58,96384.90,99160.08,96455.47,97831.19
Netherlands,104372.76,100136.39,104191.54,100696.93,101516.08,103917.11,101917.78,102293.75,102502.97,101922.86
Singapore,118981.91,118256.02,112573.05,116671.99,116567.33,118523.74,116758.76,117052.13,116647.62,116917.77
UAE,92463.84,93618.42,93474.68,92972.53,93001.49,92680.93,94691.55,94373.74,95876.06,91985.68
UK,103475.66,106250.73,102142.43,102159.11,103315.36,102309.53,101665.22,103446.78,100693.89,102895.67
USA,134307.74,131556.42,134607.19,130860.66,133905.09,130379.37,133239.32,133188.14,135208.78,133331.41

## 7.3 Analyze Salary by Experience Level and Work Mode

Compare compensation across onsite, hybrid, and remote work arrangements for different experience levels.

In [512]:
# Compare average salary by experience level and work mode

salary_by_experience_and_work_mode = (
    pd.pivot_table(
        data=df,
        values="salary_usd",
        index="experience_level",
        columns="work_mode",
        aggfunc="mean"
    )
    .round(2)
)

salary_by_experience_and_work_mode

work_mode            Hybrid     Onsite     Remote
experience_level
Entry              61553.01   61330.30   61101.72
Lead              142009.32  142169.64  142784.02
Mid                77689.50   76967.12   77586.01
Senior            104965.40  104492.81  104372.44

## 7.4 Perform Three-Factor Salary Analysis

Identify the highest-paying combinations by simultaneously analyzing country, experience level, and AI specialization.

In [513]:
# Calculate average salary by country, experience level, and AI specialization

salary_by_country_experience_specialization = (
    df.groupby(
        [
            "country",
            "experience_level",
            "ai_specialization"
        ]
    )["salary_usd"]
    .mean()
    .round(2)
    .sort_values(ascending=False)
)

salary_by_country_experience_specialization.head(30)

country    experience_level  ai_specialization
USA        Lead              LLM                       202592.26
                             Analytics                 199154.46
                             Computer Vision           197418.77
                             Generative AI             196992.64
                             MLOps                     196553.76
                             NLP                       196411.33
                             Reinforcement Learning    196233.22
                             Forecasting               194212.33
Singapore  Lead              LLM                       175767.76
                             Analytics                 174588.01
                             Generative AI             174112.23
                             Forecasting               172058.87
                             NLP                       171703.64
                             Reinforcement Learning    171431.75
                             MLOps                     170831.34
                             Computer Vision           170263.43
Australia  Lead              Analytics                 169584.99
Canada     Lead              MLOps                     164748.36
Australia  Lead              Reinforcement Learning    164178.33
                             Generative AI             163658.65
                             Computer Vision           163634.43
                             NLP                       162616.87
Canada     Lead              Forecasting               162472.29
                             Analytics                 162418.23
Australia  Lead              Forecasting               162224.77
                             LLM                       162184.95
                             MLOps                     161700.95
Canada     Lead              LLM                       161276.21
                             Reinforcement Learning    159841.46
                             Generative AI             158183.18
Name: salary_usd, dtype: float64

## 7.5 Perform Three-Factor Compensation Analysis

Identify the highest-paying country, job role, and experience level combinations based on total compensation.

In [514]:
# Calculate average total compensation by country, job role, and experience level

compensation_by_country_job_role_experience = (
    df.groupby(
        [
            "country",
            "job_role",
            "experience_level"
        ]
    )["total_compensation"]
    .mean()
    .round(2)
    .sort_values(ascending=False)
)

compensation_by_country_job_role_experience.head(25)

country      job_role                   experience_level
USA          Research Scientist         Lead                255541.23
             Machine Learning Engineer  Lead                237819.87
             Computer Vision Engineer   Lead                234778.72
             NLP Engineer               Lead                231738.38
             AI Engineer                Lead                226040.21
             AI Software Engineer       Lead                224106.94
Singapore    Research Scientist         Lead                223795.87
USA          Data Scientist             Lead                219001.36
Canada       Research Scientist         Lead                213876.02
Australia    Research Scientist         Lead                209011.14
Singapore    Computer Vision Engineer   Lead                208719.08
             Machine Learning Engineer  Lead                208498.19
             AI Engineer                Lead                198677.14
             NLP Engineer               Lead                198437.07
UK           Research Scientist         Lead                198002.21
Singapore    AI Software Engineer       Lead                196836.61
Australia    Computer Vision Engineer   Lead                196229.72
             Machine Learning Engineer  Lead                194824.28
Netherlands  Research Scientist         Lead                193905.55
Canada       Computer Vision Engineer   Lead                192036.59
Singapore    Data Scientist             Lead                191795.84
Australia    AI Engineer                Lead                191333.87
Canada       Machine Learning Engineer  Lead                191320.28
Australia    NLP Engineer               Lead                191251.39
Germany      Research Scientist         Lead                187584.32
Name: total_compensation, dtype: float64

## Level 8: Feature Engineering & Workforce Metrics

## Objective

Create meaningful workforce metrics by engineering new features from existing data. These features improve business analysis, support predictive modeling, and demonstrate practical feature engineering skills used in AI Engineering and Data Science.

## 8.1 Engineer Compensation-Based Metrics

Create new compensation metrics to better understand bonus contribution, compensation growth, and salary efficiency.

In [515]:
# Create bonus percentage for each job posting

df["bonus_percentage"] = (
    (df["bonus_usd"] / df["salary_usd"]) * 100
).round(2)

# Review the distribution of bonus percentage

bonus_percentage_summary = (
    df["bonus_percentage"]
    .describe()
    .round(2)
)

bonus_percentage_summary

count    90000.00
mean        13.50
std          4.90
min          5.00
25%          9.26
50%         13.49
75%         17.74
max         22.00
Name: bonus_percentage, dtype: float64

In [516]:
# Create the total compensation multiplier

df["compensation_multiplier"] = (
    df["total_compensation"] / df["salary_usd"]
).round(3)

# Review the distribution of compensation multiplier

compensation_multiplier_summary = (
    df["compensation_multiplier"]
    .describe()
    .round(3)
)

compensation_multiplier_summary

count    90000.000
mean         1.135
std          0.049
min          1.050
25%          1.093
50%          1.135
75%          1.177
max          1.220
Name: compensation_multiplier, dtype: float64

In [517]:
# Calculate salary earned per year of professional experience

df["salary_per_experience_year"] = np.where(
    df["experience_years"] == 0,
    df["salary_usd"],
    (df["salary_usd"] / df["experience_years"]).round(2)
)

# Review the distribution of salary per experience year

salary_per_experience_year_summary = (
    df["salary_per_experience_year"]
    .describe()
    .round(2)
)

salary_per_experience_year_summary

count     90000.00
mean      26738.04
std       23192.41
min        2201.32
25%       10464.69
50%       15918.94
75%       35733.00
max      119807.00
Name: salary_per_experience_year, dtype: float64

## 8.2 Engineer Salary Value Metrics

Develop workforce metrics that measure salary value relative to market demand and overall compensation ranking.

In [518]:
# Create the salary demand ratio

df["salary_demand_ratio"] = (
    df["salary_usd"] /
    df["skill_demand_score"]
).round(2)

# Review the distribution of the salary demand ratio

salary_demand_ratio_summary = (
    df["salary_demand_ratio"]
    .describe()
    .round(2)
)

salary_demand_ratio_summary

count     90000.00
mean       5026.59
std       12732.33
min         280.00
25%        1119.74
50%        1901.64
75%        3807.03
max      268508.00
Name: salary_demand_ratio, dtype: float64

In [519]:
# Create the compensation score using percentile ranking

df["compensation_score"] = (
    (
        df["salary_usd"] +
        df["bonus_usd"]
    )
    .rank(pct=True)
    .round(4)
)

# Review the distribution of the compensation score

compensation_score_summary = (
    df["compensation_score"]
    .describe()
    .round(4)
)

compensation_score_summary

count    90000.0000
mean         0.5000
std          0.2887
min          0.0000
25%          0.2500
50%          0.5000
75%          0.7500
max          1.0000
Name: compensation_score, dtype: float64

# 02 Career Growth Intelligence

# Module 2: Career Growth Intelligence

## Objective

Analyze the key factors that influence career progression, promotion speed, and long-term professional growth within the AI workforce.

### Business Questions

- Does experience improve career growth?
- Which AI specializations have the highest career growth?
- Which countries provide the best career opportunities?
- Which job roles offer faster promotions?
- Does salary influence career growth?
- Which factors contribute most to promotion speed?

## Career Growth Overview

**Business Question:** Analyze **career growth overview** to identify meaningful workforce trends and support career growth insights.

In [520]:
# Career Growth Overview

df[[
    "career_growth_score",
    "promotion_speed",
    "salary_percentile"
]].describe().round(2)

       career_growth_score  promotion_speed  salary_percentile
count              90000.0         90000.00           90000.00
mean                  57.2            38.44              50.54
std                   12.9            18.43              28.89
min                   25.0            12.00               1.00
25%                   48.0            24.00              25.00
50%                   57.0            37.00              51.00
75%                   66.0            51.00              76.00
max                   99.0            98.00             100.00

## Career Growth by Experience Level

**Business Question:** Analyze **career growth by experience level** to identify meaningful workforce trends and support career growth insights.

In [521]:
# Career Growth by Experience Level

df.groupby("experience_level")[
    "career_growth_score"
].agg(["mean", "median", "min", "max"]).round(2)

                   mean  median  min  max
experience_level
Entry             57.04    57.0   25   99
Lead              57.33    57.0   25   99
Mid               57.19    57.0   25   99
Senior            57.23    57.0   25   99

## Promotion Speed by Experience Level

**Business Question:** Analyze **promotion speed by experience level** to identify meaningful workforce trends and support career growth insights.

In [522]:
# Promotion Speed by Experience Level

df.groupby("experience_level")[
    "promotion_speed"
].agg(["mean", "median", "min", "max"]).round(2)

                   mean  median  min  max
experience_level
Entry             31.20    29.0   12   98
Lead              48.14    47.0   12   98
Mid               34.38    32.0   12   98
Senior            39.93    38.0   12   98

## Career Growth by Experience Years

**Business Question:** Analyze **career growth by experience years** to identify meaningful workforce trends and support career growth insights.

In [523]:
# Career Growth by Experience Years

df.groupby("experience_years")[
    "career_growth_score"
].mean().round(2)

experience_years
0     56.96
1     57.12
2     57.06
3     57.40
4     57.24
5     57.06
6     56.99
7     57.35
8     57.34
9     57.24
10    57.42
11    57.07
12    57.49
13    57.32
14    57.31
15    57.01
16    57.45
17    57.55
18    57.13
19    57.38
Name: career_growth_score, dtype: float64

## Career Growth by Country

**Business Question:** Analyze **career growth by country** to identify meaningful workforce trends and support career growth insights.

In [524]:
# Career Growth by Country

df.groupby("country")[
    "career_growth_score"
].mean().sort_values(ascending=False).round(2)

country
India          57.38
UAE            57.29
Singapore      57.29
Brazil         57.29
Australia      57.28
UK             57.24
Germany        57.22
Netherlands    57.18
Japan          57.15
Canada         57.08
USA            57.06
France         56.93
Name: career_growth_score, dtype: float64

## Career Growth by Job Role

**Business Question:** Analyze **career growth by job role** to identify meaningful workforce trends and support career growth insights.

In [525]:
# Career Growth by Job Role

df.groupby("job_role")[
    "career_growth_score"
].mean().sort_values(ascending=False).round(2)

job_role
AI Engineer                  57.30
Computer Vision Engineer     57.28
Research Scientist           57.28
NLP Engineer                 57.27
Data Scientist               57.24
Data Analyst                 57.17
AI Software Engineer         57.14
Machine Learning Engineer    56.91
Name: career_growth_score, dtype: float64

## Career Growth by AI Specialization

**Business Question:** Analyze **career growth by ai specialization** to identify meaningful workforce trends and support career growth insights.

In [526]:
# Career Growth by AI Specialization

df.groupby("ai_specialization")[
    "career_growth_score"
].mean().sort_values(ascending=False).round(2)

ai_specialization
LLM                       57.33
Generative AI             57.31
Analytics                 57.27
Reinforcement Learning    57.19
MLOps                     57.18
NLP                       57.14
Forecasting               57.10
Computer Vision           57.07
Name: career_growth_score, dtype: float64

## Promotion Speed by Job Role

**Business Question:** Analyze **promotion speed by job role** to identify meaningful workforce trends and support career growth insights.

In [527]:
# Promotion Speed by Job Role

df.groupby("job_role")[
    "promotion_speed"
].mean().sort_values(ascending=False).round(2)

job_role
AI Software Engineer         38.72
NLP Engineer                 38.64
Computer Vision Engineer     38.55
Data Scientist               38.47
AI Engineer                  38.43
Machine Learning Engineer    38.34
Data Analyst                 38.22
Research Scientist           38.15
Name: promotion_speed, dtype: float64

## Promotion Speed by AI Specialization

**Business Question:** Analyze **promotion speed by ai specialization** to identify meaningful workforce trends and support career growth insights.

In [528]:
# Promotion Speed by AI Specialization

df.groupby("ai_specialization")[
    "promotion_speed"
].mean().sort_values(ascending=False).round(2)

ai_specialization
Generative AI             38.68
LLM                       38.65
NLP                       38.54
Reinforcement Learning    38.50
MLOps                     38.43
Forecasting               38.33
Computer Vision           38.21
Analytics                 38.20
Name: promotion_speed, dtype: float64

## Salary Percentile by Experience Level

**Business Question:** Analyze **salary percentile by experience level** to identify meaningful workforce trends and support career growth insights.

In [529]:
# Salary Percentile by Experience Level

df.groupby("experience_level")[
    "salary_percentile"
].mean().round(2)

experience_level
Entry     50.69
Lead      50.34
Mid       50.51
Senior    50.62
Name: salary_percentile, dtype: float64

# Career Growth Intelligence - Ranking & Elite Segment Analysis

This notebook section contains ranking analysis, percentile analysis, and elite workforce segmentation for Career Growth Intelligence. Each business question is organized into its own markdown and code cell.

## Top 10 Countries by Career Growth Score

**Business Question:** Analyze **top 10 countries by career growth score** to identify high-performing segments, benchmark workforce performance, and support strategic career growth decisions.

In [530]:
# Top 10 Countries by Career Growth Score

df.groupby("country")[
    "career_growth_score"
].mean().sort_values(ascending=False).head(10).round(2)

country
India          57.38
UAE            57.29
Singapore      57.29
Brazil         57.29
Australia      57.28
UK             57.24
Germany        57.22
Netherlands    57.18
Japan          57.15
Canada         57.08
Name: career_growth_score, dtype: float64

## Bottom 10 Countries by Career Growth Score

**Business Question:** Analyze **bottom 10 countries by career growth score** to identify high-performing segments, benchmark workforce performance, and support strategic career growth decisions.

In [531]:
# Bottom 10 Countries by Career Growth Score

df.groupby("country")[
    "career_growth_score"
].mean().sort_values().head(10).round(2)

country
France         56.93
USA            57.06
Canada         57.08
Japan          57.15
Netherlands    57.18
Germany        57.22
UK             57.24
Australia      57.28
Brazil         57.29
Singapore      57.29
Name: career_growth_score, dtype: float64

## Top 10 Job Roles by Career Growth Score

**Business Question:** Analyze **top 10 job roles by career growth score** to identify high-performing segments, benchmark workforce performance, and support strategic career growth decisions.

In [532]:
# Top 10 Job Roles by Career Growth Score

df.groupby("job_role")[
    "career_growth_score"
].mean().sort_values(ascending=False).head(10).round(2)

job_role
AI Engineer                  57.30
Computer Vision Engineer     57.28
Research Scientist           57.28
NLP Engineer                 57.27
Data Scientist               57.24
Data Analyst                 57.17
AI Software Engineer         57.14
Machine Learning Engineer    56.91
Name: career_growth_score, dtype: float64

## Top 10 AI Specializations by Career Growth Score

**Business Question:** Analyze **top 10 ai specializations by career growth score** to identify high-performing segments, benchmark workforce performance, and support strategic career growth decisions.

In [533]:
# Top 10 AI Specializations by Career Growth Score

df.groupby("ai_specialization")[
    "career_growth_score"
].mean().sort_values(ascending=False).head(10).round(2)

ai_specialization
LLM                       57.33
Generative AI             57.31
Analytics                 57.27
Reinforcement Learning    57.19
MLOps                     57.18
NLP                       57.14
Forecasting               57.10
Computer Vision           57.07
Name: career_growth_score, dtype: float64

## Promotion Speed by Experience Level

**Business Question:** Analyze **promotion speed by experience level** to identify high-performing segments, benchmark workforce performance, and support strategic career growth decisions.

In [534]:
# Promotion Speed by Experience Level

df.groupby("experience_level")[
    "promotion_speed"
].mean().sort_values(ascending=False).round(2)

experience_level
Lead      48.14
Senior    39.93
Mid       34.38
Entry     31.20
Name: promotion_speed, dtype: float64

## Top 10 Experience Years by Career Growth Score

**Business Question:** Analyze **top 10 experience years by career growth score** to identify high-performing segments, benchmark workforce performance, and support strategic career growth decisions.

In [535]:
# Top 10 Experience Years by Career Growth Score

df.groupby("experience_years")[
    "career_growth_score"
].mean().sort_values(ascending=False).head(10).round(2)

experience_years
17    57.55
12    57.49
16    57.45
10    57.42
3     57.40
19    57.38
7     57.35
8     57.34
13    57.32
14    57.31
Name: career_growth_score, dtype: float64

## Career Growth Score Quartiles

**Business Question:** Analyze **career growth score quartiles** to identify high-performing segments, benchmark workforce performance, and support strategic career growth decisions.

In [536]:
# Career Growth Score Quartiles

df["career_growth_score"].quantile(
    [0.25, 0.50, 0.75]
).round(2)

0.25    48.0
0.50    57.0
0.75    66.0
Name: career_growth_score, dtype: float64

## Promotion Speed Quartiles

**Business Question:** Analyze **promotion speed quartiles** to identify high-performing segments, benchmark workforce performance, and support strategic career growth decisions.

In [537]:
# Promotion Speed Quartiles

df["promotion_speed"].quantile(
    [0.25, 0.50, 0.75]
).round(2)

0.25    24.0
0.50    37.0
0.75    51.0
Name: promotion_speed, dtype: float64

## Salary Percentile Quartiles

**Business Question:** Analyze **salary percentile quartiles** to identify high-performing segments, benchmark workforce performance, and support strategic career growth decisions.

In [538]:
# Salary Percentile Quartiles

df["salary_percentile"].quantile(
    [0.25, 0.50, 0.75]
).round(2)

0.25    25.0
0.50    51.0
0.75    76.0
Name: salary_percentile, dtype: float64

## Top 10% Career Growth Professionals

**Business Question:** Analyze **top 10% career growth professionals** to identify high-performing segments, benchmark workforce performance, and support strategic career growth decisions.

In [539]:
# Top 10% Career Growth Professionals

career_growth_top_10 = (
    df[
        df["career_growth_score"] >=
        df["career_growth_score"].quantile(0.90)
    ]
)

career_growth_top_10.head()

,id,country,job_role,ai_specialization,experience_level,experience_years,salary_usd,bonus_usd,education_required,industry,company_size,interview_rounds,year,work_mode,weekly_hours,company_rating,job_openings,hiring_difficulty_score,layoff_risk,ai_adoption_score,company_funding_billion,economic_index,ai_maturity_years,offer_acceptance_rate,tax_rate_percent,vacation_days,skill_demand_score,automation_risk,job_security_score,career_growth_score,work_life_balance_score,promotion_speed,salary_percentile,cost_of_living_index,employee_satisfaction,salary_quartile,total_compensation,career_stage,bonus_percentage,compensation_multiplier,salary_per_experience_year,salary_demand_ratio,compensation_score
26,27,UK,Research Scientist,NLP,Entry,1,67130,13519,Phd,Finance,Enterprise,4,2022,Onsite,37.7,4.78,25,54.86,0.297,95,5.20,78.32,6,64.49,15.1,20,27,88,78,76,98,12,82,0.81,82,Mid,80649,Early Career,20.14,1.201,67130.00,2486.30,0.3252
27,28,France,Computer Vision Engineer,Generative AI,Senior,9,126464,8212,Phd,Tech,Startup,2,2023,Remote,51.6,3.38,19,87.31,0.175,83,6.88,78.58,8,66.55,29.4,14,82,34,60,86,49,46,21,0.81,72,Best,134676,Experienced,6.49,1.065,14051.56,1542.24,0.7222
31,32,Germany,Research Scientist,LLM,Mid,3,89465,10234,Diploma,Finance,Large,3,2026,Remote,45.2,3.94,10,100.00,0.216,100,4.00,97.10,10,61.13,29.6,21,40,30,82,83,71,27,29,1.51,68,High,99699,Developing,11.44,1.114,29821.67,2236.62,0.5026
42,43,Germany,Research Scientist,Forecasting,Lead,14,180739,9690,Bachelor,Retail,Medium,7,2023,Hybrid,45.1,4.34,13,80.37,0.084,86,6.04,77.40,6,66.09,39.3,18,43,41,92,79,68,38,70,0.59,79,Best,190429,Expert,5.36,1.054,12909.93,4203.23,0.9210
46,47,UK,AI Engineer,LLM,Lead,15,172678,34093,Bachelor,Education,Enterprise,7,2026,Hybrid,47.8,3.51,26,76.05,0.121,79,7.20,49.63,5,68.06,28.8,24,24,7,83,76,70,21,34,0.73,84,Best,206771,Expert,19.74,1.197,11511.87,7194.92,0.9531

## Top 5% Career Growth Professionals

**Business Question:** Analyze **top 5% career growth professionals** to identify high-performing segments, benchmark workforce performance, and support strategic career growth decisions.

In [540]:
# Top 5% Career Growth Professionals

career_growth_top_5 = (
    df[
        df["career_growth_score"] >=
        df["career_growth_score"].quantile(0.95)
    ]
)

career_growth_top_5.head()

,id,country,job_role,ai_specialization,experience_level,experience_years,salary_usd,bonus_usd,education_required,industry,company_size,interview_rounds,year,work_mode,weekly_hours,company_rating,job_openings,hiring_difficulty_score,layoff_risk,ai_adoption_score,company_funding_billion,economic_index,ai_maturity_years,offer_acceptance_rate,tax_rate_percent,vacation_days,skill_demand_score,automation_risk,job_security_score,career_growth_score,work_life_balance_score,promotion_speed,salary_percentile,cost_of_living_index,employee_satisfaction,salary_quartile,total_compensation,career_stage,bonus_percentage,compensation_multiplier,salary_per_experience_year,salary_demand_ratio,compensation_score
27,28,France,Computer Vision Engineer,Generative AI,Senior,9,126464,8212,Phd,Tech,Startup,2,2023,Remote,51.6,3.38,19,87.31,0.175,83,6.88,78.58,8,66.55,29.4,14,82,34,60,86,49,46,21,0.81,72,Best,134676,Experienced,6.49,1.065,14051.56,1542.24,0.7222
31,32,Germany,Research Scientist,LLM,Mid,3,89465,10234,Diploma,Finance,Large,3,2026,Remote,45.2,3.94,10,100.00,0.216,100,4.00,97.10,10,61.13,29.6,21,40,30,82,83,71,27,29,1.51,68,High,99699,Developing,11.44,1.114,29821.67,2236.62,0.5026
42,43,Germany,Research Scientist,Forecasting,Lead,14,180739,9690,Bachelor,Retail,Medium,7,2023,Hybrid,45.1,4.34,13,80.37,0.084,86,6.04,77.40,6,66.09,39.3,18,43,41,92,79,68,38,70,0.59,79,Best,190429,Expert,5.36,1.054,12909.93,4203.23,0.9210
52,53,Canada,NLP Engineer,Generative AI,Senior,6,114541,22686,Master,Consulting,Small,7,2026,Onsite,37.5,4.24,26,45.37,0.125,80,8.52,71.36,13,79.63,21.9,18,79,69,83,86,93,26,100,1.44,83,High,137227,Experienced,19.81,1.198,19090.17,1449.89,0.7343
53,54,Netherlands,Computer Vision Engineer,Analytics,Lead,16,141862,26137,Master,Education,Medium,2,2024,Hybrid,40.3,4.55,31,62.85,0.079,100,9.47,79.58,10,84.41,35.0,17,97,60,86,92,80,28,73,1.51,81,Best,167999,Expert,18.42,1.184,8866.38,1462.49,0.8590

## Top 1% Career Growth Professionals

**Business Question:** Analyze **top 1% career growth professionals** to identify high-performing segments, benchmark workforce performance, and support strategic career growth decisions.

In [541]:
# Top 1% Career Growth Professionals

career_growth_top_1 = (
    df[
        df["career_growth_score"] >=
        df["career_growth_score"].quantile(0.99)
    ]
)

career_growth_top_1.head()

,id,country,job_role,ai_specialization,experience_level,experience_years,salary_usd,bonus_usd,education_required,industry,company_size,interview_rounds,year,work_mode,weekly_hours,company_rating,job_openings,hiring_difficulty_score,layoff_risk,ai_adoption_score,company_funding_billion,economic_index,ai_maturity_years,offer_acceptance_rate,tax_rate_percent,vacation_days,skill_demand_score,automation_risk,job_security_score,career_growth_score,work_life_balance_score,promotion_speed,salary_percentile,cost_of_living_index,employee_satisfaction,salary_quartile,total_compensation,career_stage,bonus_percentage,compensation_multiplier,salary_per_experience_year,salary_demand_ratio,compensation_score
27,28,France,Computer Vision Engineer,Generative AI,Senior,9,126464,8212,Phd,Tech,Startup,2,2023,Remote,51.6,3.38,19,87.31,0.175,83,6.88,78.58,8,66.55,29.4,14,82,34,60,86,49,46,21,0.81,72,Best,134676,Experienced,6.49,1.065,14051.56,1542.24,0.7222
52,53,Canada,NLP Engineer,Generative AI,Senior,6,114541,22686,Master,Consulting,Small,7,2026,Onsite,37.5,4.24,26,45.37,0.125,80,8.52,71.36,13,79.63,21.9,18,79,69,83,86,93,26,100,1.44,83,High,137227,Experienced,19.81,1.198,19090.17,1449.89,0.7343
53,54,Netherlands,Computer Vision Engineer,Analytics,Lead,16,141862,26137,Master,Education,Medium,2,2024,Hybrid,40.3,4.55,31,62.85,0.079,100,9.47,79.58,10,84.41,35.0,17,97,60,86,92,80,28,73,1.51,81,Best,167999,Expert,18.42,1.184,8866.38,1462.49,0.8590
124,125,Australia,AI Software Engineer,MLOps,Mid,4,81521,17090,Diploma,Consulting,Enterprise,3,2021,Onsite,43.3,3.21,19,45.98,0.108,92,8.91,68.85,6,58.71,34.5,19,61,25,84,86,84,15,48,2.33,80,Mid,98611,Developing,20.96,1.210,20380.25,1336.41,0.4942
134,135,UK,Data Scientist,MLOps,Entry,1,70233,4650,Master,Consulting,Startup,2,2026,Remote,42.7,4.16,27,100.00,0.297,97,6.50,80.98,3,90.57,29.4,20,40,66,56,87,71,38,51,1.76,66,Mid,74883,Early Career,6.62,1.066,70233.00,1755.82,0.2662

# Career Growth Intelligence - Multi-Factor Analysis

This notebook section explores relationships between multiple workforce variables using correlation analysis, pivot tables, and cross-tabulations. Each analysis answers a specific business question and is organized into separate markdown and code cells.

## Correlation with Career Growth Score

**Business Question:** Analyze **correlation with career growth score** to uncover multi-dimensional workforce patterns and support data-driven career growth decisions.

In [542]:
# Correlation with Career Growth Score

career_growth_corr = (
    df[[
        "career_growth_score",
        "promotion_speed",
        "salary_percentile",
        "experience_years",
        "salary_usd",
        "bonus_usd",
        "company_rating",
        "skill_demand_score",
        "job_security_score",
        "work_life_balance_score",
        "employee_satisfaction"
    ]]
    .corr()["career_growth_score"]
    .sort_values(ascending=False)
    .round(2)
)

career_growth_corr

career_growth_score        1.00
job_security_score         0.06
employee_satisfaction      0.01
experience_years           0.01
promotion_speed            0.01
bonus_usd                  0.00
salary_usd                 0.00
skill_demand_score         0.00
salary_percentile         -0.00
company_rating            -0.00
work_life_balance_score   -0.01
Name: career_growth_score, dtype: float64

## Average Career Growth by Country and Experience Level

**Business Question:** Analyze **average career growth by country and experience level** to uncover multi-dimensional workforce patterns and support data-driven career growth decisions.

In [543]:
# Average Career Growth by Country and Experience Level

pd.pivot_table(
    df,
    values="career_growth_score",
    index="country",
    columns="experience_level",
    aggfunc="mean"
).round(2)

experience_level  Entry   Lead    Mid  Senior
country
Australia         57.14  57.28  57.16   57.55
Brazil            57.23  57.60  57.16   57.15
Canada            56.54  57.40  57.33   57.04
France            56.48  57.03  57.17   57.07
Germany           57.10  57.35  57.11   57.30
India             57.09  57.58  57.44   57.42
Japan             57.05  57.30  57.07   57.16
Netherlands       57.30  57.29  56.69   57.45
Singapore         57.30  57.46  57.36   57.06
UAE               57.39  57.04  57.26   57.49
UK                56.74  57.62  57.35   57.25
USA               57.18  56.99  57.18   56.88

## Average Career Growth by AI Specialization and Experience Level

**Business Question:** Analyze **average career growth by ai specialization and experience level** to uncover multi-dimensional workforce patterns and support data-driven career growth decisions.

In [544]:
# Average Career Growth by AI Specialization and Experience Level

pd.pivot_table(
    df,
    values="career_growth_score",
    index="ai_specialization",
    columns="experience_level",
    aggfunc="mean"
).round(2)

experience_level        Entry   Lead    Mid  Senior
ai_specialization
Analytics               57.08  57.14  57.59   57.24
Computer Vision         56.71  57.15  57.11   57.29
Forecasting             57.21  57.02  57.04   57.12
Generative AI           57.12  57.48  57.19   57.43
LLM                     57.40  57.23  57.07   57.62
MLOps                   57.12  57.42  57.21   56.97
NLP                     56.64  57.73  57.14   57.06
Reinforcement Learning  57.04  57.46  57.15   57.12

## Average Career Growth by Job Role and Experience Level

**Business Question:** Analyze **average career growth by job role and experience level** to uncover multi-dimensional workforce patterns and support data-driven career growth decisions.

In [545]:
# Average Career Growth by Job Role and Experience Level

pd.pivot_table(
    df,
    values="career_growth_score",
    index="job_role",
    columns="experience_level",
    aggfunc="mean"
).round(2)

experience_level           Entry   Lead    Mid  Senior
job_role
AI Engineer                57.09  57.63  57.36   57.12
AI Software Engineer       57.25  57.14  56.85   57.29
Computer Vision Engineer   56.72  57.89  57.51   57.01
Data Analyst               57.37  56.98  56.84   57.47
Data Scientist             57.14  57.42  57.16   57.25
Machine Learning Engineer  56.80  56.77  56.95   57.13
NLP Engineer               56.94  57.51  57.26   57.36
Research Scientist         57.04  57.27  57.58   57.23

## Average Promotion Speed by AI Specialization

**Business Question:** Analyze **average promotion speed by ai specialization** to uncover multi-dimensional workforce patterns and support data-driven career growth decisions.

In [546]:
# Average Promotion Speed by AI Specialization

pd.pivot_table(
    df,
    values="promotion_speed",
    index="ai_specialization",
    columns="experience_level",
    aggfunc="mean"
).round(2)

experience_level        Entry   Lead    Mid  Senior
ai_specialization
Analytics               30.51  48.26  34.28   39.81
Computer Vision         30.81  47.87  33.94   39.75
Forecasting             31.44  47.99  34.34   39.71
Generative AI           31.77  48.69  34.01   39.90
LLM                     31.55  48.69  34.28   39.69
MLOps                   31.30  47.44  34.69   40.19
NLP                     31.02  47.74  34.94   40.35
Reinforcement Learning  31.22  48.40  34.54   40.07

## Average Salary Percentile by Job Role

**Business Question:** Analyze **average salary percentile by job role** to uncover multi-dimensional workforce patterns and support data-driven career growth decisions.

In [547]:
# Average Salary Percentile by Job Role

pd.pivot_table(
    df,
    values="salary_percentile",
    index="job_role",
    columns="experience_level",
    aggfunc="mean"
).round(2)

experience_level           Entry   Lead    Mid  Senior
job_role
AI Engineer                51.32  50.81  50.38   50.47
AI Software Engineer       50.43  50.50  50.90   50.89
Computer Vision Engineer   50.87  50.11  50.79   50.62
Data Analyst               50.30  49.50  50.86   50.96
Data Scientist             51.31  51.27  50.39   51.10
Machine Learning Engineer  50.26  49.85  50.57   50.12
NLP Engineer               50.75  50.01  50.47   50.97
Research Scientist         50.33  50.68  49.75   49.85

## Career Growth by Country and AI Specialization

**Business Question:** Analyze **career growth by country and ai specialization** to uncover multi-dimensional workforce patterns and support data-driven career growth decisions.

In [548]:
# Career Growth by Country and AI Specialization

pd.crosstab(
    index=df["country"],
    columns=df["ai_specialization"],
    values=df["career_growth_score"],
    aggfunc="mean"
).round(2)

ai_specialization,Analytics,Computer Vision,Forecasting,Generative AI,LLM,MLOps,NLP,Reinforcement Learning
country,,,,,,,,
Australia,57.41,57.36,57.23,57.06,57.58,56.62,57.54,57.48
Brazil,57.66,56.70,57.59,57.41,56.94,57.29,57.19,57.57
Canada,56.86,57.43,56.62,57.12,57.33,56.96,57.08,57.21
France,56.63,57.31,56.77,57.14,56.77,57.23,56.84,56.75
Germany,57.00,56.86,57.79,58.19,56.79,56.72,57.42,56.90
India,57.42,57.23,56.97,57.30,57.74,57.28,57.32,57.76
Japan,57.17,56.60,57.60,57.66,57.35,57.00,57.30,56.60
Netherlands,57.28,57.39,56.28,57.31,57.92,57.97,56.83,56.33
Singapore,58.19,56.94,56.90,57.16,57.02,58.21,56.95,57.06
UAE,57.34,56.71,57.30,57.16,57.89,56.93,56.98,57.99
UK,57.49,57.65,57.37,56.97,57.46,56.57,56.97,57.36
USA,56.73,56.70,56.75,57.26,57.13,57.46,57.28,57.18

## Promotion Speed by Country and Job Role

**Business Question:** Analyze **promotion speed by country and job role** to uncover multi-dimensional workforce patterns and support data-driven career growth decisions.

In [549]:
# Promotion Speed by Country and Job Role

pd.crosstab(
    index=df["country"],
    columns=df["job_role"],
    values=df["promotion_speed"],
    aggfunc="mean"
).round(2)

job_role,AI Engineer,AI Software Engineer,Computer Vision Engineer,Data Analyst,Data Scientist,Machine Learning Engineer,NLP Engineer,Research Scientist
country,,,,,,,,
Australia,38.14,38.60,37.68,38.37,38.53,37.76,38.43,38.35
Brazil,38.65,38.61,39.10,38.05,37.94,38.88,38.40,38.90
Canada,38.46,38.06,38.09,37.24,37.62,37.85,39.25,38.92
France,37.03,39.66,38.74,38.45,38.96,38.80,39.98,37.27
Germany,39.31,39.74,38.17,37.15,38.37,38.21,39.07,37.80
India,38.27,39.29,38.51,38.13,38.68,38.17,38.96,38.58
Japan,39.60,38.15,39.20,38.32,38.03,38.22,38.43,37.31
Netherlands,38.41,38.76,38.13,37.90,39.12,39.10,37.45,38.35
Singapore,38.68,38.36,38.37,39.16,38.46,37.95,38.06,37.48
UAE,38.34,39.29,38.50,38.85,38.92,38.71,38.54,38.37
UK,38.56,38.07,39.69,38.36,38.32,37.97,38.33,38.64
USA,37.59,38.14,38.46,38.77,38.63,38.49,38.80,37.76

# Career Growth Intelligence - Feature Engineering

This notebook section creates engineered workforce metrics to quantify career progression, promotion efficiency, growth potential, and career momentum. Each engineered feature and its analysis is organized into separate markdown and code cells.

## Career Acceleration Index

**Business Question:** Evaluate **career acceleration index** to derive actionable workforce intelligence from engineered career growth metrics and identify high-performing talent segments.

In [550]:
# Career Acceleration Index

df["career_acceleration_index"] = (
    df["career_growth_score"] /
    (df["experience_years"] + 1)
).round(2)

## Promotion Efficiency Index

**Business Question:** Evaluate **promotion efficiency index** to derive actionable workforce intelligence from engineered career growth metrics and identify high-performing talent segments.

In [551]:
# Promotion Efficiency Index

df["promotion_efficiency"] = (
    df["promotion_speed"] /
    (df["experience_years"] + 1)
).round(2)

## Career Momentum Score

**Business Question:** Evaluate **career momentum score** to derive actionable workforce intelligence from engineered career growth metrics and identify high-performing talent segments.

In [552]:
# Career Momentum Score

df["career_momentum_score"] = (
    (
        df["career_growth_score"] +
        df["promotion_speed"] +
        df["salary_percentile"]
    ) / 3
).round(2)

## Growth Potential Index

**Business Question:** Evaluate **growth potential index** to derive actionable workforce intelligence from engineered career growth metrics and identify high-performing talent segments.

In [553]:
# Growth Potential Index

df["growth_potential_index"] = (
    (
        df["career_growth_score"] *
        df["skill_demand_score"]
    ) / 100
).round(2)

## Experience Efficiency Score

**Business Question:** Evaluate **experience efficiency score** to derive actionable workforce intelligence from engineered career growth metrics and identify high-performing talent segments.

In [554]:
# Experience Efficiency Score

df["experience_efficiency_score"] = (
    df["career_growth_score"] /
    (df["experience_years"] + 1)
).round(2)

## Engineered Features Summary

**Business Question:** Evaluate **engineered features summary** to derive actionable workforce intelligence from engineered career growth metrics and identify high-performing talent segments.

In [555]:
# Engineered Features Summary

df[[
    "career_acceleration_index",
    "promotion_efficiency",
    "career_momentum_score",
    "growth_potential_index",
    "experience_efficiency_score"
]].describe().round(2)

,career_acceleration_index,promotion_efficiency,career_momentum_score,growth_potential_index,experience_efficiency_score
count,90000.00,90000.00,90000.00,90000.00,90000.00
mean,16.45,9.61,48.73,28.87,16.45
std,18.00,11.28,12.21,18.13,18.00
min,1.25,0.63,12.67,0.25,1.25
25%,4.45,3.07,39.67,13.72,4.45
50%,8.40,5.25,48.67,27.30,8.40
75%,21.50,11.67,57.33,42.00,21.50
max,99.00,98.00,93.33,93.10,99.00

## Top Career Acceleration

**Business Question:** Evaluate **top career acceleration** to derive actionable workforce intelligence from engineered career growth metrics and identify high-performing talent segments.

In [556]:
# Top Career Acceleration

df.nlargest(
    10,
    "career_acceleration_index"
)[[
    "job_role",
    "country",
    "career_acceleration_index"
]]

                        job_role    country  career_acceleration_index
38858  Machine Learning Engineer        UAE                       99.0
32505                AI Engineer  Australia                       97.0
35601         Research Scientist  Singapore                       97.0
2626        AI Software Engineer     Brazil                       96.0
11754               NLP Engineer  Singapore                       96.0
20016             Data Scientist        USA                       96.0
35110               Data Analyst     Brazil                       95.0
63117               NLP Engineer      Japan                       95.0
72137               NLP Engineer         UK                       95.0
19758                AI Engineer        USA                       94.0

## Top Career Momentum

**Business Question:** Evaluate **top career momentum** to derive actionable workforce intelligence from engineered career growth metrics and identify high-performing talent segments.

In [557]:
# Top Career Momentum

df.nlargest(
    10,
    "career_momentum_score"
)[[
    "job_role",
    "country",
    "career_momentum_score"
]]

                        job_role    country  career_momentum_score
74727             Data Scientist  Australia                  93.33
32446       AI Software Engineer  Singapore                  91.33
40818             Data Scientist         UK                  91.33
84670  Machine Learning Engineer        UAE                  90.00
78404       AI Software Engineer     France                  89.67
33827               NLP Engineer        USA                  89.33
79881             Data Scientist        USA                  89.33
5110          Research Scientist     Brazil                  89.00
27508                AI Engineer        USA                  88.67
35986   Computer Vision Engineer    Germany                  88.67

## Highest Growth Potential

**Business Question:** Evaluate **highest growth potential** to derive actionable workforce intelligence from engineered career growth metrics and identify high-performing talent segments.

In [558]:
# Highest Growth Potential

df.nlargest(
    10,
    "growth_potential_index"
)[[
    "job_role",
    "country",
    "growth_potential_index"
]]

                        job_role      country  growth_potential_index
6644              Data Scientist        India                   93.10
78391  Machine Learning Engineer  Netherlands                   93.10
35351             Data Scientist           UK                   92.00
78571             Data Scientist       France                   91.00
55405  Machine Learning Engineer    Australia                   90.09
53      Computer Vision Engineer  Netherlands                   89.24
2776   Machine Learning Engineer    Singapore                   89.10
10989         Research Scientist       Brazil                   89.10
33468                AI Engineer       Canada                   89.10
89422             Data Scientist           UK                   89.10

## Correlation of Engineered Features

**Business Question:** Evaluate **correlation of engineered features** to derive actionable workforce intelligence from engineered career growth metrics and identify high-performing talent segments.

In [559]:
# Correlation of Engineered Features

df[[
    "career_growth_score",
    "promotion_speed",
    "career_acceleration_index",
    "promotion_efficiency",
    "career_momentum_score",
    "growth_potential_index",
    "experience_efficiency_score"
]].corr().round(2)

,career_growth_score,promotion_speed,career_acceleration_index,promotion_efficiency,career_momentum_score,growth_potential_index,experience_efficiency_score
career_growth_score,1.00,0.01,0.20,-0.00,0.35,0.36,0.20
promotion_speed,0.01,1.00,-0.25,0.18,0.51,-0.00,-0.25
career_acceleration_index,0.20,-0.25,1.00,0.76,-0.05,0.07,1.00
promotion_efficiency,-0.00,0.18,0.76,1.00,0.09,-0.01,0.76
career_momentum_score,0.35,0.51,-0.05,0.09,1.00,0.12,-0.05
growth_potential_index,0.36,-0.00,0.07,-0.01,0.12,1.00,0.07
experience_efficiency_score,0.20,-0.25,1.00,0.76,-0.05,0.07,1.00

# 03 Workforce Risk Intelligence

# Module 3: Workforce Risk Intelligence

## Objective

Analyze workforce stability, layoff risk, automation risk, AI adoption, and job security to identify the key factors influencing employment risk in the AI workforce.

### Business Questions

- Which professionals have the highest job security?
- Which countries have the highest layoff risk?
- Does AI adoption improve job security?
- Which job roles are most vulnerable to automation?
- Which industries are most stable?
- What factors contribute to workforce risk?

# Workforce Risk Intelligence - Ranking & Elite Segment Analysis

This notebook presents ranking analysis, percentile analysis, and elite workforce segmentation for Workforce Risk Intelligence. Each business question is organized into separate markdown and code cells for clarity and presentation.

## Top 10 Countries with Highest Job Security

**Business Question:** Analyze **top 10 countries with highest job security** to identify high-risk and high-security workforce segments, benchmark organizational resilience, and support strategic workforce planning.

In [560]:
# Top 10 Countries with Highest Job Security

df.groupby("country")[
    "job_security_score"
].mean().sort_values(ascending=False).head(10).round(2)

country
UAE            75.79
Australia      75.74
Japan          75.69
Netherlands    75.67
Brazil         75.62
Germany        75.57
USA            75.54
Singapore      75.53
Canada         75.46
UK             75.44
Name: job_security_score, dtype: float64

## Top 10 Countries with Highest Layoff Risk

**Business Question:** Analyze **top 10 countries with highest layoff risk** to identify high-risk and high-security workforce segments, benchmark organizational resilience, and support strategic workforce planning.

In [561]:
# Top 10 Countries with Highest Layoff Risk

df.groupby("country")[
    "layoff_risk"
].mean().sort_values(ascending=False).head(10).round(2)

country
India          0.18
UK             0.18
France         0.18
Canada         0.18
Singapore      0.18
Netherlands    0.18
USA            0.18
Germany        0.18
Australia      0.18
Brazil         0.18
Name: layoff_risk, dtype: float64

## Top 10 Job Roles with Highest Job Security

**Business Question:** Analyze **top 10 job roles with highest job security** to identify high-risk and high-security workforce segments, benchmark organizational resilience, and support strategic workforce planning.

In [562]:
# Top 10 Job Roles with Highest Job Security

df.groupby("job_role")[
    "job_security_score"
].mean().sort_values(ascending=False).head(10).round(2)

job_role
Data Scientist               75.78
AI Software Engineer         75.67
Research Scientist           75.59
NLP Engineer                 75.53
AI Engineer                  75.51
Computer Vision Engineer     75.51
Machine Learning Engineer    75.48
Data Analyst                 75.45
Name: job_security_score, dtype: float64

## Top 10 Job Roles with Highest Automation Risk

**Business Question:** Analyze **top 10 job roles with highest automation risk** to identify high-risk and high-security workforce segments, benchmark organizational resilience, and support strategic workforce planning.

In [563]:
# Top 10 Job Roles with Highest Automation Risk

df.groupby("job_role")[
    "automation_risk"
].mean().sort_values(ascending=False).head(10).round(2)

job_role
Computer Vision Engineer     50.64
AI Software Engineer         50.62
Research Scientist           50.61
Data Analyst                 50.34
Data Scientist               50.22
NLP Engineer                 50.18
Machine Learning Engineer    50.15
AI Engineer                  50.09
Name: automation_risk, dtype: float64

## Top Industries by Job Security

**Business Question:** Analyze **top industries by job security** to identify high-risk and high-security workforce segments, benchmark organizational resilience, and support strategic workforce planning.

In [564]:
# Top Industries by Job Security

df.groupby("industry")[
    "job_security_score"
].mean().sort_values(ascending=False).head(10).round(2)

industry
Tech          75.81
Retail        75.62
Education     75.59
Healthcare    75.57
Finance       75.56
Gaming        75.55
Telecom       75.54
Energy        75.48
Automotive    75.48
Consulting    75.44
Name: job_security_score, dtype: float64

## Top Industries by AI Adoption

**Business Question:** Analyze **top industries by ai adoption** to identify high-risk and high-security workforce segments, benchmark organizational resilience, and support strategic workforce planning.

In [565]:
# Top Industries by AI Adoption

df.groupby("industry")[
    "ai_adoption_score"
].mean().sort_values(ascending=False).head(10).round(2)

industry
Automotive    71.61
Tech          71.45
Consulting    71.45
Telecom       71.45
Finance       71.40
Energy        71.39
Education     71.38
Healthcare    71.29
Gaming        71.18
Retail        71.17
Name: ai_adoption_score, dtype: float64

## Job Security Quartiles

**Business Question:** Analyze **job security quartiles** to identify high-risk and high-security workforce segments, benchmark organizational resilience, and support strategic workforce planning.

In [566]:
# Job Security Quartiles

df["job_security_score"].quantile(
    [0.25, 0.50, 0.75]
).round(2)

0.25    68.0
0.50    77.0
0.75    84.0
Name: job_security_score, dtype: float64

## Layoff Risk Quartiles

**Business Question:** Analyze **layoff risk quartiles** to identify high-risk and high-security workforce segments, benchmark organizational resilience, and support strategic workforce planning.

In [567]:
# Layoff Risk Quartiles

df["layoff_risk"].quantile(
    [0.25, 0.50, 0.75]
).round(2)

0.25    0.08
0.50    0.14
0.75    0.28
Name: layoff_risk, dtype: float64

## Automation Risk Quartiles

**Business Question:** Analyze **automation risk quartiles** to identify high-risk and high-security workforce segments, benchmark organizational resilience, and support strategic workforce planning.

In [568]:
# Automation Risk Quartiles

df["automation_risk"].quantile(
    [0.25, 0.50, 0.75]
).round(2)

0.25    25.0
0.50    50.0
0.75    75.0
Name: automation_risk, dtype: float64

## Top 10% Secure Workforce

**Business Question:** Analyze **top 10% secure workforce** to identify high-risk and high-security workforce segments, benchmark organizational resilience, and support strategic workforce planning.

In [569]:
# Top 10% Secure Workforce

secure_workforce = (
    df[
        df["job_security_score"] >=
        df["job_security_score"].quantile(0.90)
    ]
)

secure_workforce.head()

,id,country,job_role,ai_specialization,experience_level,experience_years,salary_usd,bonus_usd,education_required,industry,company_size,interview_rounds,year,work_mode,weekly_hours,company_rating,job_openings,hiring_difficulty_score,layoff_risk,ai_adoption_score,company_funding_billion,economic_index,ai_maturity_years,offer_acceptance_rate,tax_rate_percent,vacation_days,skill_demand_score,automation_risk,job_security_score,career_growth_score,work_life_balance_score,promotion_speed,salary_percentile,cost_of_living_index,employee_satisfaction,salary_quartile,total_compensation,career_stage,bonus_percentage,compensation_multiplier,salary_per_experience_year,salary_demand_ratio,compensation_score,career_acceleration_index,promotion_efficiency,career_momentum_score,growth_potential_index,experience_efficiency_score
6,7,Japan,Data Analyst,LLM,Senior,9,71014,11956,Phd,Tech,Small,5,2020,Hybrid,36.6,4.37,17,61.21,0.042,78,3.41,65.23,4,80.29,31.0,16,73,92,93,42,96,67,41,1.57,80,Mid,82970,Experienced,16.84,1.168,7890.44,972.79,0.3477,4.20,6.70,50.00,30.66,4.20
14,15,Japan,Data Analyst,Forecasting,Senior,7,64231,3378,Bootcamp,Telecom,Medium,5,2020,Remote,47.7,4.74,24,89.80,0.110,72,8.98,94.79,6,62.83,14.1,17,9,44,89,73,68,31,3,0.70,74,Low,67609,Experienced,5.26,1.053,9175.86,7136.78,0.1991,9.12,3.88,35.67,6.57,9.12
28,29,Japan,Computer Vision Engineer,Computer Vision,Lead,15,139135,21003,Bachelor,Energy,Startup,7,2022,Remote,39.8,4.70,1,90.95,0.039,61,6.57,54.97,11,57.66,34.2,11,48,75,90,53,85,58,71,1.65,87,Best,160138,Expert,15.10,1.151,9275.67,2898.65,0.8304,3.31,3.62,60.67,25.44,3.31
33,34,USA,Machine Learning Engineer,MLOps,Senior,9,158412,32692,Bachelor,Healthcare,Enterprise,2,2024,Onsite,40.3,4.02,7,48.96,0.012,53,4.41,98.65,9,73.36,28.7,21,94,41,89,43,96,15,56,2.22,93,Best,191104,Experienced,20.64,1.206,17601.33,1685.23,0.9226,4.30,1.50,38.00,40.42,4.30
42,43,Germany,Research Scientist,Forecasting,Lead,14,180739,9690,Bachelor,Retail,Medium,7,2023,Hybrid,45.1,4.34,13,80.37,0.084,86,6.04,77.40,6,66.09,39.3,18,43,41,92,79,68,38,70,0.59,79,Best,190429,Expert,5.36,1.054,12909.93,4203.23,0.9210,5.27,2.53,62.33,33.97,5.27

## Top 10% High-Risk Workforce

**Business Question:** Analyze **top 10% high-risk workforce** to identify high-risk and high-security workforce segments, benchmark organizational resilience, and support strategic workforce planning.

In [570]:
# Top 10% High-Risk Workforce

high_risk_workforce = (
    df[
        df["layoff_risk"] >=
        df["layoff_risk"].quantile(0.90)
    ]
)

high_risk_workforce.head()

,id,country,job_role,ai_specialization,experience_level,experience_years,salary_usd,bonus_usd,education_required,industry,company_size,interview_rounds,year,work_mode,weekly_hours,company_rating,job_openings,hiring_difficulty_score,layoff_risk,ai_adoption_score,company_funding_billion,economic_index,ai_maturity_years,offer_acceptance_rate,tax_rate_percent,vacation_days,skill_demand_score,automation_risk,job_security_score,career_growth_score,work_life_balance_score,promotion_speed,salary_percentile,cost_of_living_index,employee_satisfaction,salary_quartile,total_compensation,career_stage,bonus_percentage,compensation_multiplier,salary_per_experience_year,salary_demand_ratio,compensation_score,career_acceleration_index,promotion_efficiency,career_momentum_score,growth_potential_index,experience_efficiency_score
0,1,UAE,Machine Learning Engineer,Reinforcement Learning,Entry,0,66465,5395,Master,Automotive,Small,7,2020,Remote,44.7,3.67,10,52.77,0.404,91,3.30,78.65,13,60.58,20.8,27,12,76,57,65,73,15,55,1.23,76,Mid,71860,Early Career,8.12,1.081,66465.0,5538.75,0.2375,65.0,15.0,45.00,7.80,65.0
2,3,Brazil,Research Scientist,Analytics,Entry,0,41660,5268,Phd,Healthcare,Large,3,2020,Remote,46.8,4.78,10,76.40,0.415,69,5.04,87.47,8,62.95,12.2,13,12,49,70,59,68,37,13,2.13,61,Low,46928,Early Career,12.65,1.126,41660.0,3471.67,0.0811,59.0,37.0,36.33,7.08,59.0
10,11,France,AI Software Engineer,NLP,Entry,1,62612,6106,Diploma,Automotive,Large,2,2026,Onsite,46.5,4.03,22,52.70,0.400,76,5.52,93.26,14,84.63,32.9,18,65,98,58,58,70,45,23,1.90,61,Low,68718,Early Career,9.75,1.098,62612.0,963.26,0.2086,29.0,22.5,42.00,37.70,29.0
12,13,Netherlands,AI Engineer,Reinforcement Learning,Entry,1,81093,10358,Bachelor,Gaming,Medium,3,2023,Onsite,38.6,3.85,21,84.95,0.410,66,1.43,54.53,4,61.26,19.5,12,94,63,60,41,79,55,9,1.60,71,Mid,91451,Early Career,12.77,1.128,81093.0,862.69,0.4327,20.5,27.5,35.00,38.54,20.5
51,52,France,Machine Learning Engineer,Generative AI,Entry,0,63084,3351,Phd,Gaming,Enterprise,2,2023,Onsite,53.9,3.37,17,76.30,0.417,51,0.87,80.00,13,83.26,12.9,20,2,54,64,33,55,12,63,2.37,67,Low,66435,Early Career,5.31,1.053,63084.0,31542.00,0.1896,33.0,12.0,36.00,0.66,33.0

## Workforce Risk Overview

**Business Question:** Analyze **workforce risk overview** to identify workforce risk patterns, evaluate organizational resilience, and support data-driven workforce planning.

In [571]:
# Workforce Risk Overview

df[[
    "layoff_risk",
    "automation_risk",
    "job_security_score",
    "ai_adoption_score"
]].describe().round(2)

       layoff_risk  automation_risk  job_security_score  ai_adoption_score
count     90000.00         90000.00            90000.00           90000.00
mean          0.18            50.36               75.56              71.38
std           0.13            28.85               11.32              13.77
min           0.00             1.00               29.00               1.00
25%           0.08            25.00               68.00              62.00
50%           0.14            50.00               77.00              71.00
75%           0.28            75.00               84.00              81.00
max           0.59           100.00               99.00             100.00

## Job Security by Experience Level

**Business Question:** Analyze **job security by experience level** to identify workforce risk patterns, evaluate organizational resilience, and support data-driven workforce planning.

In [572]:
# Job Security by Experience Level

df.groupby("experience_level")[
    "job_security_score"
].agg(["mean", "median", "min", "max"]).round(2)

                   mean  median  min  max
experience_level
Entry             61.54    62.0   29   86
Lead              82.43    83.0   50   99
Mid               75.51    76.0   45   99
Senior            82.58    83.0   53   99

## Layoff Risk by Experience Level

**Business Question:** Analyze **layoff risk by experience level** to identify workforce risk patterns, evaluate organizational resilience, and support data-driven workforce planning.

In [573]:
# Layoff Risk by Experience Level

df.groupby("experience_level")[
    "layoff_risk"
].mean().round(2)

experience_level
Entry     0.38
Lead      0.08
Mid       0.18
Senior    0.08
Name: layoff_risk, dtype: float64

## Automation Risk by Job Role

**Business Question:** Analyze **automation risk by job role** to identify workforce risk patterns, evaluate organizational resilience, and support data-driven workforce planning.

In [574]:
# Automation Risk by Job Role

df.groupby("job_role")[
    "automation_risk"
].mean().sort_values(ascending=False).round(2)

job_role
Computer Vision Engineer     50.64
AI Software Engineer         50.62
Research Scientist           50.61
Data Analyst                 50.34
Data Scientist               50.22
NLP Engineer                 50.18
Machine Learning Engineer    50.15
AI Engineer                  50.09
Name: automation_risk, dtype: float64

## Job Security by Country

**Business Question:** Analyze **job security by country** to identify workforce risk patterns, evaluate organizational resilience, and support data-driven workforce planning.

In [575]:
# Job Security by Country

df.groupby("country")[
    "job_security_score"
].mean().sort_values(ascending=False).round(2)

country
UAE            75.79
Australia      75.74
Japan          75.69
Netherlands    75.67
Brazil         75.62
Germany        75.57
USA            75.54
Singapore      75.53
Canada         75.46
UK             75.44
France         75.37
India          75.35
Name: job_security_score, dtype: float64

## Layoff Risk by Country

**Business Question:** Analyze **layoff risk by country** to identify workforce risk patterns, evaluate organizational resilience, and support data-driven workforce planning.

In [576]:
# Layoff Risk by Country

df.groupby("country")[
    "layoff_risk"
].mean().sort_values(ascending=False).round(2)

country
India          0.18
UK             0.18
France         0.18
Canada         0.18
Singapore      0.18
Netherlands    0.18
USA            0.18
Germany        0.18
Australia      0.18
Brazil         0.18
Japan          0.18
UAE            0.18
Name: layoff_risk, dtype: float64

## Job Security by Industry

**Business Question:** Analyze **job security by industry** to identify workforce risk patterns, evaluate organizational resilience, and support data-driven workforce planning.

In [577]:
# Job Security by Industry

df.groupby("industry")[
    "job_security_score"
].mean().sort_values(ascending=False).round(2)

industry
Tech          75.81
Retail        75.62
Education     75.59
Healthcare    75.57
Finance       75.56
Gaming        75.55
Telecom       75.54
Energy        75.48
Automotive    75.48
Consulting    75.44
Name: job_security_score, dtype: float64

## AI Adoption by Industry

**Business Question:** Analyze **ai adoption by industry** to identify workforce risk patterns, evaluate organizational resilience, and support data-driven workforce planning.

In [578]:
# AI Adoption by Industry

df.groupby("industry")[
    "ai_adoption_score"
].mean().sort_values(ascending=False).round(2)

industry
Automotive    71.61
Tech          71.45
Consulting    71.45
Telecom       71.45
Finance       71.40
Energy        71.39
Education     71.38
Healthcare    71.29
Gaming        71.18
Retail        71.17
Name: ai_adoption_score, dtype: float64

# Workforce Risk Intelligence - Multi-Factor Analysis

This notebook explores relationships between workforce risk metrics using correlation analysis, pivot tables, and cross-tabulations. Each business question is presented in a separate markdown and code cell for a clean, presentation-ready workflow.

## Correlation with Job Security Score

**Business Question:** Analyze **correlation with job security score** to identify multi-dimensional workforce risk patterns and support strategic workforce planning and organizational resilience.

In [579]:
# Correlation with Job Security Score

workforce_risk_corr = (
    df[[
        "job_security_score",
        "layoff_risk",
        "automation_risk",
        "ai_adoption_score",
        "career_growth_score",
        "promotion_speed",
        "salary_usd",
        "skill_demand_score",
        "employee_satisfaction",
        "company_rating"
    ]]
    .corr()["job_security_score"]
    .sort_values(ascending=False)
    .round(2)
)

workforce_risk_corr

job_security_score       1.00
employee_satisfaction    0.48
salary_usd               0.43
career_growth_score      0.06
promotion_speed          0.06
automation_risk          0.01
company_rating           0.00
ai_adoption_score       -0.00
skill_demand_score      -0.00
layoff_risk             -0.81
Name: job_security_score, dtype: float64

## Average Job Security by Country and Experience Level

**Business Question:** Analyze **average job security by country and experience level** to identify multi-dimensional workforce risk patterns and support strategic workforce planning and organizational resilience.

In [580]:
# Average Job Security by Country and Experience Level

pd.pivot_table(
    df,
    values="job_security_score",
    index="country",
    columns="experience_level",
    aggfunc="mean"
).round(2)

experience_level  Entry   Lead    Mid  Senior
country
Australia         61.60  82.77  75.60   82.75
Brazil            61.29  82.46  75.55   82.56
Canada            61.35  82.63  75.42   82.58
France            61.38  82.33  75.50   82.51
Germany           61.70  82.19  75.41   82.56
India             61.52  82.41  75.35   82.58
Japan             61.50  82.34  75.67   82.41
Netherlands       61.69  82.27  75.63   82.84
Singapore         61.48  82.73  75.55   82.20
UAE               61.63  82.40  75.48   82.81
UK                61.59  82.41  75.49   82.49
USA               61.70  82.19  75.53   82.68

## Average Layoff Risk by Industry and Experience Level

**Business Question:** Analyze **average layoff risk by industry and experience level** to identify multi-dimensional workforce risk patterns and support strategic workforce planning and organizational resilience.

In [581]:
# Average Layoff Risk by Industry and Experience Level

pd.pivot_table(
    df,
    values="layoff_risk",
    index="industry",
    columns="experience_level",
    aggfunc="mean"
).round(2)

experience_level  Entry  Lead   Mid  Senior
industry
Automotive         0.38  0.08  0.18    0.08
Consulting         0.38  0.08  0.18    0.08
Education          0.38  0.08  0.18    0.08
Energy             0.38  0.08  0.18    0.08
Finance            0.38  0.08  0.18    0.08
Gaming             0.38  0.08  0.18    0.08
Healthcare         0.38  0.08  0.18    0.08
Retail             0.38  0.08  0.18    0.08
Tech               0.38  0.08  0.18    0.08
Telecom            0.38  0.08  0.18    0.08

## Average Automation Risk by Job Role and Experience Level

**Business Question:** Analyze **average automation risk by job role and experience level** to identify multi-dimensional workforce risk patterns and support strategic workforce planning and organizational resilience.

In [582]:
# Average Automation Risk by Job Role and Experience Level

pd.pivot_table(
    df,
    values="automation_risk",
    index="job_role",
    columns="experience_level",
    aggfunc="mean"
).round(2)

experience_level           Entry   Lead    Mid  Senior
job_role
AI Engineer                49.85  50.54  49.84   50.10
AI Software Engineer       51.52  50.03  50.59   50.38
Computer Vision Engineer   50.28  51.11  50.93   50.26
Data Analyst               49.67  51.01  50.70   50.00
Data Scientist             49.34  50.87  50.82   49.83
Machine Learning Engineer  50.43  49.90  49.97   50.31
NLP Engineer               49.80  51.05  50.11   49.76
Research Scientist         50.33  50.68  51.08   50.34

## Average AI Adoption Score by Industry and Experience Level

**Business Question:** Analyze **average ai adoption score by industry and experience level** to identify multi-dimensional workforce risk patterns and support strategic workforce planning and organizational resilience.

In [583]:
# Average AI Adoption Score by Industry and Experience Level

pd.pivot_table(
    df,
    values="ai_adoption_score",
    index="industry",
    columns="experience_level",
    aggfunc="mean"
).round(2)

experience_level  Entry   Lead    Mid  Senior
industry
Automotive        71.62  71.86  71.10   71.86
Consulting        71.53  71.30  71.83   71.14
Education         70.83  71.38  71.54   71.76
Energy            71.57  71.25  71.52   71.20
Finance           71.12  71.43  71.68   71.34
Gaming            70.60  71.90  71.15   71.07
Healthcare        71.66  71.38  71.28   70.87
Retail            70.99  71.41  71.25   71.02
Tech              70.96  71.75  71.46   71.58
Telecom           71.05  72.12  71.08   71.54

## Job Security by Country and Industry

**Business Question:** Analyze **job security by country and industry** to identify multi-dimensional workforce risk patterns and support strategic workforce planning and organizational resilience.

In [584]:
# Job Security by Country and Industry

pd.crosstab(
    index=df["country"],
    columns=df["industry"],
    values=df["job_security_score"],
    aggfunc="mean"
).round(2)

industry,Automotive,Consulting,Education,Energy,Finance,Gaming,Healthcare,Retail,Tech,Telecom
country,,,,,,,,,,
Australia,75.24,75.81,76.24,75.47,75.37,75.41,75.89,76.23,76.09,75.67
Brazil,75.01,75.39,75.36,75.24,75.71,75.76,75.24,75.27,77.06,76.15
Canada,75.35,74.69,75.20,75.31,75.66,75.87,75.71,75.85,75.42,75.39
France,76.23,75.12,75.09,75.66,75.95,75.09,75.50,75.37,74.98,74.74
Germany,75.49,75.70,75.65,75.55,75.00,75.43,75.65,76.11,76.37,74.83
India,75.25,75.12,76.06,75.49,74.88,74.80,75.26,75.58,75.56,75.38
Japan,75.25,75.97,76.18,75.41,75.74,76.18,75.30,75.88,75.46,75.56
Netherlands,75.87,75.09,75.95,75.96,75.95,76.05,75.09,75.07,75.52,76.09
Singapore,75.72,75.76,74.85,75.49,75.25,75.69,75.72,75.69,75.46,75.61
UAE,75.55,75.59,75.74,75.90,76.05,75.70,76.10,75.97,76.31,74.97
UK,75.45,75.84,75.10,75.14,75.76,75.64,75.63,74.81,75.14,75.83
USA,75.32,75.14,75.58,75.20,75.42,74.94,75.77,75.45,76.40,76.31

## Layoff Risk by Country and Job Role

**Business Question:** Analyze **layoff risk by country and job role** to identify multi-dimensional workforce risk patterns and support strategic workforce planning and organizational resilience.

In [585]:
# Layoff Risk by Country and Job Role

pd.crosstab(
    index=df["country"],
    columns=df["job_role"],
    values=df["layoff_risk"],
    aggfunc="mean"
).round(2)

job_role,AI Engineer,AI Software Engineer,Computer Vision Engineer,Data Analyst,Data Scientist,Machine Learning Engineer,NLP Engineer,Research Scientist
country,,,,,,,,
Australia,0.18,0.17,0.18,0.18,0.18,0.18,0.18,0.17
Brazil,0.17,0.17,0.18,0.18,0.18,0.18,0.18,0.17
Canada,0.18,0.18,0.18,0.18,0.18,0.18,0.18,0.18
France,0.18,0.17,0.18,0.19,0.19,0.18,0.19,0.18
Germany,0.18,0.17,0.17,0.18,0.18,0.18,0.18,0.19
India,0.18,0.18,0.18,0.18,0.18,0.19,0.18,0.19
Japan,0.17,0.18,0.18,0.18,0.17,0.18,0.18,0.18
Netherlands,0.18,0.18,0.18,0.18,0.18,0.18,0.17,0.18
Singapore,0.19,0.18,0.19,0.17,0.17,0.18,0.18,0.18
UAE,0.18,0.17,0.18,0.18,0.18,0.17,0.17,0.18
UK,0.18,0.19,0.18,0.18,0.17,0.18,0.18,0.19
USA,0.17,0.18,0.18,0.19,0.18,0.18,0.18,0.17

## Automation Risk by AI Specialization and Experience Level

**Business Question:** Analyze **automation risk by ai specialization and experience level** to identify multi-dimensional workforce risk patterns and support strategic workforce planning and organizational resilience.

In [586]:
# Automation Risk by AI Specialization and Experience Level

pd.crosstab(
    index=df["ai_specialization"],
    columns=df["experience_level"],
    values=df["automation_risk"],
    aggfunc="mean"
).round(2)

experience_level        Entry   Lead    Mid  Senior
ai_specialization
Analytics               50.90  50.35  50.30   49.07
Computer Vision         49.72  50.03  50.95   50.70
Forecasting             50.39  50.85  50.58   50.35
Generative AI           49.86  50.69  49.56   49.84
LLM                     49.11  51.31  51.04   49.85
MLOps                   50.27  50.21  50.22   50.05
NLP                     50.93  51.47  50.64   50.67
Reinforcement Learning  50.09  50.29  50.72   50.42

# Workforce Risk Intelligence - Feature Engineering

This notebook creates engineered workforce risk metrics to quantify organizational stability, automation resilience, workforce readiness, and overall risk exposure. Each engineered feature and its analysis is presented with a dedicated markdown and code cell.

## Workforce Stability Index

**Business Question:** Evaluate **workforce stability index** to derive advanced workforce risk intelligence, identify resilient talent segments, and support strategic workforce planning.

In [587]:
# Workforce Stability Index

df["workforce_stability_index"] = (
    (
        df["job_security_score"] +
        df["ai_adoption_score"] +
        (100 - df["layoff_risk"] * 100)
    ) / 3
).round(2)

## Automation Resilience Score

**Business Question:** Evaluate **automation resilience score** to derive advanced workforce risk intelligence, identify resilient talent segments, and support strategic workforce planning.

In [588]:
# Automation Resilience Score

df["automation_resilience_score"] = (
    (
        df["job_security_score"] +
        (100 - df["automation_risk"])
    ) / 2
).round(2)

## Risk Exposure Index

**Business Question:** Evaluate **risk exposure index** to derive advanced workforce risk intelligence, identify resilient talent segments, and support strategic workforce planning.

In [589]:
# Risk Exposure Index

df["risk_exposure_index"] = (
    (
        (df["layoff_risk"] * 100) +
        df["automation_risk"]
    ) / 2
).round(2)

## AI Workforce Readiness Score

**Business Question:** Evaluate **ai workforce readiness score** to derive advanced workforce risk intelligence, identify resilient talent segments, and support strategic workforce planning.

In [590]:
# AI Workforce Readiness Score

df["ai_workforce_readiness_score"] = (
    (
        df["job_security_score"] +
        df["ai_adoption_score"] +
        df["skill_demand_score"]
    ) / 3
).round(2)

## Stability-to-Risk Ratio

**Business Question:** Evaluate **stability-to-risk ratio** to derive advanced workforce risk intelligence, identify resilient talent segments, and support strategic workforce planning.

In [591]:
# Stability-to-Risk Ratio

df["stability_risk_ratio"] = (
    df["job_security_score"] /
    (df["layoff_risk"] * 100 + 1)
).round(2)

## Engineered Metrics Summary

**Business Question:** Evaluate **engineered metrics summary** to derive advanced workforce risk intelligence, identify resilient talent segments, and support strategic workforce planning.

In [592]:
# Engineered Metrics Summary

df[[
    "workforce_stability_index",
    "automation_resilience_score",
    "risk_exposure_index",
    "ai_workforce_readiness_score",
    "stability_risk_ratio"
]].describe().round(2)

,workforce_stability_index,automation_resilience_score,risk_exposure_index,ai_workforce_readiness_score,stability_risk_ratio
count,90000.00,90000.00,90000.00,90000.00,90000.00
mean,76.32,62.60,34.16,65.80,9.83
std,9.03,15.46,15.83,11.31,16.12
min,38.57,18.50,0.50,24.67,0.61
25%,70.17,50.00,21.69,57.33,2.40
50%,77.57,62.50,34.15,65.67,5.17
75%,82.97,75.00,46.70,74.33,9.38
max,99.67,99.00,77.65,99.33,99.00

## Top 10 Workforce Stability

**Business Question:** Evaluate **top 10 workforce stability** to derive advanced workforce risk intelligence, identify resilient talent segments, and support strategic workforce planning.

In [593]:
# Top 10 Workforce Stability

df.nlargest(
    10,
    "workforce_stability_index"
)[[
    "job_role",
    "country",
    "workforce_stability_index"
]]

                        job_role    country  workforce_stability_index
7258              Data Scientist  Singapore                      99.67
10472       AI Software Engineer  Australia                      99.67
57488             Data Scientist      India                      99.67
62048               Data Analyst    Germany                      99.67
67270               Data Analyst        UAE                      99.67
75125               Data Analyst      Japan                      99.43
16739               Data Analyst  Singapore                      99.33
56289             Data Scientist  Australia                      99.33
79311  Machine Learning Engineer  Australia                      99.33
89422             Data Scientist         UK                      99.13

## Top 10 Automation Resilience

**Business Question:** Evaluate **top 10 automation resilience** to derive advanced workforce risk intelligence, identify resilient talent segments, and support strategic workforce planning.

In [594]:
# Top 10 Automation Resilience

df.nlargest(
    10,
    "automation_resilience_score"
)[[
    "job_role",
    "country",
    "automation_resilience_score"
]]

                        job_role      country  automation_resilience_score
35441               Data Analyst        Japan                         99.0
54552   Computer Vision Engineer    Australia                         99.0
7016                Data Analyst       Brazil                         98.5
16262  Machine Learning Engineer          USA                         98.5
16298               NLP Engineer      Germany                         98.5
54618                AI Engineer          USA                         98.5
942           Research Scientist          USA                         98.0
2521              Data Scientist        Japan                         98.0
18151               NLP Engineer  Netherlands                         98.0
24234         Research Scientist  Netherlands                         98.0

## Top 10 Lowest Risk Exposure

**Business Question:** Evaluate **top 10 lowest risk exposure** to derive advanced workforce risk intelligence, identify resilient talent segments, and support strategic workforce planning.

In [595]:
# Top 10 Lowest Risk Exposure

df.nsmallest(
    10,
    "risk_exposure_index"
)[[
    "job_role",
    "country",
    "risk_exposure_index"
]]

                        job_role      country  risk_exposure_index
2078        AI Software Engineer    Australia                  0.5
2448          Research Scientist      Germany                  0.5
9496                 AI Engineer       France                  0.5
10892         Research Scientist          UAE                  0.5
11229  Machine Learning Engineer          USA                  0.5
17727                AI Engineer    Australia                  0.5
17829       AI Software Engineer    Australia                  0.5
22286       AI Software Engineer    Australia                  0.5
24267               Data Analyst  Netherlands                  0.5
26371                AI Engineer    Australia                  0.5

## Correlation of Engineered Metrics

**Business Question:** Evaluate **correlation of engineered metrics** to derive advanced workforce risk intelligence, identify resilient talent segments, and support strategic workforce planning.

In [596]:
# Correlation of Engineered Metrics

df[[
    "job_security_score",
    "layoff_risk",
    "automation_risk",
    "workforce_stability_index",
    "automation_resilience_score",
    "risk_exposure_index",
    "ai_workforce_readiness_score",
    "stability_risk_ratio"
]].corr().round(2)

,job_security_score,layoff_risk,automation_risk,workforce_stability_index,automation_resilience_score,risk_exposure_index,ai_workforce_readiness_score,stability_risk_ratio
job_security_score,1.00,-0.81,0.01,0.81,0.36,-0.33,0.33,0.46
layoff_risk,-0.81,1.00,-0.00,-0.83,-0.29,0.41,-0.27,-0.52
automation_risk,0.01,-0.00,1.00,0.01,-0.93,0.91,0.01,0.01
workforce_stability_index,0.81,-0.83,0.01,1.00,0.29,-0.34,0.48,0.44
automation_resilience_score,0.36,-0.29,-0.93,0.29,1.00,-0.97,0.12,0.16
risk_exposure_index,-0.33,0.41,0.91,-0.34,-0.97,1.00,-0.11,-0.21
ai_workforce_readiness_score,0.33,-0.27,0.01,0.48,0.12,-0.11,1.00,0.15
stability_risk_ratio,0.46,-0.52,0.01,0.44,0.16,-0.21,0.15,1.00

# 04 Talent Market Intelligence

# Module 4: Talent Market Intelligence

## Objective

Analyze hiring demand, skill demand, job openings, and recruitment competitiveness to understand the current AI talent market.

### Business Questions

- Which countries have the highest hiring demand?
- Which job roles have the most openings?
- Which AI specializations are most demanded?
- Which industries hire the most AI professionals?
- Does Skill Demand Score influence job openings?
- Which factors drive hiring demand?

# Talent Market Intelligence - Foundation Analysis

This notebook organizes the foundational Talent Market Intelligence analysis into individual business questions. Each analysis is presented with a dedicated markdown cell followed by a Python code cell for clarity and presentation.

## Talent Market Overview

**Business Question:** Analyze **talent market overview** to understand talent demand, hiring complexity, and labor market dynamics for strategic workforce planning.

In [597]:
# Talent Market Overview

df[[
    "job_openings",
    "skill_demand_score",
    "hiring_difficulty_score",
    "interview_rounds"
]].describe().round(2)

,job_openings,skill_demand_score,hiring_difficulty_score,interview_rounds
count,90000.00,90000.00,90000.00,90000.0
mean,17.52,50.46,55.03,4.5
std,7.85,28.85,17.90,1.7
min,1.00,1.00,0.00,2.0
25%,12.00,25.00,42.88,3.0
50%,17.00,51.00,55.07,4.0
75%,23.00,75.00,67.12,6.0
max,50.00,100.00,100.00,7.0

## Job Openings by Country

**Business Question:** Analyze **job openings by country** to understand talent demand, hiring complexity, and labor market dynamics for strategic workforce planning.

In [598]:
# Job Openings by Country

df.groupby("country")[
    "job_openings"
].agg(["mean", "median", "min", "max"]).round(2)

              mean  median  min  max
country
Australia    17.56    17.0    1   48
Brazil       17.47    17.0    1   45
Canada       17.53    17.0    1   45
France       17.40    17.0    1   47
Germany      17.38    17.0    1   45
India        17.52    17.0    1   45
Japan        17.56    18.0    1   46
Netherlands  17.51    17.0    1   50
Singapore    17.62    18.0    1   48
UAE          17.42    17.0    1   47
UK           17.64    18.0    1   47
USA          17.65    18.0    1   47

## Job Openings by Job Role

**Business Question:** Analyze **job openings by job role** to understand talent demand, hiring complexity, and labor market dynamics for strategic workforce planning.

In [599]:
# Job Openings by Job Role

df.groupby("job_role")[
    "job_openings"
].mean().sort_values(ascending=False).round(2)

job_role
AI Software Engineer         17.64
Computer Vision Engineer     17.59
Machine Learning Engineer    17.55
Data Analyst                 17.52
AI Engineer                  17.50
Data Scientist               17.47
Research Scientist           17.46
NLP Engineer                 17.43
Name: job_openings, dtype: float64

## Job Openings by AI Specialization

**Business Question:** Analyze **job openings by ai specialization** to understand talent demand, hiring complexity, and labor market dynamics for strategic workforce planning.

In [600]:
# Job Openings by AI Specialization

df.groupby("ai_specialization")[
    "job_openings"
].mean().sort_values(ascending=False).round(2)

ai_specialization
Reinforcement Learning    17.57
Analytics                 17.57
Computer Vision           17.55
Forecasting               17.53
Generative AI             17.53
NLP                       17.51
LLM                       17.50
MLOps                     17.42
Name: job_openings, dtype: float64

## Job Openings by Industry

**Business Question:** Analyze **job openings by industry** to understand talent demand, hiring complexity, and labor market dynamics for strategic workforce planning.

In [601]:
# Job Openings by Industry

df.groupby("industry")[
    "job_openings"
].mean().sort_values(ascending=False).round(2)

industry
Healthcare    17.65
Telecom       17.64
Energy        17.58
Finance       17.55
Tech          17.54
Gaming        17.51
Retail        17.44
Automotive    17.44
Consulting    17.44
Education     17.43
Name: job_openings, dtype: float64

## Skill Demand Score by AI Specialization

**Business Question:** Analyze **skill demand score by ai specialization** to understand talent demand, hiring complexity, and labor market dynamics for strategic workforce planning.

In [602]:
# Skill Demand Score by AI Specialization

df.groupby("ai_specialization")[
    "skill_demand_score"
].mean().sort_values(ascending=False).round(2)

ai_specialization
LLM                       50.83
Forecasting               50.75
Analytics                 50.70
Generative AI             50.48
MLOps                     50.43
NLP                       50.40
Computer Vision           50.11
Reinforcement Learning    49.99
Name: skill_demand_score, dtype: float64

## Hiring Difficulty by Job Role

**Business Question:** Analyze **hiring difficulty by job role** to understand talent demand, hiring complexity, and labor market dynamics for strategic workforce planning.

In [603]:
# Hiring Difficulty by Job Role

df.groupby("job_role")[
    "hiring_difficulty_score"
].mean().sort_values(ascending=False).round(2)

job_role
NLP Engineer                 55.11
Data Analyst                 55.08
Machine Learning Engineer    55.05
AI Engineer                  55.04
Data Scientist               55.04
Computer Vision Engineer     55.02
Research Scientist           54.96
AI Software Engineer         54.94
Name: hiring_difficulty_score, dtype: float64

## Interview Rounds by Job Role

**Business Question:** Analyze **interview rounds by job role** to understand talent demand, hiring complexity, and labor market dynamics for strategic workforce planning.

In [604]:
# Interview Rounds by Job Role

df.groupby("job_role")[
    "interview_rounds"
].mean().sort_values(ascending=False).round(2)

job_role
AI Engineer                  4.52
Research Scientist           4.51
Data Analyst                 4.50
AI Software Engineer         4.50
Machine Learning Engineer    4.50
Data Scientist               4.49
Computer Vision Engineer     4.48
NLP Engineer                 4.47
Name: interview_rounds, dtype: float64

# Talent Market Intelligence - Ranking & Elite Segment Analysis

This notebook presents ranking analysis, percentile analysis, and elite talent segmentation for Talent Market Intelligence. Each business question is organized into separate markdown and code cells for a clean, presentation-ready workflow.

## Top 10 Countries by Job Openings

**Business Question:** Analyze **top 10 countries by job openings** to identify high-demand talent segments, benchmark labor market trends, and support strategic hiring decisions.

In [605]:
# Top 10 Countries by Job Openings

df.groupby("country")[
    "job_openings"
].mean().sort_values(ascending=False).head(10).round(2)

country
USA            17.65
UK             17.64
Singapore      17.62
Japan          17.56
Australia      17.56
Canada         17.53
India          17.52
Netherlands    17.51
Brazil         17.47
UAE            17.42
Name: job_openings, dtype: float64

## Top 10 Job Roles by Job Openings

**Business Question:** Analyze **top 10 job roles by job openings** to identify high-demand talent segments, benchmark labor market trends, and support strategic hiring decisions.

In [606]:
# Top 10 Job Roles by Job Openings

df.groupby("job_role")[
    "job_openings"
].mean().sort_values(ascending=False).head(10).round(2)

job_role
AI Software Engineer         17.64
Computer Vision Engineer     17.59
Machine Learning Engineer    17.55
Data Analyst                 17.52
AI Engineer                  17.50
Data Scientist               17.47
Research Scientist           17.46
NLP Engineer                 17.43
Name: job_openings, dtype: float64

## Top 10 AI Specializations by Job Openings

**Business Question:** Analyze **top 10 ai specializations by job openings** to identify high-demand talent segments, benchmark labor market trends, and support strategic hiring decisions.

In [607]:
# Top 10 AI Specializations by Job Openings

df.groupby("ai_specialization")[
    "job_openings"
].mean().sort_values(ascending=False).head(10).round(2)

ai_specialization
Reinforcement Learning    17.57
Analytics                 17.57
Computer Vision           17.55
Forecasting               17.53
Generative AI             17.53
NLP                       17.51
LLM                       17.50
MLOps                     17.42
Name: job_openings, dtype: float64

## Top 10 Industries by Job Openings

**Business Question:** Analyze **top 10 industries by job openings** to identify high-demand talent segments, benchmark labor market trends, and support strategic hiring decisions.

In [608]:
# Top 10 Industries by Job Openings

df.groupby("industry")[
    "job_openings"
].mean().sort_values(ascending=False).head(10).round(2)

industry
Healthcare    17.65
Telecom       17.64
Energy        17.58
Finance       17.55
Tech          17.54
Gaming        17.51
Retail        17.44
Automotive    17.44
Consulting    17.44
Education     17.43
Name: job_openings, dtype: float64

## Top 10 AI Specializations by Skill Demand

**Business Question:** Analyze **top 10 ai specializations by skill demand** to identify high-demand talent segments, benchmark labor market trends, and support strategic hiring decisions.

In [609]:
# Top 10 AI Specializations by Skill Demand

df.groupby("ai_specialization")[
    "skill_demand_score"
].mean().sort_values(ascending=False).head(10).round(2)

ai_specialization
LLM                       50.83
Forecasting               50.75
Analytics                 50.70
Generative AI             50.48
MLOps                     50.43
NLP                       50.40
Computer Vision           50.11
Reinforcement Learning    49.99
Name: skill_demand_score, dtype: float64

## Top 10 Job Roles by Hiring Difficulty

**Business Question:** Analyze **top 10 job roles by hiring difficulty** to identify high-demand talent segments, benchmark labor market trends, and support strategic hiring decisions.

In [610]:
# Top 10 Job Roles by Hiring Difficulty

df.groupby("job_role")[
    "hiring_difficulty_score"
].mean().sort_values(ascending=False).head(10).round(2)

job_role
NLP Engineer                 55.11
Data Analyst                 55.08
Machine Learning Engineer    55.05
AI Engineer                  55.04
Data Scientist               55.04
Computer Vision Engineer     55.02
Research Scientist           54.96
AI Software Engineer         54.94
Name: hiring_difficulty_score, dtype: float64

## Job Openings Quartiles

**Business Question:** Analyze **job openings quartiles** to identify high-demand talent segments, benchmark labor market trends, and support strategic hiring decisions.

In [611]:
# Job Openings Quartiles

df["job_openings"].quantile(
    [0.25, 0.50, 0.75]
).round(2)

0.25    12.0
0.50    17.0
0.75    23.0
Name: job_openings, dtype: float64

## Skill Demand Score Quartiles

**Business Question:** Analyze **skill demand score quartiles** to identify high-demand talent segments, benchmark labor market trends, and support strategic hiring decisions.

In [612]:
# Skill Demand Score Quartiles

df["skill_demand_score"].quantile(
    [0.25, 0.50, 0.75]
).round(2)

0.25    25.0
0.50    51.0
0.75    75.0
Name: skill_demand_score, dtype: float64

## Hiring Difficulty Quartiles

**Business Question:** Analyze **hiring difficulty quartiles** to identify high-demand talent segments, benchmark labor market trends, and support strategic hiring decisions.

In [613]:
# Hiring Difficulty Quartiles

df["hiring_difficulty_score"].quantile(
    [0.25, 0.50, 0.75]
).round(2)

0.25    42.88
0.50    55.07
0.75    67.12
Name: hiring_difficulty_score, dtype: float64

## Top 10% High Hiring Demand

**Business Question:** Analyze **top 10% high hiring demand** to identify high-demand talent segments, benchmark labor market trends, and support strategic hiring decisions.

In [614]:
# Top 10% High Hiring Demand

high_hiring_demand = (
    df[
        df["job_openings"] >=
        df["job_openings"].quantile(0.90)
    ]
)

high_hiring_demand.head()

,id,country,job_role,ai_specialization,experience_level,experience_years,salary_usd,bonus_usd,education_required,industry,company_size,interview_rounds,year,work_mode,weekly_hours,company_rating,job_openings,hiring_difficulty_score,layoff_risk,ai_adoption_score,company_funding_billion,economic_index,ai_maturity_years,offer_acceptance_rate,tax_rate_percent,vacation_days,skill_demand_score,automation_risk,job_security_score,career_growth_score,work_life_balance_score,promotion_speed,salary_percentile,cost_of_living_index,employee_satisfaction,salary_quartile,total_compensation,career_stage,bonus_percentage,compensation_multiplier,salary_per_experience_year,salary_demand_ratio,compensation_score,career_acceleration_index,promotion_efficiency,career_momentum_score,growth_potential_index,experience_efficiency_score,workforce_stability_index,automation_resilience_score,risk_exposure_index,ai_workforce_readiness_score,stability_risk_ratio
13,14,Singapore,Data Scientist,NLP,Mid,5,88751,18538,Phd,Consulting,Enterprise,6,2023,Onsite,49.9,3.48,35,40.82,0.140,75,0.64,68.86,9,70.94,30.5,16,70,97,71,48,78,25,94,1.77,77,High,107289,Developing,20.89,1.209,17750.20,1267.87,0.5607,8.00,4.17,55.67,33.60,8.00,77.33,37.0,55.50,72.00,4.73
30,31,Singapore,NLP Engineer,NLP,Mid,3,78117,6947,Diploma,Retail,Small,2,2020,Remote,49.2,3.25,29,76.86,0.220,39,1.75,76.34,14,85.50,38.3,20,53,86,74,35,57,24,95,1.18,73,Mid,85064,Developing,8.89,1.089,26039.00,1473.91,0.3690,8.75,6.00,51.33,18.55,8.75,63.67,44.0,54.00,55.33,3.22
36,37,Australia,AI Software Engineer,NLP,Lead,19,155111,24453,Master,Automotive,Enterprise,5,2024,Onsite,53.3,3.67,28,72.25,0.114,78,6.01,97.16,9,85.54,16.2,15,79,73,80,63,66,30,39,2.24,75,Best,179564,Expert,15.76,1.158,8163.74,1963.43,0.8928,3.15,1.50,44.00,49.77,3.15,82.20,53.5,42.20,79.00,6.45
39,40,USA,Data Analyst,Forecasting,Lead,17,162252,14041,Diploma,Education,Startup,7,2025,Onsite,42.4,3.21,38,53.27,0.051,73,7.37,50.67,6,67.58,36.2,22,64,52,86,62,67,85,32,2.42,83,Best,176293,Expert,8.65,1.087,9544.24,2535.19,0.8840,3.44,4.72,59.67,39.68,3.44,84.63,67.0,28.55,74.33,14.10
53,54,Netherlands,Computer Vision Engineer,Analytics,Lead,16,141862,26137,Master,Education,Medium,2,2024,Hybrid,40.3,4.55,31,62.85,0.079,100,9.47,79.58,10,84.41,35.0,17,97,60,86,92,80,28,73,1.51,81,Best,167999,Expert,18.42,1.184,8866.38,1462.49,0.8590,5.41,1.65,64.33,89.24,5.41,92.70,63.0,33.95,94.33,9.66

## Top 10% High Skill Demand

**Business Question:** Analyze **top 10% high skill demand** to identify high-demand talent segments, benchmark labor market trends, and support strategic hiring decisions.

In [615]:
# Top 10% High Skill Demand

high_skill_demand = (
    df[
        df["skill_demand_score"] >=
        df["skill_demand_score"].quantile(0.90)
    ]
)

high_skill_demand.head()

,id,country,job_role,ai_specialization,experience_level,experience_years,salary_usd,bonus_usd,education_required,industry,company_size,interview_rounds,year,work_mode,weekly_hours,company_rating,job_openings,hiring_difficulty_score,layoff_risk,ai_adoption_score,company_funding_billion,economic_index,ai_maturity_years,offer_acceptance_rate,tax_rate_percent,vacation_days,skill_demand_score,automation_risk,job_security_score,career_growth_score,work_life_balance_score,promotion_speed,salary_percentile,cost_of_living_index,employee_satisfaction,salary_quartile,total_compensation,career_stage,bonus_percentage,compensation_multiplier,salary_per_experience_year,salary_demand_ratio,compensation_score,career_acceleration_index,promotion_efficiency,career_momentum_score,growth_potential_index,experience_efficiency_score,workforce_stability_index,automation_resilience_score,risk_exposure_index,ai_workforce_readiness_score,stability_risk_ratio
12,13,Netherlands,AI Engineer,Reinforcement Learning,Entry,1,81093,10358,Bachelor,Gaming,Medium,3,2023,Onsite,38.6,3.85,21,84.95,0.410,66,1.43,54.53,4,61.26,19.5,12,94,63,60,41,79,55,9,1.60,71,Mid,91451,Early Career,12.77,1.128,81093.00,862.69,0.4327,20.50,27.50,35.00,38.54,20.50,61.67,48.5,52.00,73.33,1.43
33,34,USA,Machine Learning Engineer,MLOps,Senior,9,158412,32692,Bachelor,Healthcare,Enterprise,2,2024,Onsite,40.3,4.02,7,48.96,0.012,53,4.41,98.65,9,73.36,28.7,21,94,41,89,43,96,15,56,2.22,93,Best,191104,Experienced,20.64,1.206,17601.33,1685.23,0.9226,4.30,1.50,38.00,40.42,4.30,80.27,74.0,21.10,78.67,40.45
45,46,Australia,Data Analyst,Generative AI,Lead,14,93009,11108,Diploma,Retail,Medium,2,2021,Hybrid,37.5,4.07,17,87.30,0.011,61,2.25,92.55,8,84.36,27.6,22,93,22,90,43,82,49,60,2.24,80,High,104117,Expert,11.94,1.119,6643.50,1000.10,0.5374,2.87,3.27,50.67,39.99,2.87,83.30,84.0,11.55,81.33,42.86
49,50,Netherlands,Machine Learning Engineer,Analytics,Mid,5,92263,8914,Master,Consulting,Medium,6,2026,Onsite,40.0,3.93,16,61.34,0.178,75,0.49,74.17,14,55.71,35.9,13,100,21,80,46,73,45,40,1.09,73,High,101177,Developing,9.66,1.097,18452.60,922.63,0.5149,7.67,7.50,43.67,46.00,7.67,79.07,79.5,19.40,85.00,4.26
53,54,Netherlands,Computer Vision Engineer,Analytics,Lead,16,141862,26137,Master,Education,Medium,2,2024,Hybrid,40.3,4.55,31,62.85,0.079,100,9.47,79.58,10,84.41,35.0,17,97,60,86,92,80,28,73,1.51,81,Best,167999,Expert,18.42,1.184,8866.38,1462.49,0.8590,5.41,1.65,64.33,89.24,5.41,92.70,63.0,33.95,94.33,9.66

# Talent Market Intelligence - Multi-Factor Analysis

This notebook explores relationships among talent market indicators using correlation analysis, pivot tables, and cross-tabulations. Each analysis is organized into a dedicated markdown cell followed by its corresponding Python code cell.

## Correlation with Job Openings

**Business Question:** Analyze **correlation with job openings** to identify multi-dimensional hiring patterns, skill demand, recruitment complexity, and talent market opportunities.

In [616]:
# Correlation with Job Openings

talent_market_corr = (
    df[[
        "job_openings",
        "skill_demand_score",
        "hiring_difficulty_score",
        "interview_rounds",
        "salary_usd",
        "bonus_usd",
        "career_growth_score",
        "job_security_score",
        "ai_adoption_score",
        "company_rating"
    ]]
    .corr()["job_openings"]
    .sort_values(ascending=False)
    .round(2)
)

talent_market_corr

job_openings               1.0
bonus_usd                  0.0
salary_usd                 0.0
job_security_score         0.0
ai_adoption_score          0.0
company_rating             0.0
interview_rounds           0.0
skill_demand_score        -0.0
career_growth_score       -0.0
hiring_difficulty_score   -0.0
Name: job_openings, dtype: float64

## Average Job Openings by Country and Experience Level

**Business Question:** Analyze **average job openings by country and experience level** to identify multi-dimensional hiring patterns, skill demand, recruitment complexity, and talent market opportunities.

In [617]:
# Average Job Openings by Country and Experience Level

pd.pivot_table(
    df,
    values="job_openings",
    index="country",
    columns="experience_level",
    aggfunc="mean"
).round(2)

experience_level  Entry   Lead    Mid  Senior
country
Australia         17.37  17.82  17.59   17.44
Brazil            17.25  17.69  17.49   17.46
Canada            17.45  17.54  17.56   17.55
France            17.68  16.99  17.68   17.25
Germany           17.57  17.27  17.26   17.43
India             17.48  17.24  17.78   17.59
Japan             17.37  17.45  17.71   17.72
Netherlands       17.40  17.52  17.72   17.39
Singapore         17.55  17.67  17.72   17.54
UAE               17.33  17.58  17.41   17.36
UK                17.53  17.47  17.72   17.83
USA               17.55  17.74  17.56   17.72

## Average Skill Demand by AI Specialization and Experience Level

**Business Question:** Analyze **average skill demand by ai specialization and experience level** to identify multi-dimensional hiring patterns, skill demand, recruitment complexity, and talent market opportunities.

In [618]:
# Average Skill Demand by AI Specialization and Experience Level

pd.pivot_table(
    df,
    values="skill_demand_score",
    index="ai_specialization",
    columns="experience_level",
    aggfunc="mean"
).round(2)

experience_level        Entry   Lead    Mid  Senior
ai_specialization
Analytics               50.54  50.54  51.34   50.36
Computer Vision         50.06  49.98  50.11   50.30
Forecasting             50.74  50.68  50.46   51.11
Generative AI           51.11  50.30  50.40   50.11
LLM                     51.56  50.94  50.75   50.09
MLOps                   50.12  50.64  50.04   50.92
NLP                     50.10  49.93  51.18   50.39
Reinforcement Learning  49.04  51.23  49.98   49.73

## Average Hiring Difficulty by Job Role and Experience Level

**Business Question:** Analyze **average hiring difficulty by job role and experience level** to identify multi-dimensional hiring patterns, skill demand, recruitment complexity, and talent market opportunities.

In [619]:
# Average Hiring Difficulty by Job Role and Experience Level

pd.pivot_table(
    df,
    values="hiring_difficulty_score",
    index="job_role",
    columns="experience_level",
    aggfunc="mean"
).round(2)

experience_level           Entry   Lead    Mid  Senior
job_role
AI Engineer                54.49  55.31  55.12   55.22
AI Software Engineer       54.60  55.14  54.78   55.20
Computer Vision Engineer   55.08  54.93  54.98   55.10
Data Analyst               54.57  55.70  54.94   55.11
Data Scientist             55.63  54.80  54.78   54.96
Machine Learning Engineer  54.94  55.07  54.91   55.29
NLP Engineer               55.33  54.52  55.17   55.44
Research Scientist         55.42  55.05  54.77   54.60

## Average Interview Rounds by Industry and Experience Level

**Business Question:** Analyze **average interview rounds by industry and experience level** to identify multi-dimensional hiring patterns, skill demand, recruitment complexity, and talent market opportunities.

In [620]:
# Average Interview Rounds by Industry and Experience Level

pd.pivot_table(
    df,
    values="interview_rounds",
    index="industry",
    columns="experience_level",
    aggfunc="mean"
).round(2)

experience_level  Entry  Lead   Mid  Senior
industry
Automotive         4.49  4.47  4.49    4.51
Consulting         4.54  4.51  4.52    4.47
Education          4.49  4.50  4.50    4.46
Energy             4.51  4.49  4.48    4.54
Finance            4.58  4.54  4.50    4.43
Gaming             4.54  4.41  4.54    4.53
Healthcare         4.49  4.45  4.43    4.45
Retail             4.48  4.52  4.44    4.48
Tech               4.55  4.46  4.57    4.52
Telecom            4.48  4.44  4.50    4.53

## Job Openings by Country and Industry

**Business Question:** Analyze **job openings by country and industry** to identify multi-dimensional hiring patterns, skill demand, recruitment complexity, and talent market opportunities.

In [621]:
# Job Openings by Country and Industry

pd.crosstab(
    index=df["country"],
    columns=df["industry"],
    values=df["job_openings"],
    aggfunc="mean"
).round(2)

industry,Automotive,Consulting,Education,Energy,Finance,Gaming,Healthcare,Retail,Tech,Telecom
country,,,,,,,,,,
Australia,17.66,17.33,17.84,17.17,17.63,18.09,17.43,17.41,17.34,17.70
Brazil,17.38,18.22,17.09,17.43,17.44,17.27,17.72,17.12,17.65,17.40
Canada,17.30,17.59,17.32,17.94,17.58,17.61,17.75,17.20,17.06,17.98
France,17.79,17.03,17.13,17.33,16.97,17.18,17.87,17.56,17.53,17.60
Germany,17.53,17.24,17.50,17.34,16.86,17.44,17.57,17.32,17.43,17.55
India,17.49,17.17,17.59,17.40,17.70,17.43,18.17,17.33,17.37,17.51
Japan,17.35,17.09,17.37,17.97,17.85,17.45,17.62,17.38,17.90,17.65
Netherlands,17.49,17.12,17.72,17.69,17.79,17.41,17.62,17.54,17.30,17.43
Singapore,17.49,17.62,17.49,17.71,18.04,17.82,17.48,17.39,17.45,17.65
UAE,17.35,17.58,16.77,17.68,17.84,17.27,16.98,17.41,17.88,17.48
UK,17.23,17.79,17.38,17.70,17.36,17.67,17.68,17.85,18.02,17.68
USA,17.24,17.42,17.97,17.57,17.55,17.45,17.85,17.82,17.54,18.10

## Skill Demand by Country and AI Specialization

**Business Question:** Analyze **skill demand by country and ai specialization** to identify multi-dimensional hiring patterns, skill demand, recruitment complexity, and talent market opportunities.

In [622]:
# Skill Demand by Country and AI Specialization

pd.crosstab(
    index=df["country"],
    columns=df["ai_specialization"],
    values=df["skill_demand_score"],
    aggfunc="mean"
).round(2)

ai_specialization,Analytics,Computer Vision,Forecasting,Generative AI,LLM,MLOps,NLP,Reinforcement Learning
country,,,,,,,,
Australia,50.82,50.56,52.64,48.70,50.99,50.58,51.05,50.55
Brazil,49.17,50.20,50.46,51.23,49.71,50.18,49.95,49.38
Canada,52.23,49.23,51.01,51.12,50.42,49.03,49.92,49.71
France,50.42,48.04,50.88,50.84,49.78,50.98,49.43,51.24
Germany,50.23,51.04,49.45,51.05,51.96,49.33,48.53,49.94
India,50.96,48.85,51.29,49.32,53.11,50.61,50.66,49.51
Japan,51.82,50.97,50.33,51.38,51.34,51.66,50.48,49.92
Netherlands,50.03,49.77,50.99,49.22,51.09,51.23,51.12,49.46
Singapore,50.40,50.38,49.67,50.97,49.37,49.76,51.96,49.73
UAE,51.18,50.40,50.91,49.46,51.62,49.93,51.35,49.21
UK,50.45,50.58,50.88,50.32,49.61,50.39,50.66,50.07
USA,50.74,51.26,50.39,52.16,51.02,51.47,49.75,51.16

## Hiring Difficulty by Job Role and AI Specialization

**Business Question:** Analyze **hiring difficulty by job role and ai specialization** to identify multi-dimensional hiring patterns, skill demand, recruitment complexity, and talent market opportunities.

In [623]:
# Hiring Difficulty by Job Role and AI Specialization

pd.crosstab(
    index=df["job_role"],
    columns=df["ai_specialization"],
    values=df["hiring_difficulty_score"],
    aggfunc="mean"
).round(2)

ai_specialization,Analytics,Computer Vision,Forecasting,Generative AI,LLM,MLOps,NLP,Reinforcement Learning
job_role,,,,,,,,
AI Engineer,55.00,54.88,55.51,54.77,54.99,54.89,55.92,54.32
AI Software Engineer,55.27,55.09,54.51,54.38,55.26,54.92,55.26,54.78
Computer Vision Engineer,54.96,54.61,54.51,55.32,54.94,55.36,55.40,55.10
Data Analyst,53.81,55.72,54.56,54.71,55.16,55.30,55.58,55.71
Data Scientist,56.04,55.59,54.52,54.81,54.30,54.99,54.69,55.35
Machine Learning Engineer,54.93,54.55,54.85,54.75,56.18,54.77,55.41,55.00
NLP Engineer,54.82,54.98,55.43,55.59,54.83,56.13,54.57,54.57
Research Scientist,55.48,54.13,55.70,55.23,54.92,54.16,55.25,54.88

# Talent Market Intelligence - Feature Engineering

This notebook creates engineered talent market metrics to measure hiring demand, market opportunities, recruitment competitiveness, and skill value. Each engineered feature is introduced with a business question followed by its implementation.

## Talent Demand Index

**Business Question:** Evaluate **talent demand index** to derive actionable talent market intelligence, identify high-opportunity segments, and support strategic recruitment planning.

In [624]:
# Talent Demand Index

df["talent_demand_index"] = (
    (
        df["job_openings"] +
        df["skill_demand_score"] +
        df["ai_adoption_score"]
    ) / 3
).round(2)

## Hiring Efficiency Score

**Business Question:** Evaluate **hiring efficiency score** to derive actionable talent market intelligence, identify high-opportunity segments, and support strategic recruitment planning.

In [625]:
# Hiring Efficiency Score

df["hiring_efficiency_score"] = (
    df["job_openings"] /
    (df["interview_rounds"] + 1)
).round(2)

## Market Opportunity Index

**Business Question:** Evaluate **market opportunity index** to derive actionable talent market intelligence, identify high-opportunity segments, and support strategic recruitment planning.

In [626]:
# Market Opportunity Index

df["market_opportunity_index"] = (
    (
        df["job_openings"] +
        df["career_growth_score"] +
        df["salary_percentile"]
    ) / 3
).round(2)

## Skill Premium Index

**Business Question:** Evaluate **skill premium index** to derive actionable talent market intelligence, identify high-opportunity segments, and support strategic recruitment planning.

In [627]:
# Skill Premium Index

df["skill_premium_index"] = (
    (
        df["skill_demand_score"] *
        df["salary_percentile"]
    ) / 100
).round(2)

## Recruitment Competitiveness Score

**Business Question:** Evaluate **recruitment competitiveness score** to derive actionable talent market intelligence, identify high-opportunity segments, and support strategic recruitment planning.

In [628]:
# Recruitment Competitiveness Score

df["recruitment_competitiveness_score"] = (
    (
        df["skill_demand_score"] +
        df["hiring_difficulty_score"] +
        (df["interview_rounds"] * 10)
    ) / 3
).round(2)

## Engineered Metrics Summary

**Business Question:** Evaluate **engineered metrics summary** to derive actionable talent market intelligence, identify high-opportunity segments, and support strategic recruitment planning.

In [629]:
# Engineered Metrics Summary

df[[
    "talent_demand_index",
    "hiring_efficiency_score",
    "market_opportunity_index",
    "skill_premium_index",
    "recruitment_competitiveness_score"
]].describe().round(2)

,talent_demand_index,hiring_efficiency_score,market_opportunity_index,skill_premium_index,recruitment_competitiveness_score
count,90000.00,90000.00,90000.00,90000.00,90000.00
mean,46.45,3.56,41.75,25.48,50.15
std,10.98,2.10,10.84,22.21,12.69
min,12.33,0.12,10.33,0.01,7.33
25%,38.00,2.12,33.33,7.04,41.02
50%,46.33,3.17,41.67,19.17,50.17
75%,55.00,4.67,50.33,38.94,59.25
max,78.33,16.67,74.33,100.00,90.00

## Top 10 Talent Demand

**Business Question:** Evaluate **top 10 talent demand** to derive actionable talent market intelligence, identify high-opportunity segments, and support strategic recruitment planning.

In [630]:
# Top 10 Talent Demand

df.nlargest(
    10,
    "talent_demand_index"
)[[
    "job_role",
    "country",
    "talent_demand_index"
]]

                       job_role    country  talent_demand_index
29793        Research Scientist  Australia                78.33
58917               AI Engineer        USA                78.33
16467        Research Scientist     France                78.00
37807  Computer Vision Engineer  Australia                78.00
41766              Data Analyst     Brazil                77.67
2592       AI Software Engineer  Singapore                77.33
35447            Data Scientist  Australia                77.00
65697               AI Engineer         UK                77.00
89055               AI Engineer      Japan                77.00
33890        Research Scientist        USA                76.33

## Top 10 Market Opportunity

**Business Question:** Evaluate **top 10 market opportunity** to derive actionable talent market intelligence, identify high-opportunity segments, and support strategic recruitment planning.

In [631]:
# Top 10 Market Opportunity

df.nlargest(
    10,
    "market_opportunity_index"
)[[
    "job_role",
    "country",
    "market_opportunity_index"
]]

                        job_role      country  market_opportunity_index
51909   Computer Vision Engineer          UAE                     74.33
86042         Research Scientist       Canada                     74.00
36585         Research Scientist    Singapore                     73.67
35949       AI Software Engineer           UK                     73.33
73217       AI Software Engineer        Japan                     72.67
78172               Data Analyst       Brazil                     72.67
15347                AI Engineer          UAE                     72.33
22474   Computer Vision Engineer       Canada                     72.33
47822  Machine Learning Engineer           UK                     72.33
49709   Computer Vision Engineer  Netherlands                     72.33

## Top 10 Skill Premium

**Business Question:** Evaluate **top 10 skill premium** to derive actionable talent market intelligence, identify high-opportunity segments, and support strategic recruitment planning.

In [632]:
# Top 10 Skill Premium

df.nlargest(
    10,
    "skill_premium_index"
)[[
    "job_role",
    "country",
    "skill_premium_index"
]]

                   job_role    country  skill_premium_index
6394           Data Analyst     Brazil                100.0
7957     Research Scientist  Australia                100.0
16022  AI Software Engineer      Japan                100.0
18795          NLP Engineer    Germany                100.0
30724        Data Scientist      Japan                100.0
54484        Data Scientist        UAE                100.0
54846          NLP Engineer  Australia                100.0
54858          NLP Engineer  Singapore                100.0
73370          NLP Engineer  Singapore                100.0
75717          NLP Engineer      Japan                100.0

## Correlation of Engineered Metrics

**Business Question:** Evaluate **correlation of engineered metrics** to derive actionable talent market intelligence, identify high-opportunity segments, and support strategic recruitment planning.

In [633]:
# Correlation of Engineered Metrics

df[[
    "job_openings",
    "skill_demand_score",
    "talent_demand_index",
    "hiring_efficiency_score",
    "market_opportunity_index",
    "skill_premium_index",
    "recruitment_competitiveness_score"
]].corr().round(2)

,job_openings,skill_demand_score,talent_demand_index,hiring_efficiency_score,market_opportunity_index,skill_premium_index,recruitment_competitiveness_score
job_openings,1.00,-0.00,0.24,0.76,0.23,-0.01,-0.00
skill_demand_score,-0.00,1.00,0.88,-0.00,-0.00,0.65,0.76
talent_demand_index,0.24,0.88,1.00,0.18,0.16,0.57,0.67
hiring_efficiency_score,0.76,-0.00,0.18,1.00,0.18,-0.00,-0.26
market_opportunity_index,0.23,-0.00,0.16,0.18,1.00,0.58,-0.00
skill_premium_index,-0.01,0.65,0.57,-0.00,0.58,1.00,0.50
recruitment_competitiveness_score,-0.00,0.76,0.67,-0.26,-0.00,0.50,1.00

# 05 Employee Experience Intelligence

# Module 5: Employee Experience Intelligence

## Objective

Analyze the factors affecting employee satisfaction, work-life balance, and overall employee experience in the AI workforce.

### Business Questions

- Which work mode provides the best work-life balance?
- Does company rating improve employee satisfaction?
- Do working hours affect employee happiness?
- Which countries have the happiest employees?
- What factors contribute to employee experience?

## Employee Experience Overview

**Business Question:** What is the overall distribution of employee experience indicators across the AI workforce?

In [634]:
# Employee Experience Overview

df[[
    "employee_satisfaction",
    "work_life_balance_score",
    "weekly_hours",
    "vacation_days",
    "company_rating"
]].describe().round(2)

,employee_satisfaction,work_life_balance_score,weekly_hours,vacation_days,company_rating
count,90000.00,90000.00,90000.00,90000.00,90000.00
mean,72.73,69.15,45.48,19.99,4.00
std,8.12,13.21,5.48,6.07,0.46
min,42.00,25.00,36.00,10.00,3.20
25%,67.00,59.00,40.70,15.00,3.60
50%,73.00,69.00,45.50,20.00,4.00
75%,78.00,79.00,50.20,25.00,4.40
max,99.00,98.00,55.00,30.00,4.80

## Employee Satisfaction by Work Mode

**Business Question:** How does employee satisfaction vary across work modes?

In [635]:
# Employee Satisfaction by Work Mode

df.groupby("work_mode")[
    "employee_satisfaction"
].agg(["mean", "median", "min", "max"]).round(2)

            mean  median  min  max
work_mode
Hybrid     72.74    73.0   43   99
Onsite     72.73    73.0   42   99
Remote     72.72    73.0   42   99

## Work-Life Balance by Work Mode

**Business Question:** Which work mode provides the best work-life balance?

In [636]:
# Work-Life Balance by Work Mode

df.groupby("work_mode")[
    "work_life_balance_score"
].mean().round(2)

work_mode
Hybrid    69.08
Onsite    69.17
Remote    69.19
Name: work_life_balance_score, dtype: float64

## Employee Satisfaction by Country

**Business Question:** Which countries report the highest employee satisfaction?

In [637]:
# Employee Satisfaction by Country

df.groupby("country")[
    "employee_satisfaction"
].mean().sort_values(ascending=False).round(2)

country
USA            76.29
Singapore      74.89
Australia      74.11
Canada         73.84
Netherlands    73.46
UK             73.37
Germany        73.09
Japan          72.91
France         72.55
UAE            72.45
Brazil         68.39
India          67.43
Name: employee_satisfaction, dtype: float64

## Employee Satisfaction by Industry

**Business Question:** Which industries provide the best employee experience?

In [638]:
# Employee Satisfaction by Industry

df.groupby("industry")[
    "employee_satisfaction"
].mean().sort_values(ascending=False).round(2)

industry
Retail        72.81
Tech          72.81
Automotive    72.74
Consulting    72.74
Healthcare    72.74
Gaming        72.73
Finance       72.71
Telecom       72.70
Education     72.70
Energy        72.66
Name: employee_satisfaction, dtype: float64

## Employee Satisfaction by Company Rating

**Business Question:** Does company rating influence employee satisfaction?

In [639]:
# Employee Satisfaction by Company Rating

df.groupby("company_rating")[
    "employee_satisfaction"
].mean().round(2)

company_rating
3.20    72.28
3.21    72.98
3.22    72.82
3.23    72.34
3.24    72.85
        ...
4.76    72.68
4.77    72.35
4.78    73.27
4.79    73.16
4.80    73.53
Name: employee_satisfaction, Length: 161, dtype: float64

# Employee Experience Intelligence - Relationship Analytics

## Correlation with Employee Satisfaction

**Business Question:** Which variables have the strongest relationship with employee satisfaction?

In [640]:
# Correlation with Employee Satisfaction

employee_corr = (
    df[[
        "employee_satisfaction",
        "work_life_balance_score",
        "weekly_hours",
        "vacation_days",
        "company_rating",
        "career_growth_score",
        "salary_usd",
        "job_security_score"
    ]]
    .corr()["employee_satisfaction"]
    .sort_values(ascending=False)
    .round(2)
)

employee_corr

employee_satisfaction      1.00
salary_usd                 0.63
job_security_score         0.48
work_life_balance_score    0.43
career_growth_score        0.01
company_rating             0.00
vacation_days             -0.01
weekly_hours              -0.34
Name: employee_satisfaction, dtype: float64

## Work Mode vs Work-Life Balance

**Business Question:** How does work-life balance vary across work modes and experience levels?

In [641]:
# Work Mode vs Work-Life Balance

pd.pivot_table(
    df,
    values="work_life_balance_score",
    index="work_mode",
    columns="experience_level",
    aggfunc="mean"
).round(2)

experience_level  Entry   Lead    Mid  Senior
work_mode
Hybrid            69.37  69.08  68.65   69.23
Onsite            69.01  69.10  69.36   69.19
Remote            69.06  69.56  69.03   69.11

## Company Rating vs Satisfaction

**Business Question:** How does company rating influence satisfaction?

In [642]:
# Company Rating vs Satisfaction

pd.pivot_table(
    df,
    values="employee_satisfaction",
    index="company_rating",
    columns="work_mode",
    aggfunc="mean"
).round(2)

work_mode       Hybrid  Onsite  Remote
company_rating
3.20             71.89   72.93   72.04
3.21             74.04   72.39   72.56
3.22             73.39   72.27   72.77
3.23             72.98   71.77   72.24
3.24             72.61   73.21   72.80
...                ...     ...     ...
4.76             72.26   72.53   73.20
4.77             71.70   72.93   72.41
4.78             72.53   73.41   73.87
4.79             73.29   72.92   73.31
4.80             73.73   73.45   73.38

[161 rows x 3 columns]

## Weekly Hours vs Employee Satisfaction

**Business Question:** How do weekly working hours affect satisfaction?

In [643]:
# Weekly Hours vs Employee Satisfaction

pd.crosstab(
    index=df["weekly_hours"],
    columns=df["work_mode"],
    values=df["employee_satisfaction"],
    aggfunc="mean"
).round(2)

work_mode     Hybrid  Onsite  Remote
weekly_hours
36.0           77.07   77.09   77.25
36.1           78.01   76.01   77.35
36.2           77.47   77.96   77.28
36.3           77.37   76.73   77.20
36.4           78.02   77.68   76.96
...              ...     ...     ...
54.6           68.69   69.14   67.10
54.7           68.48   68.41   67.72
54.8           69.13   67.67   67.13
54.9           67.87   68.17   68.80
55.0           68.10   67.61   67.18

[191 rows x 3 columns]

# Employee Experience Intelligence - Feature Engineering

## Employee Experience Index

**Business Question:** Can overall employee experience be summarized into a single index?

In [644]:
# Employee Experience Index

df["employee_experience_index"] = (
    (
        df["employee_satisfaction"] +
        df["work_life_balance_score"] +
        df["company_rating"] * 20
    ) / 3
).round(2)

## Wellbeing Score

**Business Question:** How can employee wellbeing be measured?

In [645]:
# Wellbeing Score

df["wellbeing_score"] = (
    (
        df["employee_satisfaction"] +
        df["work_life_balance_score"] +
        (100 - df["weekly_hours"])
    ) / 3
).round(2)

## Engineered Metrics Summary

**Business Question:** What is the statistical summary of the engineered metrics?

In [646]:
# Engineered Metrics Summary

df[[
    "employee_experience_index",
    "wellbeing_score"
]].describe().round(2)

       employee_experience_index  wellbeing_score
count                   90000.00         90000.00
mean                       73.95            65.47
std                         6.82             7.56
min                        49.40            40.90
25%                        69.20            59.77
50%                        73.93            65.50
75%                        78.73            71.17
max                        97.40            86.77

## Top Employee Experience

**Business Question:** Which professionals have the highest employee experience scores?

In [647]:
# Top Employee Experience

df.nlargest(
    10,
    "employee_experience_index"
)[[
    "job_role",
    "country",
    "employee_experience_index"
]]

                        job_role    country  employee_experience_index
31338  Machine Learning Engineer        USA                      97.40
89246               NLP Engineer     Canada                      97.20
32015  Machine Learning Engineer  Australia                      96.07
80164             Data Scientist     France                      95.87
2788                Data Analyst        USA                      95.60
4356                NLP Engineer        USA                      95.60
84843         Research Scientist         UK                      95.60
1744          Research Scientist      India                      95.33
3340   Machine Learning Engineer    Germany                      95.33
38746  Machine Learning Engineer        USA                      95.33

# 06 Recruitment Intelligence

# Module 6: Recruitment Intelligence

## Objective

Analyze recruitment effectiveness by evaluating offer acceptance, interview process efficiency, hiring difficulty, and candidate decision patterns.

### Business Questions

- What influences offer acceptance?
- Does salary improve offer acceptance?
- Does hiring difficulty reduce acceptance?
- Which countries have the highest offer acceptance?
- Which job roles experience better recruitment success?

## Recruitment Overview

**Business Question:** What are the overall recruitment metrics?

In [648]:
df[[
    "offer_acceptance_rate",
    "interview_rounds",
    "hiring_difficulty_score"
]].describe().round(2)

       offer_acceptance_rate  interview_rounds  hiring_difficulty_score
count               90000.00           90000.0                 90000.00
mean                   75.01               4.5                    55.03
std                    11.51               1.7                    17.90
min                    55.00               2.0                     0.00
25%                    65.07               3.0                    42.88
50%                    75.00               4.0                    55.07
75%                    84.99               6.0                    67.12
max                    95.00               7.0                   100.00

## Offer Acceptance by Country

**Business Question:** How does offer acceptance vary across countries?

In [649]:
df.groupby("country")["offer_acceptance_rate"].agg(["mean","median","min","max"]).round(2)

              mean  median    min    max
country
Australia    74.93   74.87  55.00  95.00
Brazil       75.00   74.87  55.00  95.00
Canada       75.13   75.10  55.00  94.99
France       75.33   75.45  55.01  95.00
Germany      75.05   74.99  55.00  94.99
India        74.90   75.02  55.01  94.99
Japan        75.04   75.16  55.00  94.99
Netherlands  74.97   75.06  55.00  95.00
Singapore    74.94   74.93  55.00  94.99
UAE          74.91   74.94  55.01  95.00
UK           75.06   75.06  55.00  95.00
USA          74.85   74.81  55.01  95.00

## Offer Acceptance by Job Role

**Business Question:** Which job roles have the highest offer acceptance?

In [650]:
df.groupby("job_role")["offer_acceptance_rate"].mean().sort_values(ascending=False).round(2)

job_role
Data Analyst                 75.19
Machine Learning Engineer    75.12
Data Scientist               74.99
Computer Vision Engineer     74.99
Research Scientist           74.99
AI Software Engineer         74.96
NLP Engineer                 74.93
AI Engineer                  74.89
Name: offer_acceptance_rate, dtype: float64

## Offer Acceptance by AI Specialization

**Business Question:** Which AI specializations have the highest offer acceptance?

In [651]:
df.groupby("ai_specialization")["offer_acceptance_rate"].mean().sort_values(ascending=False).round(2)

ai_specialization
LLM                       75.21
NLP                       75.06
Analytics                 75.03
MLOps                     75.01
Computer Vision           75.01
Forecasting               74.94
Reinforcement Learning    74.92
Generative AI             74.90
Name: offer_acceptance_rate, dtype: float64

## Offer Acceptance by Industry

**Business Question:** How does offer acceptance vary across industries?

In [652]:
df.groupby("industry")["offer_acceptance_rate"].mean().sort_values(ascending=False).round(2)

industry
Retail        75.11
Finance       75.09
Telecom       75.05
Education     75.04
Energy        75.02
Consulting    74.99
Gaming        74.97
Tech          74.96
Automotive    74.93
Healthcare    74.93
Name: offer_acceptance_rate, dtype: float64

# Recruitment Intelligence - Relationship Analytics

## Correlation with Offer Acceptance

**Business Question:** Which variables influence offer acceptance?

In [653]:
recruitment_corr=(df[[
"offer_acceptance_rate","salary_usd","bonus_usd","interview_rounds",
"hiring_difficulty_score","career_growth_score","company_rating",
"employee_satisfaction"]].corr()["offer_acceptance_rate"].sort_values(ascending=False).round(2))
recruitment_corr

offer_acceptance_rate      1.00
career_growth_score        0.00
employee_satisfaction      0.00
salary_usd                -0.00
bonus_usd                 -0.00
interview_rounds          -0.00
company_rating            -0.00
hiring_difficulty_score   -0.01
Name: offer_acceptance_rate, dtype: float64

## Offer Acceptance by Experience Level

**Business Question:** How does offer acceptance vary by experience and work mode?

In [654]:
pd.pivot_table(df,values="offer_acceptance_rate",index="experience_level",columns="work_mode",aggfunc="mean").round(2)

work_mode         Hybrid  Onsite  Remote
experience_level
Entry              74.86   74.91   75.01
Lead               74.91   75.05   74.97
Mid                74.91   74.98   75.25
Senior             75.17   75.05   75.04

## Offer Acceptance by Industry

**Business Question:** How does offer acceptance vary by industry and experience?

In [655]:
pd.pivot_table(df,values="offer_acceptance_rate",index="industry",columns="experience_level",aggfunc="mean").round(2)

experience_level  Entry   Lead    Mid  Senior
industry
Automotive        74.80  74.93  75.08   74.92
Consulting        74.94  74.82  75.02   75.20
Education         74.80  74.68  75.16   75.52
Energy            74.78  75.19  75.28   74.85
Finance           74.94  75.44  74.71   75.27
Gaming            74.77  74.90  75.19   75.00
Healthcare        75.24  74.85  74.71   74.90
Retail            75.22  75.14  75.05   75.04
Tech              74.54  74.73  75.26   75.30
Telecom           75.24  75.08  75.01   74.86

## Hiring Difficulty by Job Role

**Business Question:** How does hiring difficulty vary across job roles?

In [656]:
pd.crosstab(index=df["job_role"],columns=df["experience_level"],values=df["hiring_difficulty_score"],aggfunc="mean").round(2)

experience_level           Entry   Lead    Mid  Senior
job_role
AI Engineer                54.49  55.31  55.12   55.22
AI Software Engineer       54.60  55.14  54.78   55.20
Computer Vision Engineer   55.08  54.93  54.98   55.10
Data Analyst               54.57  55.70  54.94   55.11
Data Scientist             55.63  54.80  54.78   54.96
Machine Learning Engineer  54.94  55.07  54.91   55.29
NLP Engineer               55.33  54.52  55.17   55.44
Research Scientist         55.42  55.05  54.77   54.60

# Recruitment Intelligence - Feature Engineering

## Recruitment Success Index

**Business Question:** Can recruitment effectiveness be summarized into one metric?

In [657]:
df["recruitment_success_index"]=((df["offer_acceptance_rate"]+(100-df["hiring_difficulty_score"])+(100-(df["interview_rounds"]*10)))/3).round(2)

## Candidate Attraction Score

**Business Question:** Can candidate attraction be summarized into one metric?

In [658]:
df["candidate_attraction_score"]=((df["offer_acceptance_rate"]+df["salary_percentile"]+df["company_rating"]*20)/3).round(2)

## Recruitment Metrics Summary

**Business Question:** What is the summary of engineered metrics?

In [659]:
df[["recruitment_success_index","candidate_attraction_score"]].describe().round(2)

       recruitment_success_index  candidate_attraction_score
count                   90000.00                    90000.00
mean                       58.34                       68.50
std                         9.12                       10.81
min                        28.65                       40.39
25%                        51.94                       60.06
50%                        58.35                       68.49
75%                        64.71                       76.91
max                        91.06                       96.47

## Top Recruitment Success

**Business Question:** Which records have the highest recruitment success index?

In [660]:
df.nlargest(10,"recruitment_success_index")[["job_role","country","recruitment_success_index"]]

                        job_role    country  recruitment_success_index
55238             Data Scientist      Japan                      91.06
39515   Computer Vision Engineer      Japan                      90.39
67969               Data Analyst        UAE                      90.14
86542   Computer Vision Engineer  Australia                      90.00
81287   Computer Vision Engineer      India                      89.60
19453               Data Analyst        UAE                      89.23
710           Research Scientist  Australia                      88.90
18848  Machine Learning Engineer    Germany                      88.80
76264       AI Software Engineer        USA                      88.76
82542   Computer Vision Engineer     Canada                      88.53