# Module 4: Talent Market Intelligence

## Objective

Analyze hiring demand, skill demand, job openings, and recruitment competitiveness to understand the current AI talent market.

### Business Questions

- Which countries have the highest hiring demand?
- Which job roles have the most openings?
- Which AI specializations are most demanded?
- Which industries hire the most AI professionals?
- Does Skill Demand Score influence job openings?
- Which factors drive hiring demand?

In [73]:
import warnings
import platform
import numpy as np
import pandas as pd

# Configure execution environment and suppress warnings
warnings.filterwarnings("ignore")

# Optimize pandas display configurations for comprehensive data inspection.
pd.set_option("display.max_columns", None)
pd.set_option("display.max_rows", 100)
pd.set_option("display.width", None)

# Log framework metadata and verification metrics.

print("Environment Information")
print("-" * 22)
print(f"Python Version : {platform.python_version()}")
print(f"Pandas Version : {pd.__version__}")
print(f"NumPy Version  : {np.__version__}")

Environment Information
----------------------
Python Version : 3.14.6
Pandas Version : 3.0.3
NumPy Version  : 2.4.6

In [74]:
# Load target dataset

DATA_PATH = "../../../data/processed/cleaned_ai_jobs.csv"
df = pd.read_csv(DATA_PATH)
print("\nDataset Loaded Successfully")

# Execute descriptive matrix shape verification.

print("\nDataset Shape")
print("-" * 16)

total_rows, total_columns = df.shape

print(f"Rows    : {total_rows:,}")
print(f"Columns : {total_columns}")
print("-" * 16)

# Display a quick preview of the dataset schema.

display(df.head())

Dataset Loaded Successfully

Dataset Shape
----------------
Rows    : 90,000
Columns : 35
----------------

,id,country,job_role,ai_specialization,experience_level,experience_years,salary_usd,bonus_usd,education_required,industry,company_size,interview_rounds,year,work_mode,weekly_hours,company_rating,job_openings,hiring_difficulty_score,layoff_risk,ai_adoption_score,company_funding_billion,economic_index,ai_maturity_years,offer_acceptance_rate,tax_rate_percent,vacation_days,skill_demand_score,automation_risk,job_security_score,career_growth_score,work_life_balance_score,promotion_speed,salary_percentile,cost_of_living_index,employee_satisfaction
0,1,UAE,Machine Learning Engineer,Reinforcement Learning,Entry,0,66465,5395,Master,Automotive,Small,7,2020,Remote,44.7,3.67,10,52.77,0.404,91,3.30,78.65,13,60.58,20.8,27,12,76,57,65,73,15,55,1.23,76
1,2,USA,AI Engineer,LLM,Entry,1,75507,11713,Bootcamp,Retail,Small,3,2021,Onsite,48.9,4.26,27,53.11,0.387,71,4.39,62.14,13,75.80,28.4,27,54,29,69,60,51,15,58,0.87,67
2,3,Brazil,Research Scientist,Analytics,Entry,0,41660,5268,Phd,Healthcare,Large,3,2020,Remote,46.8,4.78,10,76.40,0.415,69,5.04,87.47,8,62.95,12.2,13,12,49,70,59,68,37,13,2.13,61
3,4,India,AI Software Engineer,Computer Vision,Senior,6,43268,7975,Diploma,Tech,Large,2,2026,Onsite,52.2,4.34,23,59.34,0.115,74,4.38,86.84,7,77.45,35.1,30,80,47,79,65,55,46,74,1.49,56
4,5,Germany,Machine Learning Engineer,Computer Vision,Entry,0,69119,4758,Master,Retail,Medium,2,2021,Hybrid,46.7,4.49,17,72.30,0.311,68,6.67,79.84,7,89.86,36.1,24,82,47,64,52,69,17,21,0.87,72

# Talent Market Intelligence - Foundation Analysis

This notebook organizes the foundational Talent Market Intelligence analysis into individual business questions. Each analysis is presented with a dedicated markdown cell followed by a Python code cell for clarity and presentation.

## Talent Market Overview

**Business Question:** Analyze **talent market overview** to understand talent demand, hiring complexity, and labor market dynamics for strategic workforce planning.

In [75]:
# Talent Market Overview

df[[
    "job_openings",
    "skill_demand_score",
    "hiring_difficulty_score",
    "interview_rounds"
]].describe().round(2)

,job_openings,skill_demand_score,hiring_difficulty_score,interview_rounds
count,90000.00,90000.00,90000.00,90000.0
mean,17.52,50.46,55.03,4.5
std,7.85,28.85,17.90,1.7
min,1.00,1.00,0.00,2.0
25%,12.00,25.00,42.88,3.0
50%,17.00,51.00,55.07,4.0
75%,23.00,75.00,67.12,6.0
max,50.00,100.00,100.00,7.0

## Job Openings by Country

**Business Question:** Analyze **job openings by country** to understand talent demand, hiring complexity, and labor market dynamics for strategic workforce planning.

In [76]:
# Job Openings by Country

df.groupby("country")[
    "job_openings"
].agg(["mean", "median", "min", "max"]).round(2)

              mean  median  min  max
country
Australia    17.56    17.0    1   48
Brazil       17.47    17.0    1   45
Canada       17.53    17.0    1   45
France       17.40    17.0    1   47
Germany      17.38    17.0    1   45
India        17.52    17.0    1   45
Japan        17.56    18.0    1   46
Netherlands  17.51    17.0    1   50
Singapore    17.62    18.0    1   48
UAE          17.42    17.0    1   47
UK           17.64    18.0    1   47
USA          17.65    18.0    1   47

## Job Openings by Job Role

**Business Question:** Analyze **job openings by job role** to understand talent demand, hiring complexity, and labor market dynamics for strategic workforce planning.

In [77]:
# Job Openings by Job Role

df.groupby("job_role")[
    "job_openings"
].mean().sort_values(ascending=False).round(2)

job_role
AI Software Engineer         17.64
Computer Vision Engineer     17.59
Machine Learning Engineer    17.55
Data Analyst                 17.52
AI Engineer                  17.50
Data Scientist               17.47
Research Scientist           17.46
NLP Engineer                 17.43
Name: job_openings, dtype: float64

## Job Openings by AI Specialization

**Business Question:** Analyze **job openings by ai specialization** to understand talent demand, hiring complexity, and labor market dynamics for strategic workforce planning.

In [78]:
# Job Openings by AI Specialization

df.groupby("ai_specialization")[
    "job_openings"
].mean().sort_values(ascending=False).round(2)

ai_specialization
Reinforcement Learning    17.57
Analytics                 17.57
Computer Vision           17.55
Forecasting               17.53
Generative AI             17.53
NLP                       17.51
LLM                       17.50
MLOps                     17.42
Name: job_openings, dtype: float64

## Job Openings by Industry

**Business Question:** Analyze **job openings by industry** to understand talent demand, hiring complexity, and labor market dynamics for strategic workforce planning.

In [79]:
# Job Openings by Industry

df.groupby("industry")[
    "job_openings"
].mean().sort_values(ascending=False).round(2)

industry
Healthcare    17.65
Telecom       17.64
Energy        17.58
Finance       17.55
Tech          17.54
Gaming        17.51
Retail        17.44
Automotive    17.44
Consulting    17.44
Education     17.43
Name: job_openings, dtype: float64

## Skill Demand Score by AI Specialization

**Business Question:** Analyze **skill demand score by ai specialization** to understand talent demand, hiring complexity, and labor market dynamics for strategic workforce planning.

In [80]:
# Skill Demand Score by AI Specialization

df.groupby("ai_specialization")[
    "skill_demand_score"
].mean().sort_values(ascending=False).round(2)

ai_specialization
LLM                       50.83
Forecasting               50.75
Analytics                 50.70
Generative AI             50.48
MLOps                     50.43
NLP                       50.40
Computer Vision           50.11
Reinforcement Learning    49.99
Name: skill_demand_score, dtype: float64

## Hiring Difficulty by Job Role

**Business Question:** Analyze **hiring difficulty by job role** to understand talent demand, hiring complexity, and labor market dynamics for strategic workforce planning.

In [81]:
# Hiring Difficulty by Job Role

df.groupby("job_role")[
    "hiring_difficulty_score"
].mean().sort_values(ascending=False).round(2)

job_role
NLP Engineer                 55.11
Data Analyst                 55.08
Machine Learning Engineer    55.05
AI Engineer                  55.04
Data Scientist               55.04
Computer Vision Engineer     55.02
Research Scientist           54.96
AI Software Engineer         54.94
Name: hiring_difficulty_score, dtype: float64

## Interview Rounds by Job Role

**Business Question:** Analyze **interview rounds by job role** to understand talent demand, hiring complexity, and labor market dynamics for strategic workforce planning.

In [82]:
# Interview Rounds by Job Role

df.groupby("job_role")[
    "interview_rounds"
].mean().sort_values(ascending=False).round(2)

job_role
AI Engineer                  4.52
Research Scientist           4.51
Data Analyst                 4.50
AI Software Engineer         4.50
Machine Learning Engineer    4.50
Data Scientist               4.49
Computer Vision Engineer     4.48
NLP Engineer                 4.47
Name: interview_rounds, dtype: float64

# Talent Market Intelligence - Ranking & Elite Segment Analysis

This notebook presents ranking analysis, percentile analysis, and elite talent segmentation for Talent Market Intelligence. Each business question is organized into separate markdown and code cells for a clean, presentation-ready workflow.

## Top 10 Countries by Job Openings

**Business Question:** Analyze **top 10 countries by job openings** to identify high-demand talent segments, benchmark labor market trends, and support strategic hiring decisions.

In [83]:
# Top 10 Countries by Job Openings

df.groupby("country")[
    "job_openings"
].mean().sort_values(ascending=False).head(10).round(2)

country
USA            17.65
UK             17.64
Singapore      17.62
Japan          17.56
Australia      17.56
Canada         17.53
India          17.52
Netherlands    17.51
Brazil         17.47
UAE            17.42
Name: job_openings, dtype: float64

## Top 10 Job Roles by Job Openings

**Business Question:** Analyze **top 10 job roles by job openings** to identify high-demand talent segments, benchmark labor market trends, and support strategic hiring decisions.

In [84]:
# Top 10 Job Roles by Job Openings

df.groupby("job_role")[
    "job_openings"
].mean().sort_values(ascending=False).head(10).round(2)

job_role
AI Software Engineer         17.64
Computer Vision Engineer     17.59
Machine Learning Engineer    17.55
Data Analyst                 17.52
AI Engineer                  17.50
Data Scientist               17.47
Research Scientist           17.46
NLP Engineer                 17.43
Name: job_openings, dtype: float64

## Top 10 AI Specializations by Job Openings

**Business Question:** Analyze **top 10 ai specializations by job openings** to identify high-demand talent segments, benchmark labor market trends, and support strategic hiring decisions.

In [85]:
# Top 10 AI Specializations by Job Openings

df.groupby("ai_specialization")[
    "job_openings"
].mean().sort_values(ascending=False).head(10).round(2)

ai_specialization
Reinforcement Learning    17.57
Analytics                 17.57
Computer Vision           17.55
Forecasting               17.53
Generative AI             17.53
NLP                       17.51
LLM                       17.50
MLOps                     17.42
Name: job_openings, dtype: float64

## Top 10 Industries by Job Openings

**Business Question:** Analyze **top 10 industries by job openings** to identify high-demand talent segments, benchmark labor market trends, and support strategic hiring decisions.

In [86]:
# Top 10 Industries by Job Openings

df.groupby("industry")[
    "job_openings"
].mean().sort_values(ascending=False).head(10).round(2)

industry
Healthcare    17.65
Telecom       17.64
Energy        17.58
Finance       17.55
Tech          17.54
Gaming        17.51
Retail        17.44
Automotive    17.44
Consulting    17.44
Education     17.43
Name: job_openings, dtype: float64

## Top 10 AI Specializations by Skill Demand

**Business Question:** Analyze **top 10 ai specializations by skill demand** to identify high-demand talent segments, benchmark labor market trends, and support strategic hiring decisions.

In [87]:
# Top 10 AI Specializations by Skill Demand

df.groupby("ai_specialization")[
    "skill_demand_score"
].mean().sort_values(ascending=False).head(10).round(2)

ai_specialization
LLM                       50.83
Forecasting               50.75
Analytics                 50.70
Generative AI             50.48
MLOps                     50.43
NLP                       50.40
Computer Vision           50.11
Reinforcement Learning    49.99
Name: skill_demand_score, dtype: float64

## Top 10 Job Roles by Hiring Difficulty

**Business Question:** Analyze **top 10 job roles by hiring difficulty** to identify high-demand talent segments, benchmark labor market trends, and support strategic hiring decisions.

In [88]:
# Top 10 Job Roles by Hiring Difficulty

df.groupby("job_role")[
    "hiring_difficulty_score"
].mean().sort_values(ascending=False).head(10).round(2)

job_role
NLP Engineer                 55.11
Data Analyst                 55.08
Machine Learning Engineer    55.05
AI Engineer                  55.04
Data Scientist               55.04
Computer Vision Engineer     55.02
Research Scientist           54.96
AI Software Engineer         54.94
Name: hiring_difficulty_score, dtype: float64

## Job Openings Quartiles

**Business Question:** Analyze **job openings quartiles** to identify high-demand talent segments, benchmark labor market trends, and support strategic hiring decisions.

In [89]:
# Job Openings Quartiles

df["job_openings"].quantile(
    [0.25, 0.50, 0.75]
).round(2)

0.25    12.0
0.50    17.0
0.75    23.0
Name: job_openings, dtype: float64

## Skill Demand Score Quartiles

**Business Question:** Analyze **skill demand score quartiles** to identify high-demand talent segments, benchmark labor market trends, and support strategic hiring decisions.

In [90]:
# Skill Demand Score Quartiles

df["skill_demand_score"].quantile(
    [0.25, 0.50, 0.75]
).round(2)

0.25    25.0
0.50    51.0
0.75    75.0
Name: skill_demand_score, dtype: float64

## Hiring Difficulty Quartiles

**Business Question:** Analyze **hiring difficulty quartiles** to identify high-demand talent segments, benchmark labor market trends, and support strategic hiring decisions.

In [91]:
# Hiring Difficulty Quartiles

df["hiring_difficulty_score"].quantile(
    [0.25, 0.50, 0.75]
).round(2)

0.25    42.88
0.50    55.07
0.75    67.12
Name: hiring_difficulty_score, dtype: float64

## Top 10% High Hiring Demand

**Business Question:** Analyze **top 10% high hiring demand** to identify high-demand talent segments, benchmark labor market trends, and support strategic hiring decisions.

In [92]:
# Top 10% High Hiring Demand

high_hiring_demand = (
    df[
        df["job_openings"] >=
        df["job_openings"].quantile(0.90)
    ]
)

high_hiring_demand.head()

,id,country,job_role,ai_specialization,experience_level,experience_years,salary_usd,bonus_usd,education_required,industry,company_size,interview_rounds,year,work_mode,weekly_hours,company_rating,job_openings,hiring_difficulty_score,layoff_risk,ai_adoption_score,company_funding_billion,economic_index,ai_maturity_years,offer_acceptance_rate,tax_rate_percent,vacation_days,skill_demand_score,automation_risk,job_security_score,career_growth_score,work_life_balance_score,promotion_speed,salary_percentile,cost_of_living_index,employee_satisfaction
13,14,Singapore,Data Scientist,NLP,Mid,5,88751,18538,Phd,Consulting,Enterprise,6,2023,Onsite,49.9,3.48,35,40.82,0.140,75,0.64,68.86,9,70.94,30.5,16,70,97,71,48,78,25,94,1.77,77
30,31,Singapore,NLP Engineer,NLP,Mid,3,78117,6947,Diploma,Retail,Small,2,2020,Remote,49.2,3.25,29,76.86,0.220,39,1.75,76.34,14,85.50,38.3,20,53,86,74,35,57,24,95,1.18,73
36,37,Australia,AI Software Engineer,NLP,Lead,19,155111,24453,Master,Automotive,Enterprise,5,2024,Onsite,53.3,3.67,28,72.25,0.114,78,6.01,97.16,9,85.54,16.2,15,79,73,80,63,66,30,39,2.24,75
39,40,USA,Data Analyst,Forecasting,Lead,17,162252,14041,Diploma,Education,Startup,7,2025,Onsite,42.4,3.21,38,53.27,0.051,73,7.37,50.67,6,67.58,36.2,22,64,52,86,62,67,85,32,2.42,83
53,54,Netherlands,Computer Vision Engineer,Analytics,Lead,16,141862,26137,Master,Education,Medium,2,2024,Hybrid,40.3,4.55,31,62.85,0.079,100,9.47,79.58,10,84.41,35.0,17,97,60,86,92,80,28,73,1.51,81

## Top 10% High Skill Demand

**Business Question:** Analyze **top 10% high skill demand** to identify high-demand talent segments, benchmark labor market trends, and support strategic hiring decisions.

In [93]:
# Top 10% High Skill Demand

high_skill_demand = (
    df[
        df["skill_demand_score"] >=
        df["skill_demand_score"].quantile(0.90)
    ]
)

high_skill_demand.head()

,id,country,job_role,ai_specialization,experience_level,experience_years,salary_usd,bonus_usd,education_required,industry,company_size,interview_rounds,year,work_mode,weekly_hours,company_rating,job_openings,hiring_difficulty_score,layoff_risk,ai_adoption_score,company_funding_billion,economic_index,ai_maturity_years,offer_acceptance_rate,tax_rate_percent,vacation_days,skill_demand_score,automation_risk,job_security_score,career_growth_score,work_life_balance_score,promotion_speed,salary_percentile,cost_of_living_index,employee_satisfaction
12,13,Netherlands,AI Engineer,Reinforcement Learning,Entry,1,81093,10358,Bachelor,Gaming,Medium,3,2023,Onsite,38.6,3.85,21,84.95,0.410,66,1.43,54.53,4,61.26,19.5,12,94,63,60,41,79,55,9,1.60,71
33,34,USA,Machine Learning Engineer,MLOps,Senior,9,158412,32692,Bachelor,Healthcare,Enterprise,2,2024,Onsite,40.3,4.02,7,48.96,0.012,53,4.41,98.65,9,73.36,28.7,21,94,41,89,43,96,15,56,2.22,93
45,46,Australia,Data Analyst,Generative AI,Lead,14,93009,11108,Diploma,Retail,Medium,2,2021,Hybrid,37.5,4.07,17,87.30,0.011,61,2.25,92.55,8,84.36,27.6,22,93,22,90,43,82,49,60,2.24,80
49,50,Netherlands,Machine Learning Engineer,Analytics,Mid,5,92263,8914,Master,Consulting,Medium,6,2026,Onsite,40.0,3.93,16,61.34,0.178,75,0.49,74.17,14,55.71,35.9,13,100,21,80,46,73,45,40,1.09,73
53,54,Netherlands,Computer Vision Engineer,Analytics,Lead,16,141862,26137,Master,Education,Medium,2,2024,Hybrid,40.3,4.55,31,62.85,0.079,100,9.47,79.58,10,84.41,35.0,17,97,60,86,92,80,28,73,1.51,81

# Talent Market Intelligence - Multi-Factor Analysis

This notebook explores relationships among talent market indicators using correlation analysis, pivot tables, and cross-tabulations. Each analysis is organized into a dedicated markdown cell followed by its corresponding Python code cell.

## Correlation with Job Openings

**Business Question:** Analyze **correlation with job openings** to identify multi-dimensional hiring patterns, skill demand, recruitment complexity, and talent market opportunities.

In [94]:
# Correlation with Job Openings

talent_market_corr = (
    df[[
        "job_openings",
        "skill_demand_score",
        "hiring_difficulty_score",
        "interview_rounds",
        "salary_usd",
        "bonus_usd",
        "career_growth_score",
        "job_security_score",
        "ai_adoption_score",
        "company_rating"
    ]]
    .corr()["job_openings"]
    .sort_values(ascending=False)
    .round(2)
)

talent_market_corr

job_openings               1.0
bonus_usd                  0.0
salary_usd                 0.0
job_security_score         0.0
ai_adoption_score          0.0
company_rating             0.0
interview_rounds           0.0
skill_demand_score        -0.0
career_growth_score       -0.0
hiring_difficulty_score   -0.0
Name: job_openings, dtype: float64

## Average Job Openings by Country and Experience Level

**Business Question:** Analyze **average job openings by country and experience level** to identify multi-dimensional hiring patterns, skill demand, recruitment complexity, and talent market opportunities.

In [95]:
# Average Job Openings by Country and Experience Level

pd.pivot_table(
    df,
    values="job_openings",
    index="country",
    columns="experience_level",
    aggfunc="mean"
).round(2)

experience_level  Entry   Lead    Mid  Senior
country
Australia         17.37  17.82  17.59   17.44
Brazil            17.25  17.69  17.49   17.46
Canada            17.45  17.54  17.56   17.55
France            17.68  16.99  17.68   17.25
Germany           17.57  17.27  17.26   17.43
India             17.48  17.24  17.78   17.59
Japan             17.37  17.45  17.71   17.72
Netherlands       17.40  17.52  17.72   17.39
Singapore         17.55  17.67  17.72   17.54
UAE               17.33  17.58  17.41   17.36
UK                17.53  17.47  17.72   17.83
USA               17.55  17.74  17.56   17.72

## Average Skill Demand by AI Specialization and Experience Level

**Business Question:** Analyze **average skill demand by ai specialization and experience level** to identify multi-dimensional hiring patterns, skill demand, recruitment complexity, and talent market opportunities.

In [96]:
# Average Skill Demand by AI Specialization and Experience Level

pd.pivot_table(
    df,
    values="skill_demand_score",
    index="ai_specialization",
    columns="experience_level",
    aggfunc="mean"
).round(2)

experience_level        Entry   Lead    Mid  Senior
ai_specialization
Analytics               50.54  50.54  51.34   50.36
Computer Vision         50.06  49.98  50.11   50.30
Forecasting             50.74  50.68  50.46   51.11
Generative AI           51.11  50.30  50.40   50.11
LLM                     51.56  50.94  50.75   50.09
MLOps                   50.12  50.64  50.04   50.92
NLP                     50.10  49.93  51.18   50.39
Reinforcement Learning  49.04  51.23  49.98   49.73

## Average Hiring Difficulty by Job Role and Experience Level

**Business Question:** Analyze **average hiring difficulty by job role and experience level** to identify multi-dimensional hiring patterns, skill demand, recruitment complexity, and talent market opportunities.

In [97]:
# Average Hiring Difficulty by Job Role and Experience Level

pd.pivot_table(
    df,
    values="hiring_difficulty_score",
    index="job_role",
    columns="experience_level",
    aggfunc="mean"
).round(2)

experience_level           Entry   Lead    Mid  Senior
job_role
AI Engineer                54.49  55.31  55.12   55.22
AI Software Engineer       54.60  55.14  54.78   55.20
Computer Vision Engineer   55.08  54.93  54.98   55.10
Data Analyst               54.57  55.70  54.94   55.11
Data Scientist             55.63  54.80  54.78   54.96
Machine Learning Engineer  54.94  55.07  54.91   55.29
NLP Engineer               55.33  54.52  55.17   55.44
Research Scientist         55.42  55.05  54.77   54.60

## Average Interview Rounds by Industry and Experience Level

**Business Question:** Analyze **average interview rounds by industry and experience level** to identify multi-dimensional hiring patterns, skill demand, recruitment complexity, and talent market opportunities.

In [98]:
# Average Interview Rounds by Industry and Experience Level

pd.pivot_table(
    df,
    values="interview_rounds",
    index="industry",
    columns="experience_level",
    aggfunc="mean"
).round(2)

experience_level  Entry  Lead   Mid  Senior
industry
Automotive         4.49  4.47  4.49    4.51
Consulting         4.54  4.51  4.52    4.47
Education          4.49  4.50  4.50    4.46
Energy             4.51  4.49  4.48    4.54
Finance            4.58  4.54  4.50    4.43
Gaming             4.54  4.41  4.54    4.53
Healthcare         4.49  4.45  4.43    4.45
Retail             4.48  4.52  4.44    4.48
Tech               4.55  4.46  4.57    4.52
Telecom            4.48  4.44  4.50    4.53

## Job Openings by Country and Industry

**Business Question:** Analyze **job openings by country and industry** to identify multi-dimensional hiring patterns, skill demand, recruitment complexity, and talent market opportunities.

In [99]:
# Job Openings by Country and Industry

pd.crosstab(
    index=df["country"],
    columns=df["industry"],
    values=df["job_openings"],
    aggfunc="mean"
).round(2)

industry,Automotive,Consulting,Education,Energy,Finance,Gaming,Healthcare,Retail,Tech,Telecom
country,,,,,,,,,,
Australia,17.66,17.33,17.84,17.17,17.63,18.09,17.43,17.41,17.34,17.70
Brazil,17.38,18.22,17.09,17.43,17.44,17.27,17.72,17.12,17.65,17.40
Canada,17.30,17.59,17.32,17.94,17.58,17.61,17.75,17.20,17.06,17.98
France,17.79,17.03,17.13,17.33,16.97,17.18,17.87,17.56,17.53,17.60
Germany,17.53,17.24,17.50,17.34,16.86,17.44,17.57,17.32,17.43,17.55
India,17.49,17.17,17.59,17.40,17.70,17.43,18.17,17.33,17.37,17.51
Japan,17.35,17.09,17.37,17.97,17.85,17.45,17.62,17.38,17.90,17.65
Netherlands,17.49,17.12,17.72,17.69,17.79,17.41,17.62,17.54,17.30,17.43
Singapore,17.49,17.62,17.49,17.71,18.04,17.82,17.48,17.39,17.45,17.65
UAE,17.35,17.58,16.77,17.68,17.84,17.27,16.98,17.41,17.88,17.48
UK,17.23,17.79,17.38,17.70,17.36,17.67,17.68,17.85,18.02,17.68
USA,17.24,17.42,17.97,17.57,17.55,17.45,17.85,17.82,17.54,18.10

## Skill Demand by Country and AI Specialization

**Business Question:** Analyze **skill demand by country and ai specialization** to identify multi-dimensional hiring patterns, skill demand, recruitment complexity, and talent market opportunities.

In [100]:
# Skill Demand by Country and AI Specialization

pd.crosstab(
    index=df["country"],
    columns=df["ai_specialization"],
    values=df["skill_demand_score"],
    aggfunc="mean"
).round(2)

ai_specialization,Analytics,Computer Vision,Forecasting,Generative AI,LLM,MLOps,NLP,Reinforcement Learning
country,,,,,,,,
Australia,50.82,50.56,52.64,48.70,50.99,50.58,51.05,50.55
Brazil,49.17,50.20,50.46,51.23,49.71,50.18,49.95,49.38
Canada,52.23,49.23,51.01,51.12,50.42,49.03,49.92,49.71
France,50.42,48.04,50.88,50.84,49.78,50.98,49.43,51.24
Germany,50.23,51.04,49.45,51.05,51.96,49.33,48.53,49.94
India,50.96,48.85,51.29,49.32,53.11,50.61,50.66,49.51
Japan,51.82,50.97,50.33,51.38,51.34,51.66,50.48,49.92
Netherlands,50.03,49.77,50.99,49.22,51.09,51.23,51.12,49.46
Singapore,50.40,50.38,49.67,50.97,49.37,49.76,51.96,49.73
UAE,51.18,50.40,50.91,49.46,51.62,49.93,51.35,49.21
UK,50.45,50.58,50.88,50.32,49.61,50.39,50.66,50.07
USA,50.74,51.26,50.39,52.16,51.02,51.47,49.75,51.16

## Hiring Difficulty by Job Role and AI Specialization

**Business Question:** Analyze **hiring difficulty by job role and ai specialization** to identify multi-dimensional hiring patterns, skill demand, recruitment complexity, and talent market opportunities.

In [101]:
# Hiring Difficulty by Job Role and AI Specialization

pd.crosstab(
    index=df["job_role"],
    columns=df["ai_specialization"],
    values=df["hiring_difficulty_score"],
    aggfunc="mean"
).round(2)

ai_specialization,Analytics,Computer Vision,Forecasting,Generative AI,LLM,MLOps,NLP,Reinforcement Learning
job_role,,,,,,,,
AI Engineer,55.00,54.88,55.51,54.77,54.99,54.89,55.92,54.32
AI Software Engineer,55.27,55.09,54.51,54.38,55.26,54.92,55.26,54.78
Computer Vision Engineer,54.96,54.61,54.51,55.32,54.94,55.36,55.40,55.10
Data Analyst,53.81,55.72,54.56,54.71,55.16,55.30,55.58,55.71
Data Scientist,56.04,55.59,54.52,54.81,54.30,54.99,54.69,55.35
Machine Learning Engineer,54.93,54.55,54.85,54.75,56.18,54.77,55.41,55.00
NLP Engineer,54.82,54.98,55.43,55.59,54.83,56.13,54.57,54.57
Research Scientist,55.48,54.13,55.70,55.23,54.92,54.16,55.25,54.88

# Talent Market Intelligence - Feature Engineering

This notebook creates engineered talent market metrics to measure hiring demand, market opportunities, recruitment competitiveness, and skill value. Each engineered feature is introduced with a business question followed by its implementation.

## Talent Demand Index

**Business Question:** Evaluate **talent demand index** to derive actionable talent market intelligence, identify high-opportunity segments, and support strategic recruitment planning.

In [102]:
# Talent Demand Index

df["talent_demand_index"] = (
    (
        df["job_openings"] +
        df["skill_demand_score"] +
        df["ai_adoption_score"]
    ) / 3
).round(2)

## Hiring Efficiency Score

**Business Question:** Evaluate **hiring efficiency score** to derive actionable talent market intelligence, identify high-opportunity segments, and support strategic recruitment planning.

In [103]:
# Hiring Efficiency Score

df["hiring_efficiency_score"] = (
    df["job_openings"] /
    (df["interview_rounds"] + 1)
).round(2)

## Market Opportunity Index

**Business Question:** Evaluate **market opportunity index** to derive actionable talent market intelligence, identify high-opportunity segments, and support strategic recruitment planning.

In [104]:
# Market Opportunity Index

df["market_opportunity_index"] = (
    (
        df["job_openings"] +
        df["career_growth_score"] +
        df["salary_percentile"]
    ) / 3
).round(2)

## Skill Premium Index

**Business Question:** Evaluate **skill premium index** to derive actionable talent market intelligence, identify high-opportunity segments, and support strategic recruitment planning.

In [105]:
# Skill Premium Index

df["skill_premium_index"] = (
    (
        df["skill_demand_score"] *
        df["salary_percentile"]
    ) / 100
).round(2)

## Recruitment Competitiveness Score

**Business Question:** Evaluate **recruitment competitiveness score** to derive actionable talent market intelligence, identify high-opportunity segments, and support strategic recruitment planning.

In [106]:
# Recruitment Competitiveness Score

df["recruitment_competitiveness_score"] = (
    (
        df["skill_demand_score"] +
        df["hiring_difficulty_score"] +
        (df["interview_rounds"] * 10)
    ) / 3
).round(2)

## Engineered Metrics Summary

**Business Question:** Evaluate **engineered metrics summary** to derive actionable talent market intelligence, identify high-opportunity segments, and support strategic recruitment planning.

In [107]:
# Engineered Metrics Summary

df[[
    "talent_demand_index",
    "hiring_efficiency_score",
    "market_opportunity_index",
    "skill_premium_index",
    "recruitment_competitiveness_score"
]].describe().round(2)

,talent_demand_index,hiring_efficiency_score,market_opportunity_index,skill_premium_index,recruitment_competitiveness_score
count,90000.00,90000.00,90000.00,90000.00,90000.00
mean,46.45,3.56,41.75,25.48,50.15
std,10.98,2.10,10.84,22.21,12.69
min,12.33,0.12,10.33,0.01,7.33
25%,38.00,2.12,33.33,7.04,41.02
50%,46.33,3.17,41.67,19.17,50.17
75%,55.00,4.67,50.33,38.94,59.25
max,78.33,16.67,74.33,100.00,90.00

## Top 10 Talent Demand

**Business Question:** Evaluate **top 10 talent demand** to derive actionable talent market intelligence, identify high-opportunity segments, and support strategic recruitment planning.

In [108]:
# Top 10 Talent Demand

df.nlargest(
    10,
    "talent_demand_index"
)[[
    "job_role",
    "country",
    "talent_demand_index"
]]

                       job_role    country  talent_demand_index
29793        Research Scientist  Australia                78.33
58917               AI Engineer        USA                78.33
16467        Research Scientist     France                78.00
37807  Computer Vision Engineer  Australia                78.00
41766              Data Analyst     Brazil                77.67
2592       AI Software Engineer  Singapore                77.33
35447            Data Scientist  Australia                77.00
65697               AI Engineer         UK                77.00
89055               AI Engineer      Japan                77.00
33890        Research Scientist        USA                76.33

## Top 10 Market Opportunity

**Business Question:** Evaluate **top 10 market opportunity** to derive actionable talent market intelligence, identify high-opportunity segments, and support strategic recruitment planning.

In [109]:
# Top 10 Market Opportunity

df.nlargest(
    10,
    "market_opportunity_index"
)[[
    "job_role",
    "country",
    "market_opportunity_index"
]]

                        job_role      country  market_opportunity_index
51909   Computer Vision Engineer          UAE                     74.33
86042         Research Scientist       Canada                     74.00
36585         Research Scientist    Singapore                     73.67
35949       AI Software Engineer           UK                     73.33
73217       AI Software Engineer        Japan                     72.67
78172               Data Analyst       Brazil                     72.67
15347                AI Engineer          UAE                     72.33
22474   Computer Vision Engineer       Canada                     72.33
47822  Machine Learning Engineer           UK                     72.33
49709   Computer Vision Engineer  Netherlands                     72.33

## Top 10 Skill Premium

**Business Question:** Evaluate **top 10 skill premium** to derive actionable talent market intelligence, identify high-opportunity segments, and support strategic recruitment planning.

In [110]:
# Top 10 Skill Premium

df.nlargest(
    10,
    "skill_premium_index"
)[[
    "job_role",
    "country",
    "skill_premium_index"
]]

                   job_role    country  skill_premium_index
6394           Data Analyst     Brazil                100.0
7957     Research Scientist  Australia                100.0
16022  AI Software Engineer      Japan                100.0
18795          NLP Engineer    Germany                100.0
30724        Data Scientist      Japan                100.0
54484        Data Scientist        UAE                100.0
54846          NLP Engineer  Australia                100.0
54858          NLP Engineer  Singapore                100.0
73370          NLP Engineer  Singapore                100.0
75717          NLP Engineer      Japan                100.0

## Correlation of Engineered Metrics

**Business Question:** Evaluate **correlation of engineered metrics** to derive actionable talent market intelligence, identify high-opportunity segments, and support strategic recruitment planning.

In [111]:
# Correlation of Engineered Metrics

df[[
    "job_openings",
    "skill_demand_score",
    "talent_demand_index",
    "hiring_efficiency_score",
    "market_opportunity_index",
    "skill_premium_index",
    "recruitment_competitiveness_score"
]].corr().round(2)

,job_openings,skill_demand_score,talent_demand_index,hiring_efficiency_score,market_opportunity_index,skill_premium_index,recruitment_competitiveness_score
job_openings,1.00,-0.00,0.24,0.76,0.23,-0.01,-0.00
skill_demand_score,-0.00,1.00,0.88,-0.00,-0.00,0.65,0.76
talent_demand_index,0.24,0.88,1.00,0.18,0.16,0.57,0.67
hiring_efficiency_score,0.76,-0.00,0.18,1.00,0.18,-0.00,-0.26
market_opportunity_index,0.23,-0.00,0.16,0.18,1.00,0.58,-0.00
skill_premium_index,-0.01,0.65,0.57,-0.00,0.58,1.00,0.50
recruitment_competitiveness_score,-0.00,0.76,0.67,-0.26,-0.00,0.50,1.00