# Module 3: Workforce Risk Intelligence

## Objective

Analyze workforce stability, layoff risk, automation risk, AI adoption, and job security to identify the key factors influencing employment risk in the AI workforce.

### Business Questions

- Which professionals have the highest job security?
- Which countries have the highest layoff risk?
- Does AI adoption improve job security?
- Which job roles are most vulnerable to automation?
- Which industries are most stable?
- What factors contribute to workforce risk?

In [1]:
import warnings
import platform
import numpy as np
import pandas as pd

# Configure execution environment and suppress warnings
warnings.filterwarnings("ignore")

# Optimize pandas display configurations for comprehensive data inspection.
pd.set_option("display.max_columns", None)
pd.set_option("display.max_rows", 100)
pd.set_option("display.width", None)

# Log framework metadata and verification metrics.

print("Environment Information")
print("-" * 22)
print(f"Python Version : {platform.python_version()}")
print(f"Pandas Version : {pd.__version__}")
print(f"NumPy Version  : {np.__version__}")

Environment Information
----------------------
Python Version : 3.14.6
Pandas Version : 3.0.3
NumPy Version  : 2.4.6

In [2]:
# Load target dataset

DATA_PATH = "../../../data/processed/cleaned_ai_jobs.csv"
df = pd.read_csv(DATA_PATH)
print("\nDataset Loaded Successfully")

# Execute descriptive matrix shape verification.

print("\nDataset Shape")
print("-" * 16)

total_rows, total_columns = df.shape

print(f"Rows    : {total_rows:,}")
print(f"Columns : {total_columns}")
print("-" * 16)

# Display a quick preview of the dataset schema.

display(df.head())

Dataset Loaded Successfully

Dataset Shape
----------------
Rows    : 90,000
Columns : 35
----------------

,id,country,job_role,ai_specialization,experience_level,experience_years,salary_usd,bonus_usd,education_required,industry,company_size,interview_rounds,year,work_mode,weekly_hours,company_rating,job_openings,hiring_difficulty_score,layoff_risk,ai_adoption_score,company_funding_billion,economic_index,ai_maturity_years,offer_acceptance_rate,tax_rate_percent,vacation_days,skill_demand_score,automation_risk,job_security_score,career_growth_score,work_life_balance_score,promotion_speed,salary_percentile,cost_of_living_index,employee_satisfaction
0,1,UAE,Machine Learning Engineer,Reinforcement Learning,Entry,0,66465,5395,Master,Automotive,Small,7,2020,Remote,44.7,3.67,10,52.77,0.404,91,3.30,78.65,13,60.58,20.8,27,12,76,57,65,73,15,55,1.23,76
1,2,USA,AI Engineer,LLM,Entry,1,75507,11713,Bootcamp,Retail,Small,3,2021,Onsite,48.9,4.26,27,53.11,0.387,71,4.39,62.14,13,75.80,28.4,27,54,29,69,60,51,15,58,0.87,67
2,3,Brazil,Research Scientist,Analytics,Entry,0,41660,5268,Phd,Healthcare,Large,3,2020,Remote,46.8,4.78,10,76.40,0.415,69,5.04,87.47,8,62.95,12.2,13,12,49,70,59,68,37,13,2.13,61
3,4,India,AI Software Engineer,Computer Vision,Senior,6,43268,7975,Diploma,Tech,Large,2,2026,Onsite,52.2,4.34,23,59.34,0.115,74,4.38,86.84,7,77.45,35.1,30,80,47,79,65,55,46,74,1.49,56
4,5,Germany,Machine Learning Engineer,Computer Vision,Entry,0,69119,4758,Master,Retail,Medium,2,2021,Hybrid,46.7,4.49,17,72.30,0.311,68,6.67,79.84,7,89.86,36.1,24,82,47,64,52,69,17,21,0.87,72

# Workforce Risk Intelligence - Foundation Analysis

This notebook organizes the foundational Workforce Risk Intelligence analysis into individual business questions. Each analysis is separated into its own markdown and code cell for clarity and presentation.

# Workforce Risk Intelligence - Ranking & Elite Segment Analysis

This notebook presents ranking analysis, percentile analysis, and elite workforce segmentation for Workforce Risk Intelligence. Each business question is organized into separate markdown and code cells for clarity and presentation.

## Top 10 Countries with Highest Job Security

**Business Question:** Analyze **top 10 countries with highest job security** to identify high-risk and high-security workforce segments, benchmark organizational resilience, and support strategic workforce planning.

In [3]:
# Top 10 Countries with Highest Job Security

df.groupby("country")[
    "job_security_score"
].mean().sort_values(ascending=False).head(10).round(2)

country
UAE            75.79
Australia      75.74
Japan          75.69
Netherlands    75.67
Brazil         75.62
Germany        75.57
USA            75.54
Singapore      75.53
Canada         75.46
UK             75.44
Name: job_security_score, dtype: float64

## Top 10 Countries with Highest Layoff Risk

**Business Question:** Analyze **top 10 countries with highest layoff risk** to identify high-risk and high-security workforce segments, benchmark organizational resilience, and support strategic workforce planning.

In [4]:
# Top 10 Countries with Highest Layoff Risk

df.groupby("country")[
    "layoff_risk"
].mean().sort_values(ascending=False).head(10).round(2)

country
India          0.18
UK             0.18
France         0.18
Canada         0.18
Singapore      0.18
Netherlands    0.18
USA            0.18
Germany        0.18
Australia      0.18
Brazil         0.18
Name: layoff_risk, dtype: float64

## Top 10 Job Roles with Highest Job Security

**Business Question:** Analyze **top 10 job roles with highest job security** to identify high-risk and high-security workforce segments, benchmark organizational resilience, and support strategic workforce planning.

In [5]:
# Top 10 Job Roles with Highest Job Security

df.groupby("job_role")[
    "job_security_score"
].mean().sort_values(ascending=False).head(10).round(2)

job_role
Data Scientist               75.78
AI Software Engineer         75.67
Research Scientist           75.59
NLP Engineer                 75.53
AI Engineer                  75.51
Computer Vision Engineer     75.51
Machine Learning Engineer    75.48
Data Analyst                 75.45
Name: job_security_score, dtype: float64

## Top 10 Job Roles with Highest Automation Risk

**Business Question:** Analyze **top 10 job roles with highest automation risk** to identify high-risk and high-security workforce segments, benchmark organizational resilience, and support strategic workforce planning.

In [6]:
# Top 10 Job Roles with Highest Automation Risk

df.groupby("job_role")[
    "automation_risk"
].mean().sort_values(ascending=False).head(10).round(2)

job_role
Computer Vision Engineer     50.64
AI Software Engineer         50.62
Research Scientist           50.61
Data Analyst                 50.34
Data Scientist               50.22
NLP Engineer                 50.18
Machine Learning Engineer    50.15
AI Engineer                  50.09
Name: automation_risk, dtype: float64

## Top Industries by Job Security

**Business Question:** Analyze **top industries by job security** to identify high-risk and high-security workforce segments, benchmark organizational resilience, and support strategic workforce planning.

In [7]:
# Top Industries by Job Security

df.groupby("industry")[
    "job_security_score"
].mean().sort_values(ascending=False).head(10).round(2)

industry
Tech          75.81
Retail        75.62
Education     75.59
Healthcare    75.57
Finance       75.56
Gaming        75.55
Telecom       75.54
Energy        75.48
Automotive    75.48
Consulting    75.44
Name: job_security_score, dtype: float64

## Top Industries by AI Adoption

**Business Question:** Analyze **top industries by ai adoption** to identify high-risk and high-security workforce segments, benchmark organizational resilience, and support strategic workforce planning.

In [8]:
# Top Industries by AI Adoption

df.groupby("industry")[
    "ai_adoption_score"
].mean().sort_values(ascending=False).head(10).round(2)

industry
Automotive    71.61
Tech          71.45
Consulting    71.45
Telecom       71.45
Finance       71.40
Energy        71.39
Education     71.38
Healthcare    71.29
Gaming        71.18
Retail        71.17
Name: ai_adoption_score, dtype: float64

## Job Security Quartiles

**Business Question:** Analyze **job security quartiles** to identify high-risk and high-security workforce segments, benchmark organizational resilience, and support strategic workforce planning.

In [9]:
# Job Security Quartiles

df["job_security_score"].quantile(
    [0.25, 0.50, 0.75]
).round(2)

0.25    68.0
0.50    77.0
0.75    84.0
Name: job_security_score, dtype: float64

## Layoff Risk Quartiles

**Business Question:** Analyze **layoff risk quartiles** to identify high-risk and high-security workforce segments, benchmark organizational resilience, and support strategic workforce planning.

In [10]:
# Layoff Risk Quartiles

df["layoff_risk"].quantile(
    [0.25, 0.50, 0.75]
).round(2)

0.25    0.08
0.50    0.14
0.75    0.28
Name: layoff_risk, dtype: float64

## Automation Risk Quartiles

**Business Question:** Analyze **automation risk quartiles** to identify high-risk and high-security workforce segments, benchmark organizational resilience, and support strategic workforce planning.

In [11]:
# Automation Risk Quartiles

df["automation_risk"].quantile(
    [0.25, 0.50, 0.75]
).round(2)

0.25    25.0
0.50    50.0
0.75    75.0
Name: automation_risk, dtype: float64

## Top 10% Secure Workforce

**Business Question:** Analyze **top 10% secure workforce** to identify high-risk and high-security workforce segments, benchmark organizational resilience, and support strategic workforce planning.

In [12]:
# Top 10% Secure Workforce

secure_workforce = (
    df[
        df["job_security_score"] >=
        df["job_security_score"].quantile(0.90)
    ]
)

secure_workforce.head()

,id,country,job_role,ai_specialization,experience_level,experience_years,salary_usd,bonus_usd,education_required,industry,company_size,interview_rounds,year,work_mode,weekly_hours,company_rating,job_openings,hiring_difficulty_score,layoff_risk,ai_adoption_score,company_funding_billion,economic_index,ai_maturity_years,offer_acceptance_rate,tax_rate_percent,vacation_days,skill_demand_score,automation_risk,job_security_score,career_growth_score,work_life_balance_score,promotion_speed,salary_percentile,cost_of_living_index,employee_satisfaction
6,7,Japan,Data Analyst,LLM,Senior,9,71014,11956,Phd,Tech,Small,5,2020,Hybrid,36.6,4.37,17,61.21,0.042,78,3.41,65.23,4,80.29,31.0,16,73,92,93,42,96,67,41,1.57,80
14,15,Japan,Data Analyst,Forecasting,Senior,7,64231,3378,Bootcamp,Telecom,Medium,5,2020,Remote,47.7,4.74,24,89.80,0.110,72,8.98,94.79,6,62.83,14.1,17,9,44,89,73,68,31,3,0.70,74
28,29,Japan,Computer Vision Engineer,Computer Vision,Lead,15,139135,21003,Bachelor,Energy,Startup,7,2022,Remote,39.8,4.70,1,90.95,0.039,61,6.57,54.97,11,57.66,34.2,11,48,75,90,53,85,58,71,1.65,87
33,34,USA,Machine Learning Engineer,MLOps,Senior,9,158412,32692,Bachelor,Healthcare,Enterprise,2,2024,Onsite,40.3,4.02,7,48.96,0.012,53,4.41,98.65,9,73.36,28.7,21,94,41,89,43,96,15,56,2.22,93
42,43,Germany,Research Scientist,Forecasting,Lead,14,180739,9690,Bachelor,Retail,Medium,7,2023,Hybrid,45.1,4.34,13,80.37,0.084,86,6.04,77.40,6,66.09,39.3,18,43,41,92,79,68,38,70,0.59,79

## Top 10% High-Risk Workforce

**Business Question:** Analyze **top 10% high-risk workforce** to identify high-risk and high-security workforce segments, benchmark organizational resilience, and support strategic workforce planning.

In [13]:
# Top 10% High-Risk Workforce

high_risk_workforce = (
    df[
        df["layoff_risk"] >=
        df["layoff_risk"].quantile(0.90)
    ]
)

high_risk_workforce.head()

,id,country,job_role,ai_specialization,experience_level,experience_years,salary_usd,bonus_usd,education_required,industry,company_size,interview_rounds,year,work_mode,weekly_hours,company_rating,job_openings,hiring_difficulty_score,layoff_risk,ai_adoption_score,company_funding_billion,economic_index,ai_maturity_years,offer_acceptance_rate,tax_rate_percent,vacation_days,skill_demand_score,automation_risk,job_security_score,career_growth_score,work_life_balance_score,promotion_speed,salary_percentile,cost_of_living_index,employee_satisfaction
0,1,UAE,Machine Learning Engineer,Reinforcement Learning,Entry,0,66465,5395,Master,Automotive,Small,7,2020,Remote,44.7,3.67,10,52.77,0.404,91,3.30,78.65,13,60.58,20.8,27,12,76,57,65,73,15,55,1.23,76
2,3,Brazil,Research Scientist,Analytics,Entry,0,41660,5268,Phd,Healthcare,Large,3,2020,Remote,46.8,4.78,10,76.40,0.415,69,5.04,87.47,8,62.95,12.2,13,12,49,70,59,68,37,13,2.13,61
10,11,France,AI Software Engineer,NLP,Entry,1,62612,6106,Diploma,Automotive,Large,2,2026,Onsite,46.5,4.03,22,52.70,0.400,76,5.52,93.26,14,84.63,32.9,18,65,98,58,58,70,45,23,1.90,61
12,13,Netherlands,AI Engineer,Reinforcement Learning,Entry,1,81093,10358,Bachelor,Gaming,Medium,3,2023,Onsite,38.6,3.85,21,84.95,0.410,66,1.43,54.53,4,61.26,19.5,12,94,63,60,41,79,55,9,1.60,71
51,52,France,Machine Learning Engineer,Generative AI,Entry,0,63084,3351,Phd,Gaming,Enterprise,2,2023,Onsite,53.9,3.37,17,76.30,0.417,51,0.87,80.00,13,83.26,12.9,20,2,54,64,33,55,12,63,2.37,67

## Workforce Risk Overview

**Business Question:** Analyze **workforce risk overview** to identify workforce risk patterns, evaluate organizational resilience, and support data-driven workforce planning.

In [14]:
# Workforce Risk Overview

df[[
    "layoff_risk",
    "automation_risk",
    "job_security_score",
    "ai_adoption_score"
]].describe().round(2)

       layoff_risk  automation_risk  job_security_score  ai_adoption_score
count     90000.00         90000.00            90000.00           90000.00
mean          0.18            50.36               75.56              71.38
std           0.13            28.85               11.32              13.77
min           0.00             1.00               29.00               1.00
25%           0.08            25.00               68.00              62.00
50%           0.14            50.00               77.00              71.00
75%           0.28            75.00               84.00              81.00
max           0.59           100.00               99.00             100.00

## Job Security by Experience Level

**Business Question:** Analyze **job security by experience level** to identify workforce risk patterns, evaluate organizational resilience, and support data-driven workforce planning.

In [15]:
# Job Security by Experience Level

df.groupby("experience_level")[
    "job_security_score"
].agg(["mean", "median", "min", "max"]).round(2)

                   mean  median  min  max
experience_level
Entry             61.54    62.0   29   86
Lead              82.43    83.0   50   99
Mid               75.51    76.0   45   99
Senior            82.58    83.0   53   99

## Layoff Risk by Experience Level

**Business Question:** Analyze **layoff risk by experience level** to identify workforce risk patterns, evaluate organizational resilience, and support data-driven workforce planning.

In [16]:
# Layoff Risk by Experience Level

df.groupby("experience_level")[
    "layoff_risk"
].mean().round(2)

experience_level
Entry     0.38
Lead      0.08
Mid       0.18
Senior    0.08
Name: layoff_risk, dtype: float64

## Automation Risk by Job Role

**Business Question:** Analyze **automation risk by job role** to identify workforce risk patterns, evaluate organizational resilience, and support data-driven workforce planning.

In [17]:
# Automation Risk by Job Role

df.groupby("job_role")[
    "automation_risk"
].mean().sort_values(ascending=False).round(2)

job_role
Computer Vision Engineer     50.64
AI Software Engineer         50.62
Research Scientist           50.61
Data Analyst                 50.34
Data Scientist               50.22
NLP Engineer                 50.18
Machine Learning Engineer    50.15
AI Engineer                  50.09
Name: automation_risk, dtype: float64

## Job Security by Country

**Business Question:** Analyze **job security by country** to identify workforce risk patterns, evaluate organizational resilience, and support data-driven workforce planning.

In [18]:
# Job Security by Country

df.groupby("country")[
    "job_security_score"
].mean().sort_values(ascending=False).round(2)

country
UAE            75.79
Australia      75.74
Japan          75.69
Netherlands    75.67
Brazil         75.62
Germany        75.57
USA            75.54
Singapore      75.53
Canada         75.46
UK             75.44
France         75.37
India          75.35
Name: job_security_score, dtype: float64

## Layoff Risk by Country

**Business Question:** Analyze **layoff risk by country** to identify workforce risk patterns, evaluate organizational resilience, and support data-driven workforce planning.

In [19]:
# Layoff Risk by Country

df.groupby("country")[
    "layoff_risk"
].mean().sort_values(ascending=False).round(2)

country
India          0.18
UK             0.18
France         0.18
Canada         0.18
Singapore      0.18
Netherlands    0.18
USA            0.18
Germany        0.18
Australia      0.18
Brazil         0.18
Japan          0.18
UAE            0.18
Name: layoff_risk, dtype: float64

## Job Security by Industry

**Business Question:** Analyze **job security by industry** to identify workforce risk patterns, evaluate organizational resilience, and support data-driven workforce planning.

In [20]:
# Job Security by Industry

df.groupby("industry")[
    "job_security_score"
].mean().sort_values(ascending=False).round(2)

industry
Tech          75.81
Retail        75.62
Education     75.59
Healthcare    75.57
Finance       75.56
Gaming        75.55
Telecom       75.54
Energy        75.48
Automotive    75.48
Consulting    75.44
Name: job_security_score, dtype: float64

## AI Adoption by Industry

**Business Question:** Analyze **ai adoption by industry** to identify workforce risk patterns, evaluate organizational resilience, and support data-driven workforce planning.

In [21]:
# AI Adoption by Industry

df.groupby("industry")[
    "ai_adoption_score"
].mean().sort_values(ascending=False).round(2)

industry
Automotive    71.61
Tech          71.45
Consulting    71.45
Telecom       71.45
Finance       71.40
Energy        71.39
Education     71.38
Healthcare    71.29
Gaming        71.18
Retail        71.17
Name: ai_adoption_score, dtype: float64

# Workforce Risk Intelligence - Multi-Factor Analysis

This notebook explores relationships between workforce risk metrics using correlation analysis, pivot tables, and cross-tabulations. Each business question is presented in a separate markdown and code cell for a clean, presentation-ready workflow.

## Correlation with Job Security Score

**Business Question:** Analyze **correlation with job security score** to identify multi-dimensional workforce risk patterns and support strategic workforce planning and organizational resilience.

In [22]:
# Correlation with Job Security Score

workforce_risk_corr = (
    df[[
        "job_security_score",
        "layoff_risk",
        "automation_risk",
        "ai_adoption_score",
        "career_growth_score",
        "promotion_speed",
        "salary_usd",
        "skill_demand_score",
        "employee_satisfaction",
        "company_rating"
    ]]
    .corr()["job_security_score"]
    .sort_values(ascending=False)
    .round(2)
)

workforce_risk_corr

job_security_score       1.00
employee_satisfaction    0.48
salary_usd               0.43
career_growth_score      0.06
promotion_speed          0.06
automation_risk          0.01
company_rating           0.00
ai_adoption_score       -0.00
skill_demand_score      -0.00
layoff_risk             -0.81
Name: job_security_score, dtype: float64

## Average Job Security by Country and Experience Level

**Business Question:** Analyze **average job security by country and experience level** to identify multi-dimensional workforce risk patterns and support strategic workforce planning and organizational resilience.

In [23]:
# Average Job Security by Country and Experience Level

pd.pivot_table(
    df,
    values="job_security_score",
    index="country",
    columns="experience_level",
    aggfunc="mean"
).round(2)

experience_level  Entry   Lead    Mid  Senior
country
Australia         61.60  82.77  75.60   82.75
Brazil            61.29  82.46  75.55   82.56
Canada            61.35  82.63  75.42   82.58
France            61.38  82.33  75.50   82.51
Germany           61.70  82.19  75.41   82.56
India             61.52  82.41  75.35   82.58
Japan             61.50  82.34  75.67   82.41
Netherlands       61.69  82.27  75.63   82.84
Singapore         61.48  82.73  75.55   82.20
UAE               61.63  82.40  75.48   82.81
UK                61.59  82.41  75.49   82.49
USA               61.70  82.19  75.53   82.68

## Average Layoff Risk by Industry and Experience Level

**Business Question:** Analyze **average layoff risk by industry and experience level** to identify multi-dimensional workforce risk patterns and support strategic workforce planning and organizational resilience.

In [24]:
# Average Layoff Risk by Industry and Experience Level

pd.pivot_table(
    df,
    values="layoff_risk",
    index="industry",
    columns="experience_level",
    aggfunc="mean"
).round(2)

experience_level  Entry  Lead   Mid  Senior
industry
Automotive         0.38  0.08  0.18    0.08
Consulting         0.38  0.08  0.18    0.08
Education          0.38  0.08  0.18    0.08
Energy             0.38  0.08  0.18    0.08
Finance            0.38  0.08  0.18    0.08
Gaming             0.38  0.08  0.18    0.08
Healthcare         0.38  0.08  0.18    0.08
Retail             0.38  0.08  0.18    0.08
Tech               0.38  0.08  0.18    0.08
Telecom            0.38  0.08  0.18    0.08

## Average Automation Risk by Job Role and Experience Level

**Business Question:** Analyze **average automation risk by job role and experience level** to identify multi-dimensional workforce risk patterns and support strategic workforce planning and organizational resilience.

In [25]:
# Average Automation Risk by Job Role and Experience Level

pd.pivot_table(
    df,
    values="automation_risk",
    index="job_role",
    columns="experience_level",
    aggfunc="mean"
).round(2)

experience_level           Entry   Lead    Mid  Senior
job_role
AI Engineer                49.85  50.54  49.84   50.10
AI Software Engineer       51.52  50.03  50.59   50.38
Computer Vision Engineer   50.28  51.11  50.93   50.26
Data Analyst               49.67  51.01  50.70   50.00
Data Scientist             49.34  50.87  50.82   49.83
Machine Learning Engineer  50.43  49.90  49.97   50.31
NLP Engineer               49.80  51.05  50.11   49.76
Research Scientist         50.33  50.68  51.08   50.34

## Average AI Adoption Score by Industry and Experience Level

**Business Question:** Analyze **average ai adoption score by industry and experience level** to identify multi-dimensional workforce risk patterns and support strategic workforce planning and organizational resilience.

In [26]:
# Average AI Adoption Score by Industry and Experience Level

pd.pivot_table(
    df,
    values="ai_adoption_score",
    index="industry",
    columns="experience_level",
    aggfunc="mean"
).round(2)

experience_level  Entry   Lead    Mid  Senior
industry
Automotive        71.62  71.86  71.10   71.86
Consulting        71.53  71.30  71.83   71.14
Education         70.83  71.38  71.54   71.76
Energy            71.57  71.25  71.52   71.20
Finance           71.12  71.43  71.68   71.34
Gaming            70.60  71.90  71.15   71.07
Healthcare        71.66  71.38  71.28   70.87
Retail            70.99  71.41  71.25   71.02
Tech              70.96  71.75  71.46   71.58
Telecom           71.05  72.12  71.08   71.54

## Job Security by Country and Industry

**Business Question:** Analyze **job security by country and industry** to identify multi-dimensional workforce risk patterns and support strategic workforce planning and organizational resilience.

In [27]:
# Job Security by Country and Industry

pd.crosstab(
    index=df["country"],
    columns=df["industry"],
    values=df["job_security_score"],
    aggfunc="mean"
).round(2)

industry,Automotive,Consulting,Education,Energy,Finance,Gaming,Healthcare,Retail,Tech,Telecom
country,,,,,,,,,,
Australia,75.24,75.81,76.24,75.47,75.37,75.41,75.89,76.23,76.09,75.67
Brazil,75.01,75.39,75.36,75.24,75.71,75.76,75.24,75.27,77.06,76.15
Canada,75.35,74.69,75.20,75.31,75.66,75.87,75.71,75.85,75.42,75.39
France,76.23,75.12,75.09,75.66,75.95,75.09,75.50,75.37,74.98,74.74
Germany,75.49,75.70,75.65,75.55,75.00,75.43,75.65,76.11,76.37,74.83
India,75.25,75.12,76.06,75.49,74.88,74.80,75.26,75.58,75.56,75.38
Japan,75.25,75.97,76.18,75.41,75.74,76.18,75.30,75.88,75.46,75.56
Netherlands,75.87,75.09,75.95,75.96,75.95,76.05,75.09,75.07,75.52,76.09
Singapore,75.72,75.76,74.85,75.49,75.25,75.69,75.72,75.69,75.46,75.61
UAE,75.55,75.59,75.74,75.90,76.05,75.70,76.10,75.97,76.31,74.97
UK,75.45,75.84,75.10,75.14,75.76,75.64,75.63,74.81,75.14,75.83
USA,75.32,75.14,75.58,75.20,75.42,74.94,75.77,75.45,76.40,76.31

## Layoff Risk by Country and Job Role

**Business Question:** Analyze **layoff risk by country and job role** to identify multi-dimensional workforce risk patterns and support strategic workforce planning and organizational resilience.

In [28]:
# Layoff Risk by Country and Job Role

pd.crosstab(
    index=df["country"],
    columns=df["job_role"],
    values=df["layoff_risk"],
    aggfunc="mean"
).round(2)

job_role,AI Engineer,AI Software Engineer,Computer Vision Engineer,Data Analyst,Data Scientist,Machine Learning Engineer,NLP Engineer,Research Scientist
country,,,,,,,,
Australia,0.18,0.17,0.18,0.18,0.18,0.18,0.18,0.17
Brazil,0.17,0.17,0.18,0.18,0.18,0.18,0.18,0.17
Canada,0.18,0.18,0.18,0.18,0.18,0.18,0.18,0.18
France,0.18,0.17,0.18,0.19,0.19,0.18,0.19,0.18
Germany,0.18,0.17,0.17,0.18,0.18,0.18,0.18,0.19
India,0.18,0.18,0.18,0.18,0.18,0.19,0.18,0.19
Japan,0.17,0.18,0.18,0.18,0.17,0.18,0.18,0.18
Netherlands,0.18,0.18,0.18,0.18,0.18,0.18,0.17,0.18
Singapore,0.19,0.18,0.19,0.17,0.17,0.18,0.18,0.18
UAE,0.18,0.17,0.18,0.18,0.18,0.17,0.17,0.18
UK,0.18,0.19,0.18,0.18,0.17,0.18,0.18,0.19
USA,0.17,0.18,0.18,0.19,0.18,0.18,0.18,0.17

## Automation Risk by AI Specialization and Experience Level

**Business Question:** Analyze **automation risk by ai specialization and experience level** to identify multi-dimensional workforce risk patterns and support strategic workforce planning and organizational resilience.

In [29]:
# Automation Risk by AI Specialization and Experience Level

pd.crosstab(
    index=df["ai_specialization"],
    columns=df["experience_level"],
    values=df["automation_risk"],
    aggfunc="mean"
).round(2)

experience_level        Entry   Lead    Mid  Senior
ai_specialization
Analytics               50.90  50.35  50.30   49.07
Computer Vision         49.72  50.03  50.95   50.70
Forecasting             50.39  50.85  50.58   50.35
Generative AI           49.86  50.69  49.56   49.84
LLM                     49.11  51.31  51.04   49.85
MLOps                   50.27  50.21  50.22   50.05
NLP                     50.93  51.47  50.64   50.67
Reinforcement Learning  50.09  50.29  50.72   50.42

# Workforce Risk Intelligence - Feature Engineering

This notebook creates engineered workforce risk metrics to quantify organizational stability, automation resilience, workforce readiness, and overall risk exposure. Each engineered feature and its analysis is presented with a dedicated markdown and code cell.

## Workforce Stability Index

**Business Question:** Evaluate **workforce stability index** to derive advanced workforce risk intelligence, identify resilient talent segments, and support strategic workforce planning.

In [30]:
# Workforce Stability Index

df["workforce_stability_index"] = (
    (
        df["job_security_score"] +
        df["ai_adoption_score"] +
        (100 - df["layoff_risk"] * 100)
    ) / 3
).round(2)

## Automation Resilience Score

**Business Question:** Evaluate **automation resilience score** to derive advanced workforce risk intelligence, identify resilient talent segments, and support strategic workforce planning.

In [31]:
# Automation Resilience Score

df["automation_resilience_score"] = (
    (
        df["job_security_score"] +
        (100 - df["automation_risk"])
    ) / 2
).round(2)

## Risk Exposure Index

**Business Question:** Evaluate **risk exposure index** to derive advanced workforce risk intelligence, identify resilient talent segments, and support strategic workforce planning.

In [32]:
# Risk Exposure Index

df["risk_exposure_index"] = (
    (
        (df["layoff_risk"] * 100) +
        df["automation_risk"]
    ) / 2
).round(2)

## AI Workforce Readiness Score

**Business Question:** Evaluate **ai workforce readiness score** to derive advanced workforce risk intelligence, identify resilient talent segments, and support strategic workforce planning.

In [33]:
# AI Workforce Readiness Score

df["ai_workforce_readiness_score"] = (
    (
        df["job_security_score"] +
        df["ai_adoption_score"] +
        df["skill_demand_score"]
    ) / 3
).round(2)

## Stability-to-Risk Ratio

**Business Question:** Evaluate **stability-to-risk ratio** to derive advanced workforce risk intelligence, identify resilient talent segments, and support strategic workforce planning.

In [34]:
# Stability-to-Risk Ratio

df["stability_risk_ratio"] = (
    df["job_security_score"] /
    (df["layoff_risk"] * 100 + 1)
).round(2)

## Engineered Metrics Summary

**Business Question:** Evaluate **engineered metrics summary** to derive advanced workforce risk intelligence, identify resilient talent segments, and support strategic workforce planning.

In [35]:
# Engineered Metrics Summary

df[[
    "workforce_stability_index",
    "automation_resilience_score",
    "risk_exposure_index",
    "ai_workforce_readiness_score",
    "stability_risk_ratio"
]].describe().round(2)

,workforce_stability_index,automation_resilience_score,risk_exposure_index,ai_workforce_readiness_score,stability_risk_ratio
count,90000.00,90000.00,90000.00,90000.00,90000.00
mean,76.32,62.60,34.16,65.80,9.83
std,9.03,15.46,15.83,11.31,16.12
min,38.57,18.50,0.50,24.67,0.61
25%,70.17,50.00,21.69,57.33,2.40
50%,77.57,62.50,34.15,65.67,5.17
75%,82.97,75.00,46.70,74.33,9.38
max,99.67,99.00,77.65,99.33,99.00

## Top 10 Workforce Stability

**Business Question:** Evaluate **top 10 workforce stability** to derive advanced workforce risk intelligence, identify resilient talent segments, and support strategic workforce planning.

In [36]:
# Top 10 Workforce Stability

df.nlargest(
    10,
    "workforce_stability_index"
)[[
    "job_role",
    "country",
    "workforce_stability_index"
]]

                        job_role    country  workforce_stability_index
7258              Data Scientist  Singapore                      99.67
10472       AI Software Engineer  Australia                      99.67
57488             Data Scientist      India                      99.67
62048               Data Analyst    Germany                      99.67
67270               Data Analyst        UAE                      99.67
75125               Data Analyst      Japan                      99.43
16739               Data Analyst  Singapore                      99.33
56289             Data Scientist  Australia                      99.33
79311  Machine Learning Engineer  Australia                      99.33
89422             Data Scientist         UK                      99.13

## Top 10 Automation Resilience

**Business Question:** Evaluate **top 10 automation resilience** to derive advanced workforce risk intelligence, identify resilient talent segments, and support strategic workforce planning.

In [37]:
# Top 10 Automation Resilience

df.nlargest(
    10,
    "automation_resilience_score"
)[[
    "job_role",
    "country",
    "automation_resilience_score"
]]

                        job_role      country  automation_resilience_score
35441               Data Analyst        Japan                         99.0
54552   Computer Vision Engineer    Australia                         99.0
7016                Data Analyst       Brazil                         98.5
16262  Machine Learning Engineer          USA                         98.5
16298               NLP Engineer      Germany                         98.5
54618                AI Engineer          USA                         98.5
942           Research Scientist          USA                         98.0
2521              Data Scientist        Japan                         98.0
18151               NLP Engineer  Netherlands                         98.0
24234         Research Scientist  Netherlands                         98.0

## Top 10 Lowest Risk Exposure

**Business Question:** Evaluate **top 10 lowest risk exposure** to derive advanced workforce risk intelligence, identify resilient talent segments, and support strategic workforce planning.

In [38]:
# Top 10 Lowest Risk Exposure

df.nsmallest(
    10,
    "risk_exposure_index"
)[[
    "job_role",
    "country",
    "risk_exposure_index"
]]

                        job_role      country  risk_exposure_index
2078        AI Software Engineer    Australia                  0.5
2448          Research Scientist      Germany                  0.5
9496                 AI Engineer       France                  0.5
10892         Research Scientist          UAE                  0.5
11229  Machine Learning Engineer          USA                  0.5
17727                AI Engineer    Australia                  0.5
17829       AI Software Engineer    Australia                  0.5
22286       AI Software Engineer    Australia                  0.5
24267               Data Analyst  Netherlands                  0.5
26371                AI Engineer    Australia                  0.5

## Correlation of Engineered Metrics

**Business Question:** Evaluate **correlation of engineered metrics** to derive advanced workforce risk intelligence, identify resilient talent segments, and support strategic workforce planning.

In [39]:
# Correlation of Engineered Metrics

df[[
    "job_security_score",
    "layoff_risk",
    "automation_risk",
    "workforce_stability_index",
    "automation_resilience_score",
    "risk_exposure_index",
    "ai_workforce_readiness_score",
    "stability_risk_ratio"
]].corr().round(2)

,job_security_score,layoff_risk,automation_risk,workforce_stability_index,automation_resilience_score,risk_exposure_index,ai_workforce_readiness_score,stability_risk_ratio
job_security_score,1.00,-0.81,0.01,0.81,0.36,-0.33,0.33,0.46
layoff_risk,-0.81,1.00,-0.00,-0.83,-0.29,0.41,-0.27,-0.52
automation_risk,0.01,-0.00,1.00,0.01,-0.93,0.91,0.01,0.01
workforce_stability_index,0.81,-0.83,0.01,1.00,0.29,-0.34,0.48,0.44
automation_resilience_score,0.36,-0.29,-0.93,0.29,1.00,-0.97,0.12,0.16
risk_exposure_index,-0.33,0.41,0.91,-0.34,-0.97,1.00,-0.11,-0.21
ai_workforce_readiness_score,0.33,-0.27,0.01,0.48,0.12,-0.11,1.00,0.15
stability_risk_ratio,0.46,-0.52,0.01,0.44,0.16,-0.21,0.15,1.00